import { add as _ssrg_int_add } from "@seseragi/runtime/int"
import { Just as _ssrg_maybe_Just, maybeFunctor as _ssrg_maybe_functor, maybeApplicative as _ssrg_maybe_applicative, maybeMonad as _ssrg_maybe_monad, Nothing as _ssrg_maybe_Nothing } from "@seseragi/runtime/sum"
import { println as _ssrg_console_println } from "@seseragi/runtime/console"

const increment = (value: number) => _ssrg_int_add(value, 1)
const incrementMaybe = (value: number) => _ssrg_maybe_Just(_ssrg_int_add(value, 2))
const mapWith = (operation: (argument: (argument: number) => number) => (argument: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: number }) => { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: number }) => operation(increment)(_ssrg_maybe_Just(41))
const applyWith = (operation: (argument: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: number }) => { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: number }) => operation(_ssrg_maybe_Just(41))
const bindWith = (operation: (argument: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: number }) => (argument: (argument: number) => { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: number }) => { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: number }) => (value: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: number }) => operation(value)(incrementMaybe)
const bindGeneric = <M, A, B,>(value: unknown) => (next: (argument: A) => unknown) => (__ssrg$evidence$0: Readonly<Record<string, (...args: any[]) => any>>) => __ssrg$evidence$0["flatMap"](next)(value)
const render = (checks: readonly [{ readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: number }, { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: number }, { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: number }, { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: number }]) => (($ssrg_match: readonly [{ readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: number }, { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: number }, { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: number }, { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: number }]): string => $ssrg_match[0].tag === "Just" && $ssrg_match[0].value === 42 && $ssrg_match[1].tag === "Just" && $ssrg_match[1].value === 42 && $ssrg_match[2].tag === "Just" && $ssrg_match[2].value === 42 && $ssrg_match[3].tag === "Nothing" ? "Type-class sections: map / apply / bind / short-circuit" : "unexpected type-class section result")(checks)
export const main = (_unit: undefined) => _ssrg_console_println(render([mapWith((__ssrg$operator$argument$0) => (__ssrg$operator$argument$1) => _ssrg_maybe_functor["map"](__ssrg$operator$argument$0)(__ssrg$operator$argument$1)), applyWith((__ssrg$operator$argument$1) => _ssrg_maybe_applicative["apply"](_ssrg_maybe_Just(increment))(__ssrg$operator$argument$1)), ((bindGeneric(_ssrg_maybe_Just(40))(incrementMaybe)(_ssrg_maybe_monad)) as { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: number }), bindWith((__ssrg$operator$argument$0) => (__ssrg$operator$argument$1) => _ssrg_maybe_monad["flatMap"](__ssrg$operator$argument$1)(__ssrg$operator$argument$0))(_ssrg_maybe_Nothing)] as const))
