import { Nothing as _ssrg_maybe_Nothing, Just as _ssrg_maybe_Just } from "@seseragi/runtime/sum"
import { add as _ssrg_int_add, multiply as _ssrg_int_multiply } from "@seseragi/runtime/int"
import { stringEq as _ssrg_string_eq_dictionary } from "@seseragi/runtime/equality"
import { stringAdd as _ssrg_string_add_dictionary } from "@seseragi/runtime/string"
import { flatMap as _ssrg_effect_flatMap } from "@seseragi/runtime/effect"
import { println as _ssrg_console_println } from "@seseragi/runtime/console"

export const __ssrg$instance$Functor$0 = { "map": <A, B,>(f: (argument: A) => B) => (value: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: A }) => (($ssrg_match: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: A }): { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: B } => $ssrg_match.tag === "Nothing" ? _ssrg_maybe_Nothing : $ssrg_match.tag === "Just" ? ((item: A): { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: B } => _ssrg_maybe_Just(f(item)))($ssrg_match.value) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(value) } as const;
export const __ssrg$instance$Applicative$1 = (__ssrg$evidence$0: Readonly<Record<string, (...args: any[]) => any>>) => ({ ...__ssrg$evidence$0, "pure": <A,>(value: A) => _ssrg_maybe_Just(value), "apply": <A, B,>(wrapped: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: (argument: A) => B }) => (value: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: A }) => (($ssrg_match: readonly [{ readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: (argument: A) => B }, { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: A }]): { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: B } => $ssrg_match[0].tag === "Just" && $ssrg_match[1].tag === "Just" ? ((_function: (argument: A) => B, item: A): { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: B } => _ssrg_maybe_Just(_function(item)))($ssrg_match[0].value, $ssrg_match[1].value) : _ssrg_maybe_Nothing)([wrapped, value] as const) }) as const;
export const __ssrg$instance$Monad$2 = (__ssrg$evidence$0: Readonly<Record<string, (...args: any[]) => any>>) => ({ ...__ssrg$evidence$0, "flatMap": <A, B,>(f: (argument: A) => { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: B }) => (value: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: A }) => (($ssrg_match: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: A }): { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: B } => $ssrg_match.tag === "Nothing" ? _ssrg_maybe_Nothing : $ssrg_match.tag === "Just" ? ((item: A): { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: B } => f(item))($ssrg_match.value) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(value) }) as const;
const identityInt = (value: number) => value
const increment = (value: number) => _ssrg_int_add(value, 1)
const double = (value: number) => _ssrg_int_multiply(value, 2)
const incrementThenDouble = (value: number) => double(increment(value))
const wrapMaybe = (value: number) => _ssrg_maybe_Just(value)
const stepA = (value: number) => _ssrg_maybe_Just(_ssrg_int_add(value, 1))
const stepB = (value: number) => _ssrg_maybe_Just(_ssrg_int_multiply(value, 2))
const stepAB = (value: number) => __ssrg$instance$Monad$2(__ssrg$instance$Applicative$1(__ssrg$instance$Functor$0))["flatMap"](stepB)(stepA(value))
const render = (value: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: number }) => (($ssrg_match: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: number }): string => $ssrg_match.tag === "Nothing" ? "Nothing" : $ssrg_match.tag === "Just" && $ssrg_match.value === 21 ? "Just 21" : $ssrg_match.tag === "Just" && $ssrg_match.value === 41 ? "Just 41" : $ssrg_match.tag === "Just" && $ssrg_match.value === 42 ? "Just 42" : $ssrg_match.tag === "Just" && $ssrg_match.value === 82 ? "Just 82" : "Just another value")(value)
const report = (label: string) => (left: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: number }) => (right: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: number }) => _ssrg_string_eq_dictionary["eq"](render(left))(render(right)) ? _ssrg_string_add_dictionary["add"](label)(": ok") : _ssrg_string_add_dictionary["add"](label)(": failed")
export const main = (_unit: undefined) => _ssrg_effect_flatMap(_ssrg_console_println(report("Functor identity")(__ssrg$instance$Functor$0["map"](identityInt)(_ssrg_maybe_Just(21)))(_ssrg_maybe_Just(21))), () => _ssrg_effect_flatMap(_ssrg_console_println(report("Functor composition")(__ssrg$instance$Functor$0["map"](incrementThenDouble)(_ssrg_maybe_Just(20)))(__ssrg$instance$Functor$0["map"](double)(__ssrg$instance$Functor$0["map"](increment)(_ssrg_maybe_Just(20))))), () => _ssrg_effect_flatMap(_ssrg_console_println(report("Applicative identity")(__ssrg$instance$Applicative$1(__ssrg$instance$Functor$0)["apply"](__ssrg$instance$Applicative$1(__ssrg$instance$Functor$0)["pure"](identityInt))(_ssrg_maybe_Just(21)))(_ssrg_maybe_Just(21))), () => _ssrg_effect_flatMap(_ssrg_console_println(report("Applicative homomorphism")(__ssrg$instance$Applicative$1(__ssrg$instance$Functor$0)["apply"](__ssrg$instance$Applicative$1(__ssrg$instance$Functor$0)["pure"](increment))(__ssrg$instance$Applicative$1(__ssrg$instance$Functor$0)["pure"](41)))(__ssrg$instance$Applicative$1(__ssrg$instance$Functor$0)["pure"](42))), () => _ssrg_effect_flatMap(_ssrg_console_println(report("Monad left identity")(__ssrg$instance$Monad$2(__ssrg$instance$Applicative$1(__ssrg$instance$Functor$0))["flatMap"](stepA)(__ssrg$instance$Applicative$1(__ssrg$instance$Functor$0)["pure"](40)))(stepA(40))), () => _ssrg_effect_flatMap(_ssrg_console_println(report("Monad right identity")(__ssrg$instance$Monad$2(__ssrg$instance$Applicative$1(__ssrg$instance$Functor$0))["flatMap"](wrapMaybe)(_ssrg_maybe_Just(41)))(_ssrg_maybe_Just(41))), () => _ssrg_console_println(report("Monad associativity")(__ssrg$instance$Monad$2(__ssrg$instance$Applicative$1(__ssrg$instance$Functor$0))["flatMap"](stepB)(__ssrg$instance$Monad$2(__ssrg$instance$Applicative$1(__ssrg$instance$Functor$0))["flatMap"](stepA)(_ssrg_maybe_Just(40))))(__ssrg$instance$Monad$2(__ssrg$instance$Applicative$1(__ssrg$instance$Functor$0))["flatMap"](stepAB)(_ssrg_maybe_Just(40))))))))))
