import { Nothing as _ssrg_maybe_Nothing, Just as _ssrg_maybe_Just } from "@seseragi/runtime/sum"
import { add as _ssrg_int64_add, multiply as _ssrg_int64_multiply } from "@seseragi/runtime/int64"
import { flatMap as _ssrg_effect_flatMap } from "@seseragi/runtime/effect"
import { println as _ssrg_console_println } from "@seseragi/runtime/console"

export const __ssrg$instance$Functor$0 = { "map": <A, B,>(f: (argument: A) => B) => (value: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: A }) => (($ssrg_match: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: A }): { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: B } => $ssrg_match.tag === "Nothing" ? _ssrg_maybe_Nothing : $ssrg_match.tag === "Just" ? ((item: A): { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: B } => _ssrg_maybe_Just(f(item)))($ssrg_match.value) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(value) } as const;
export const __ssrg$instance$Applicative$1 = (__ssrg$evidence$0: Readonly<Record<string, (...args: any[]) => any>>) => ({ ...__ssrg$evidence$0, "pure": <A,>(value: A) => _ssrg_maybe_Just(value), "apply": <A, B,>(wrapped: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: (argument: A) => B }) => (value: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: A }) => (($ssrg_match: readonly [{ readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: (argument: A) => B }, { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: A }]): { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: B } => $ssrg_match[0].tag === "Just" && $ssrg_match[1].tag === "Just" ? ((_function: (argument: A) => B, item: A): { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: B } => _ssrg_maybe_Just(_function(item)))($ssrg_match[0].value, $ssrg_match[1].value) : _ssrg_maybe_Nothing)([wrapped, value] as const) }) as const;
export const __ssrg$instance$Monad$2 = (__ssrg$evidence$0: Readonly<Record<string, (...args: any[]) => any>>) => ({ ...__ssrg$evidence$0, "flatMap": <A, B,>(f: (argument: A) => { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: B }) => (value: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: A }) => (($ssrg_match: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: A }): { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: B } => $ssrg_match.tag === "Nothing" ? _ssrg_maybe_Nothing : $ssrg_match.tag === "Just" ? ((item: A): { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: B } => f(item))($ssrg_match.value) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(value) }) as const;
const identityInt = (value: bigint) => value
const increment = (value: bigint) => _ssrg_int64_add(value, 1n)
const double = (value: bigint) => _ssrg_int64_multiply(value, 2n)
const incrementThenDouble = (value: bigint) => double(increment(value))
const wrapMaybe = (value: bigint) => _ssrg_maybe_Just(value)
const stepA = (value: bigint) => _ssrg_maybe_Just(_ssrg_int64_add(value, 1n))
const stepB = (value: bigint) => _ssrg_maybe_Just(_ssrg_int64_multiply(value, 2n))
const stepAB = (value: bigint) => __ssrg$instance$Monad$2(__ssrg$instance$Applicative$1(__ssrg$instance$Functor$0))["flatMap"](stepB)(stepA(value))
const render = (value: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: bigint }) => (($ssrg_match: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: bigint }): string => $ssrg_match.tag === "Nothing" ? "Nothing" : $ssrg_match.tag === "Just" && $ssrg_match.value === 21n ? "Just 21" : $ssrg_match.tag === "Just" && $ssrg_match.value === 41n ? "Just 41" : $ssrg_match.tag === "Just" && $ssrg_match.value === 42n ? "Just 42" : $ssrg_match.tag === "Just" && $ssrg_match.value === 82n ? "Just 82" : "Just another value")(value)
const report = (label: string) => (left: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: bigint }) => (right: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: bigint }) => render(left) === render(right) ? label + ": ok" : label + ": failed"
export const main = (_unit: undefined) => _ssrg_effect_flatMap(_ssrg_console_println(report("Functor identity")(__ssrg$instance$Functor$0["map"](identityInt)(_ssrg_maybe_Just(21n)))(_ssrg_maybe_Just(21n))), () => _ssrg_effect_flatMap(_ssrg_console_println(report("Functor composition")(__ssrg$instance$Functor$0["map"](incrementThenDouble)(_ssrg_maybe_Just(20n)))(__ssrg$instance$Functor$0["map"](double)(__ssrg$instance$Functor$0["map"](increment)(_ssrg_maybe_Just(20n))))), () => _ssrg_effect_flatMap(_ssrg_console_println(report("Applicative identity")(__ssrg$instance$Applicative$1(__ssrg$instance$Functor$0)["apply"](__ssrg$instance$Applicative$1(__ssrg$instance$Functor$0)["pure"](identityInt))(_ssrg_maybe_Just(21n)))(_ssrg_maybe_Just(21n))), () => _ssrg_effect_flatMap(_ssrg_console_println(report("Applicative homomorphism")(__ssrg$instance$Applicative$1(__ssrg$instance$Functor$0)["apply"](__ssrg$instance$Applicative$1(__ssrg$instance$Functor$0)["pure"](increment))(__ssrg$instance$Applicative$1(__ssrg$instance$Functor$0)["pure"](41n)))(__ssrg$instance$Applicative$1(__ssrg$instance$Functor$0)["pure"](42n))), () => _ssrg_effect_flatMap(_ssrg_console_println(report("Monad left identity")(__ssrg$instance$Monad$2(__ssrg$instance$Applicative$1(__ssrg$instance$Functor$0))["flatMap"](stepA)(__ssrg$instance$Applicative$1(__ssrg$instance$Functor$0)["pure"](40n)))(stepA(40n))), () => _ssrg_effect_flatMap(_ssrg_console_println(report("Monad right identity")(__ssrg$instance$Monad$2(__ssrg$instance$Applicative$1(__ssrg$instance$Functor$0))["flatMap"](wrapMaybe)(_ssrg_maybe_Just(41n)))(_ssrg_maybe_Just(41n))), () => _ssrg_console_println(report("Monad associativity")(__ssrg$instance$Monad$2(__ssrg$instance$Applicative$1(__ssrg$instance$Functor$0))["flatMap"](stepB)(__ssrg$instance$Monad$2(__ssrg$instance$Applicative$1(__ssrg$instance$Functor$0))["flatMap"](stepA)(_ssrg_maybe_Just(40n))))(__ssrg$instance$Monad$2(__ssrg$instance$Applicative$1(__ssrg$instance$Functor$0))["flatMap"](stepAB)(_ssrg_maybe_Just(40n))))))))))
