import { combine as ops_combine, display as ops_display, inspect as ops_inspect, same as ops_same, errors as ops_errors, convert as ops_convert } from "./operations.js"
import { assertUnicodeVersion as $ssrg$assertUnicodeVersion } from "@seseragi/runtime/unicode-version"
import { boundedShow as _ssrg_show_boundedShow, boundedDebug as _ssrg_debug_boundedDebug, stringShow as _ssrg_show_stringShow, stringDebug as _ssrg_debug_stringDebug, intShow as _ssrg_show_intShow, intDebug as _ssrg_debug_intDebug, boolShow as _ssrg_show_boolShow, listShow as _ssrg_show_listShow, nonEmptyListShow as _ssrg_show_nonEmptyListShow, eitherShow as _ssrg_show_eitherShow, type Show as _ssrg_show_Show, type Debug as _ssrg_debug_Debug } from "@seseragi/runtime/show"
import { stringEq as _ssrg_string_eq_dictionary, intEq as _ssrg_int_eq_dictionary } from "@seseragi/runtime/equality"
import { flatMap as _ssrg_effect_flatMap } from "@seseragi/runtime/effect"
import { invalid as _ssrg_validation_invalid, type Validation as Validation } from "@seseragi/runtime/validation"
import { add as _ssrg_int_add } from "@seseragi/runtime/int"
import { println as _ssrg_console_println } from "@seseragi/runtime/console"
import { type List as List, type NonEmptyList as NonEmptyList } from "@seseragi/runtime/list"
$ssrg$assertUnicodeVersion("17.0.0")

type Problem =
  | { readonly tag: "Problem"; readonly value: string };
const Problem = (value: string): Problem => ({ tag: "Problem", value } as const);
export const __ssrg$instance$Show$0: _ssrg_show_Show<Problem> = _ssrg_show_boundedShow((value: Problem): string => { switch (value.tag) { case "Problem": return "Problem" + " " + _ssrg_show_stringShow.show(value.value); } });
export const __ssrg$instance$Debug$1: _ssrg_debug_Debug<Problem> = _ssrg_debug_boundedDebug((value: Problem): string => { switch (value.tag) { case "Problem": return "Problem" + " " + _ssrg_debug_stringDebug.debug(value.value); } });
export const __ssrg$instance$Eq$2 = { "eq": (left: Problem) => (right: Problem) => (($ssrg_match: readonly [Problem, Problem]): boolean => $ssrg_match[0].tag === "Problem" && $ssrg_match[1].tag === "Problem" ? ((a: string, b: string): boolean => _ssrg_string_eq_dictionary["eq"](a)(b))($ssrg_match[0].value, $ssrg_match[1].value) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())([left, right] as const) } as const;
export const main = (_unit: undefined) => (() => { const left: Validation<Problem, number> = _ssrg_validation_invalid(Problem("first")); return (() => { const right: Validation<Problem, number> = _ssrg_validation_invalid(Problem("second")); return (() => { const result: Validation<Problem, number> = ops_combine([(a: number) => (b: number) => _ssrg_int_add(a, b), left, right] as const); return _ssrg_effect_flatMap(_ssrg_console_println(((ops_display(result)(__ssrg$instance$Show$0)(_ssrg_show_intShow)) as string)), () => _ssrg_effect_flatMap(_ssrg_console_println(((ops_inspect(result)(__ssrg$instance$Debug$1)(_ssrg_debug_intDebug)) as string)), () => (() => { const same: boolean = ((ops_same(result)(result)(__ssrg$instance$Eq$2)(_ssrg_int_eq_dictionary)) as boolean); return _ssrg_effect_flatMap(_ssrg_console_println(((_ssrg_show_boolShow["show"](same)) as string)), () => _ssrg_effect_flatMap(_ssrg_console_println(((_ssrg_show_listShow<Problem>(__ssrg$instance$Show$0)["show"](ops_errors(result))) as string)), () => (() => { const convert: (argument: Validation<Problem, number>) => { readonly tag: "Left"; readonly value: NonEmptyList<Problem> } | { readonly tag: "Right"; readonly value: number } = ops_convert; return (() => { const converted: { readonly tag: "Left"; readonly value: NonEmptyList<Problem> } | { readonly tag: "Right"; readonly value: number } = convert(result); return _ssrg_console_println(((_ssrg_show_eitherShow<NonEmptyList<Problem>, number>(_ssrg_show_nonEmptyListShow<Problem>(__ssrg$instance$Show$0), _ssrg_show_intShow)["show"](converted)) as string)); })(); })())); })())); })(); })(); })()
