import { assertUnicodeVersion as $ssrg$assertUnicodeVersion } from "@seseragi/runtime/unicode-version"
import { flatMap as _ssrg_effect_flatMap, type Effect as Effect } from "@seseragi/runtime/effect"
import { make as _ssrg_signal_make, map as _ssrg_signal_map, signalFunctor as _ssrg_signal_functor, constant as _ssrg_signal_constant, signalApplicative as _ssrg_signal_applicative, subscribe as _ssrg_signal_subscribe, set as _ssrg_signal_set, unsubscribe as _ssrg_signal_unsubscribe, read as _ssrg_signal_read, type MutableSignal as MutableSignal, type Signal as Signal, type Subscription as Subscription } from "@seseragi/runtime/signal"
import { multiply as _ssrg_int_multiply, add as _ssrg_int_add } from "@seseragi/runtime/int"
import { println as _ssrg_console_println } from "@seseragi/runtime/console"
import { intShow as _ssrg_show_intShow } from "@seseragi/runtime/show"
$ssrg$assertUnicodeVersion("17.0.0")

export const main = (_unit: undefined) => _ssrg_effect_flatMap(_ssrg_signal_make<number>(10), (source: MutableSignal<number>) => _ssrg_effect_flatMap(_ssrg_signal_make<number>(0), (mirror: MutableSignal<number>) => (() => { const values: Signal<number> = _ssrg_signal_map((value: number) => value, source); return (() => { const doubled: Signal<number> = _ssrg_signal_functor["map"]((value: number) => _ssrg_int_multiply(value, 2))(values); return (() => { const functions: Signal<(argument: number) => number> = _ssrg_signal_constant((value: number) => _ssrg_int_add(value, 2)); return (() => { const answer: Signal<number> = _ssrg_signal_applicative["apply"](functions)(doubled); return _ssrg_effect_flatMap(_ssrg_signal_subscribe((value: number) => _ssrg_signal_set(value, mirror), answer), (subscription: Subscription) => _ssrg_effect_flatMap(_ssrg_signal_set(20, source), () => _ssrg_effect_flatMap(_ssrg_signal_unsubscribe(subscription), () => _ssrg_effect_flatMap(_ssrg_signal_read(mirror), (current: number) => _ssrg_console_println("Signal Functor / Applicative: " + _ssrg_show_intShow["show"](current)))))); })(); })(); })(); })()))
