import { assertUnicodeVersion as $ssrg$assertUnicodeVersion } from "@seseragi/runtime/unicode-version"
import { validationApplicative as _ssrg_validation_applicative, validationEq as _ssrg_validation_eq, toEither as _ssrg_validation_toEither, type Validation as Validation } from "@seseragi/runtime/validation"
import { validationShow as _ssrg_show_validationShow, validationDebug as _ssrg_debug_validationDebug } from "@seseragi/runtime/show"
import { fromArray as _ssrg_list_from_array, toListNonEmpty as _ssrg_non_empty_list_toList, type List as List, type NonEmptyList as NonEmptyList } from "@seseragi/runtime/list"
$ssrg$assertUnicodeVersion("17.0.0")

export const combine = <E, A, B, C,>(inputs: readonly [(argument: A) => (argument: B) => C, Validation<E, A>, Validation<E, B>]) => (() => { const __ssrg$pattern$265: readonly [(argument: A) => (argument: B) => C, Validation<E, A>, Validation<E, B>] = inputs; return (() => { const f: (argument: A) => (argument: B) => C = (($ssrg_match: readonly [(argument: A) => (argument: B) => C, Validation<E, A>, Validation<E, B>]): (argument: A) => (argument: B) => C => ((f: (argument: A) => (argument: B) => C, left: Validation<E, A>, right: Validation<E, B>): (argument: A) => (argument: B) => C => f)($ssrg_match[0], $ssrg_match[1], $ssrg_match[2]))(__ssrg$pattern$265); return (() => { const left: Validation<E, A> = (($ssrg_match: readonly [(argument: A) => (argument: B) => C, Validation<E, A>, Validation<E, B>]): Validation<E, A> => ((f: (argument: A) => (argument: B) => C, left: Validation<E, A>, right: Validation<E, B>): Validation<E, A> => left)($ssrg_match[0], $ssrg_match[1], $ssrg_match[2]))(__ssrg$pattern$265); return (() => { const right: Validation<E, B> = (($ssrg_match: readonly [(argument: A) => (argument: B) => C, Validation<E, A>, Validation<E, B>]): Validation<E, B> => ((f: (argument: A) => (argument: B) => C, left: Validation<E, A>, right: Validation<E, B>): Validation<E, B> => right)($ssrg_match[0], $ssrg_match[1], $ssrg_match[2]))(__ssrg$pattern$265); return _ssrg_validation_applicative["apply"](_ssrg_validation_applicative["apply"](_ssrg_validation_applicative["pure"](f))(left))(right); })(); })(); })(); })()
export const same = <E, A,>(left: Validation<E, A>) => (right: Validation<E, A>) => (__ssrg$evidence$0: Readonly<Record<string, (...args: any[]) => any>>) => (__ssrg$evidence$1: Readonly<Record<string, (...args: any[]) => any>>) => _ssrg_validation_eq<E, A>(__ssrg$evidence$0, __ssrg$evidence$1)["eq"](left)(right)
export const display = <E, A,>(value: Validation<E, A>) => (__ssrg$evidence$0: Readonly<Record<string, (...args: any[]) => any>>) => (__ssrg$evidence$1: Readonly<Record<string, (...args: any[]) => any>>) => _ssrg_show_validationShow<E, A>(__ssrg$evidence$0, __ssrg$evidence$1)["show"](value)
export const inspect = <E, A,>(value: Validation<E, A>) => (__ssrg$evidence$0: Readonly<Record<string, (...args: any[]) => any>>) => (__ssrg$evidence$1: Readonly<Record<string, (...args: any[]) => any>>) => _ssrg_debug_validationDebug<E, A>(__ssrg$evidence$0, __ssrg$evidence$1)["debug"](value)
export const errors = <E, A,>(value: Validation<E, A>) => (($ssrg_match: Validation<E, A>): List<E> => $ssrg_match.tag === "Valid" ? _ssrg_list_from_array([] as ReadonlyArray<E>) : $ssrg_match.tag === "Invalid" ? ((items: NonEmptyList<E>): List<E> => _ssrg_non_empty_list_toList(items))($ssrg_match.value) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(value)
export const convert = <E, A,>(value: Validation<E, A>) => _ssrg_validation_toEither(value)
