import { add as _ssrg_int_add, multiply as _ssrg_int_multiply } from "@seseragi/runtime/int"
import { fromArray as _ssrg_list_from_array, length as _ssrg_list_length, type List as List } from "@seseragi/runtime/list"
import { collectMap as _ssrg_array_comprehend, length as _ssrg_array_length, arrayIterable as _ssrg_array_iterable } from "@seseragi/runtime/array"
import { Just as _ssrg_maybe_Just, Nothing as _ssrg_maybe_Nothing, maybeMonad as _ssrg_maybe_monad, maybeApplicative as _ssrg_maybe_applicative } from "@seseragi/runtime/sum"
import { flatMap as _ssrg_effect_flatMap, succeed as _ssrg_effect_succeed, type Effect as Effect } from "@seseragi/runtime/effect"
import { forEach as _ssrg_collection_for_each } from "@seseragi/runtime/collection"
import { println as _ssrg_console_println, type Console as Console, type ConsoleError as ConsoleError } from "@seseragi/runtime/console"
import { stringShow as _ssrg_show_stringShow, intShow as _ssrg_show_intShow } from "@seseragi/runtime/show"

type UserId =
  | { readonly tag: "UserId"; readonly value: number };
const UserId = (value: number): UserId => ({ tag: "UserId", value } as const);
declare const __ssrg$brand$User: unique symbol;
type User = {
  readonly "id": number;
  readonly "name": string;
  readonly [__ssrg$brand$User]: true;
};
const blockTotal = (_unit: undefined) => (() => { const __ssrg$pattern$476: readonly [number, number] = [1, 2] as const; return (() => { const left: number = (($ssrg_match: readonly [number, number]): number => ((left: number, right: number): number => left)($ssrg_match[0], $ssrg_match[1]))(__ssrg$pattern$476); return (() => { const right: number = (($ssrg_match: readonly [number, number]): number => ((left: number, right: number): number => right)($ssrg_match[0], $ssrg_match[1]))(__ssrg$pattern$476); return (() => { const __ssrg$pattern$506: { readonly "value": number } = ({ "value": 3 } as const); return (() => { const value: number = (($ssrg_match: { readonly "value": number }): number => ((value: number): number => value)($ssrg_match["value"]))(__ssrg$pattern$506); return (() => { const __ssrg$pattern$537: User = (({ "id": 4, "name": "Mio" } as const) as unknown as User); return (() => { const localId: number = (($ssrg_match: User): number => ((localId: number, localName: string): number => localId)($ssrg_match["id"], $ssrg_match["name"]))(__ssrg$pattern$537); return (() => { const localName: string = (($ssrg_match: User): string => ((localId: number, localName: string): string => localName)($ssrg_match["id"], $ssrg_match["name"]))(__ssrg$pattern$537); return (() => { const __ssrg$pattern$611: UserId = UserId(localId); return (() => { const unwrapped: number = (($ssrg_match: UserId): number => $ssrg_match.tag === "UserId" ? ((unwrapped: number): number => unwrapped)($ssrg_match.value) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(__ssrg$pattern$611); return (() => { const __ssrg$pattern$651: ReadonlyArray<number> = arrayValues; return (() => { const localArray: ReadonlyArray<number> = (($ssrg_match: ReadonlyArray<number>): ReadonlyArray<number> => $ssrg_match.length >= 0 ? ((localArray: ReadonlyArray<number>): ReadonlyArray<number> => localArray)($ssrg_match.slice(0)) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(__ssrg$pattern$651); return (() => { const __ssrg$pattern$687: List<number> = listValues; return (() => { const localList: List<number> = (($ssrg_match: List<number>): List<number> => true ? ((localList: List<number>): List<number> => localList)($ssrg_match) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(__ssrg$pattern$687); return _ssrg_int_add(_ssrg_int_add(_ssrg_int_add(_ssrg_int_add(_ssrg_int_add(left, right), value), unwrapped), _ssrg_array_length(localArray)), _ssrg_list_length(localList)); })(); })(); })(); })(); })(); })(); })(); })(); })(); })(); })(); })(); })(); })()
const matchPair = (pair: readonly [number, string]) => (($ssrg_match: readonly [number, string]): number => ((number: number, label: string): number => number)($ssrg_match[0], $ssrg_match[1]))(pair)
const monadPair = (value: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: readonly [number, number] }) => _ssrg_maybe_monad["flatMap"]((__ssrg$pattern$969: readonly [number, number]) => (() => { const left: number = (($ssrg_match: readonly [number, number]): number => ((left: number, right: number): number => left)($ssrg_match[0], $ssrg_match[1]))(__ssrg$pattern$969); return (() => { const right: number = (($ssrg_match: readonly [number, number]): number => ((left: number, right: number): number => right)($ssrg_match[0], $ssrg_match[1]))(__ssrg$pattern$969); return (() => { const __ssrg$pattern$996: readonly [number, number] = [1, 2] as const; return (() => { const offset: number = (($ssrg_match: readonly [number, number]): number => ((offset: number, scale: number): number => offset)($ssrg_match[0], $ssrg_match[1]))(__ssrg$pattern$996); return (() => { const scale: number = (($ssrg_match: readonly [number, number]): number => ((offset: number, scale: number): number => scale)($ssrg_match[0], $ssrg_match[1]))(__ssrg$pattern$996); return _ssrg_maybe_applicative["pure"](_ssrg_int_multiply(_ssrg_int_add(_ssrg_int_add(left, right), offset), scale)); })(); })(); })(); })(); })())(value)
export const main = (_unit: undefined) => (() => { const __ssrg$pattern$1173: readonly [number, number] = [increment(10), double(10)] as const; return (() => { const first: number = (($ssrg_match: readonly [number, number]): number => ((first: number, second: number): number => first)($ssrg_match[0], $ssrg_match[1]))(__ssrg$pattern$1173); return (() => { const second: number = (($ssrg_match: readonly [number, number]): number => ((first: number, second: number): number => second)($ssrg_match[0], $ssrg_match[1]))(__ssrg$pattern$1173); return _ssrg_effect_flatMap(_ssrg_effect_succeed([3, 4] as const), (__ssrg$pattern$1225: readonly [number, number]) => (() => { const third: number = (($ssrg_match: readonly [number, number]): number => ((third: number, fourth: number): number => third)($ssrg_match[0], $ssrg_match[1]))(__ssrg$pattern$1225); return (() => { const fourth: number = (($ssrg_match: readonly [number, number]): number => ((third: number, fourth: number): number => fourth)($ssrg_match[0], $ssrg_match[1]))(__ssrg$pattern$1225); return _ssrg_effect_flatMap(_ssrg_collection_for_each(_ssrg_array_iterable, ($ssrg_for_value: readonly [number, string]) => (($ssrg_match: readonly [number, string]): Effect<{ readonly "console": Console }, ConsoleError, undefined> => ((value: number, label: string): Effect<{ readonly "console": Console }, ConsoleError, undefined> => _ssrg_console_println(_ssrg_show_stringShow["show"](label) + ": " + _ssrg_show_intShow["show"](value)))($ssrg_match[0], $ssrg_match[1]))($ssrg_for_value), [[_ssrg_int_add(x, y), name] as const, [rawId, "id"] as const]), () => _ssrg_console_println("binding total: " + _ssrg_show_intShow["show"](_ssrg_int_add(_ssrg_int_add(_ssrg_int_add(_ssrg_int_add(_ssrg_int_add(_ssrg_int_add(first, second), third), fourth), blockTotal(undefined)), matchPair([5, "ok"] as const)), _ssrg_array_length(filtered))))); })(); })()); })(); })(); })()
const operations: readonly [(argument: number) => number, (argument: number) => number] = [(value: number) => _ssrg_int_add(value, 1), (value: number) => _ssrg_int_multiply(value, 2)] as const;
const __ssrg$pattern$236: readonly [(argument: number) => number, (argument: number) => number] = operations;
const increment: (argument: number) => number = (($ssrg_match: readonly [(argument: number) => number, (argument: number) => number]): (argument: number) => number => ((increment: (argument: number) => number, double: (argument: number) => number): (argument: number) => number => increment)($ssrg_match[0], $ssrg_match[1]))(__ssrg$pattern$236);
const double: (argument: number) => number = (($ssrg_match: readonly [(argument: number) => number, (argument: number) => number]): (argument: number) => number => ((increment: (argument: number) => number, double: (argument: number) => number): (argument: number) => number => double)($ssrg_match[0], $ssrg_match[1]))(__ssrg$pattern$236);
const __ssrg$pattern$273: { readonly "x": number; readonly "y": number } = ({ "x": 20, "y": 22 } as const);
const x: number = (($ssrg_match: { readonly "x": number; readonly "y": number }): number => ((x: number, y: number): number => x)($ssrg_match["x"], $ssrg_match["y"]))(__ssrg$pattern$273);
const y: number = (($ssrg_match: { readonly "x": number; readonly "y": number }): number => ((x: number, y: number): number => y)($ssrg_match["x"], $ssrg_match["y"]))(__ssrg$pattern$273);
const __ssrg$pattern$305: User = (({ "id": 40, "name": "Aki" } as const) as unknown as User);
const id: number = (($ssrg_match: User): number => ((id: number, name: string): number => id)($ssrg_match["id"], $ssrg_match["name"]))(__ssrg$pattern$305);
const name: string = (($ssrg_match: User): string => ((id: number, name: string): string => name)($ssrg_match["id"], $ssrg_match["name"]))(__ssrg$pattern$305);
const __ssrg$pattern$358: UserId = UserId(id);
const rawId: number = (($ssrg_match: UserId): number => $ssrg_match.tag === "UserId" ? ((rawId: number): number => rawId)($ssrg_match.value) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(__ssrg$pattern$358);
const __ssrg$pattern$387: ReadonlyArray<number> = [1, 2, 3];
const arrayValues: ReadonlyArray<number> = (($ssrg_match: ReadonlyArray<number>): ReadonlyArray<number> => $ssrg_match.length >= 0 ? ((arrayValues: ReadonlyArray<number>): ReadonlyArray<number> => arrayValues)($ssrg_match.slice(0)) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(__ssrg$pattern$387);
const __ssrg$pattern$420: List<number> = _ssrg_list_from_array([4, 5]);
const listValues: List<number> = (($ssrg_match: List<number>): List<number> => true ? ((listValues: List<number>): List<number> => listValues)($ssrg_match) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(__ssrg$pattern$420);
const filtered: ReadonlyArray<number> = _ssrg_array_comprehend([_ssrg_maybe_Just(1), _ssrg_maybe_Nothing, _ssrg_maybe_Just(2)], ($ssrg_item0) => (($ssrg_match: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: number }): boolean => $ssrg_match.tag === "Just" ? ((number: number): boolean => true)($ssrg_match.value) : false)($ssrg_item0), ($ssrg_item0) => (($ssrg_match: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: number }): number => $ssrg_match.tag === "Just" ? ((number: number): number => number)($ssrg_match.value) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())($ssrg_item0));
