import { type Score, ordered, __ssrg$instance$Eq$0, __ssrg$instance$Ord$1 } from "./domain.js"
import { assertUnicodeVersion as $ssrg$assertUnicodeVersion } from "@seseragi/runtime/unicode-version"
import { flatMap as _ssrg_effect_flatMap } from "@seseragi/runtime/effect"
import { println as _ssrg_console_println } from "@seseragi/runtime/console"
import { boolShow as _ssrg_show_boolShow, tupleShow as _ssrg_show_tupleShow } from "@seseragi/runtime/show"
$ssrg$assertUnicodeVersion("17.0.0")

const localGeneric = <A,>(left: A) => (right: A) => (__ssrg$evidence$0: Readonly<Record<string, (...args: any[]) => any>>) => (__ssrg$evidence$0["compare"](left)(right))["tag"] !== "Less"
export const main = (_unit: undefined) => (() => { const low: Score = (({ "value": 2 } as const) as unknown as Score); return (() => { const high: Score = (({ "value": 1 } as const) as unknown as Score); return (() => { const lower: (argument: Score) => (argument: Score) => boolean = (((__ssrg$comparison$left) => (__ssrg$comparison$right) => (__ssrg$instance$Ord$1(__ssrg$instance$Eq$0)["compare"](__ssrg$comparison$left)(__ssrg$comparison$right))["tag"] === "Less") as (argument: Score) => (argument: Score) => boolean); return _ssrg_effect_flatMap(_ssrg_console_println(_ssrg_show_tupleShow<readonly [boolean, boolean, boolean, boolean]>(_ssrg_show_boolShow, _ssrg_show_boolShow, _ssrg_show_boolShow, _ssrg_show_boolShow)["show"]([(__ssrg$instance$Ord$1(__ssrg$instance$Eq$0)["compare"](low)(high))["tag"] === "Less", (__ssrg$instance$Ord$1(__ssrg$instance$Eq$0)["compare"](low)(high))["tag"] !== "Greater", (__ssrg$instance$Ord$1(__ssrg$instance$Eq$0)["compare"](high)(low))["tag"] === "Greater", (__ssrg$instance$Ord$1(__ssrg$instance$Eq$0)["compare"](high)(low))["tag"] !== "Less"] as const)), () => _ssrg_console_println(_ssrg_show_tupleShow<readonly [boolean, boolean, boolean]>(_ssrg_show_boolShow, _ssrg_show_boolShow, _ssrg_show_boolShow)["show"]([((ordered(low)(high)(__ssrg$instance$Ord$1(__ssrg$instance$Eq$0))) as boolean), ((localGeneric(high)(low)(__ssrg$instance$Ord$1(__ssrg$instance$Eq$0))) as boolean), lower(low)(high)] as const))); })(); })(); })()
