[package]
name = "seseragi-driver"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
semver.workspace = true
seseragi-formatter = { path = "../seseragi-formatter" }
seseragi-lowering = { path = "../seseragi-lowering" }
seseragi-project = { path = "../seseragi-project" }
seseragi-provider = { path = "../seseragi-provider" }
seseragi-semantics = { path = "../seseragi-semantics" }
seseragi-source = { path = "../seseragi-source" }
seseragi-syntax = { path = "../seseragi-syntax" }

[dev-dependencies]
serde_json.workspace = true
