import { collectMap as _ssrg_array_comprehend, reduce as _ssrg_array_reduce } from "@seseragi/runtime/array"
import { Just as _ssrg_maybe_Just, Nothing as _ssrg_maybe_Nothing } from "@seseragi/runtime/sum"
import { remainder as _ssrg_int64_remainder, add as _ssrg_int64_add } from "@seseragi/runtime/int64"
import { println as _ssrg_console_println } from "@seseragi/runtime/console"

const presentValues = (unit: undefined) => _ssrg_array_comprehend([_ssrg_maybe_Just(1n), _ssrg_maybe_Nothing, _ssrg_maybe_Just(3n), _ssrg_maybe_Just(4n)], ($ssrg_item0) => (($ssrg_match: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: bigint }): boolean => $ssrg_match.tag === "Just" && ((value: bigint): boolean => _ssrg_int64_remainder(value, 2n) === 1n)($ssrg_match.value) ? ((value: bigint): boolean => true)($ssrg_match.value) : false)($ssrg_item0), ($ssrg_item0) => (($ssrg_match: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: bigint }): bigint => $ssrg_match.tag === "Just" ? ((value: bigint): bigint => value)($ssrg_match.value) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())($ssrg_item0))
const matchingValues = (unit: undefined) => _ssrg_array_comprehend([[1n, 10n] as const, [2n, 20n] as const, [1n, 30n] as const], ($ssrg_item0) => (($ssrg_match: readonly [bigint, bigint]): boolean => $ssrg_match[0] === 1n ? ((value: bigint): boolean => true)($ssrg_match[1]) : false)($ssrg_item0), ($ssrg_item0) => (($ssrg_match: readonly [bigint, bigint]): bigint => $ssrg_match[0] === 1n ? ((value: bigint): bigint => value)($ssrg_match[1]) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())($ssrg_item0))
const presentTotal = (unit: undefined) => _ssrg_array_reduce(0n, (_argument0) => (_argument1) => _ssrg_int64_add(_argument0, _argument1), presentValues(undefined))
const matchingTotal = (unit: undefined) => _ssrg_array_reduce(0n, (_argument0) => (_argument1) => _ssrg_int64_add(_argument0, _argument1), matchingValues(undefined))
const renderTotals = (totals: readonly [bigint, bigint]) => (($ssrg_match: readonly [bigint, bigint]): string => $ssrg_match[0] === 4n && $ssrg_match[1] === 40n ? "pattern-filter totals: 4 / 40" : "unexpected pattern-filter totals")(totals)
export const main = (_unit: undefined) => _ssrg_console_println(renderTotals([presentTotal(undefined), matchingTotal(undefined)] as const))
