use std::fs;
use std::path::Path;

const FILES: &[(&str, &str)] = &[
    (
        "UNICODE-LICENSE",
        include_str!("../../../runtime/ts/UNICODE-LICENSE"),
    ),
    (
        "src/char.ts",
        include_str!("../../../runtime/ts/src/char.ts"),
    ),
    (
        "src/grapheme.ts",
        include_str!("../../../runtime/ts/src/grapheme.ts"),
    ),
    (
        "src/unicode.ts",
        include_str!("../../../runtime/ts/src/unicode.ts"),
    ),
    (
        "src/unicode-data.ts",
        include_str!("../../../runtime/ts/src/unicode-data.ts"),
    ),
    (
        "src/unicode-version.ts",
        include_str!("../../../runtime/ts/src/unicode-version.ts"),
    ),
    (
        "src/unicode-version-data.ts",
        include_str!("../../../runtime/ts/src/unicode-version-data.ts"),
    ),
    (
        "src/unicode-case.ts",
        include_str!("../../../runtime/ts/src/unicode-case.ts"),
    ),
    (
        "src/unicode-normalization.ts",
        include_str!("../../../runtime/ts/src/unicode-normalization.ts"),
    ),
    (
        "src/unicode-properties.ts",
        include_str!("../../../runtime/ts/src/unicode-properties.ts"),
    ),
    (
        "src/regex.ts",
        include_str!("../../../runtime/ts/src/regex.ts"),
    ),
    (
        "src/text-core.ts",
        include_str!("../../../runtime/ts/src/text-core.ts"),
    ),
    (
        "src/text-search.ts",
        include_str!("../../../runtime/ts/src/text-search.ts"),
    ),
    (
        "THIRD_PARTY_NOTICES.txt",
        include_str!("../../../runtime/ts/THIRD_PARTY_NOTICES.txt"),
    ),
    (
        "package.json",
        include_str!("../../../runtime/ts/package.json"),
    ),
    (
        "src/index.ts",
        include_str!("../../../runtime/ts/src/index.ts"),
    ),
    (
        "src/console.ts",
        include_str!("../../../runtime/ts/src/console.ts"),
    ),
    (
        "src/console-service.ts",
        include_str!("../../../runtime/ts/src/console-service.ts"),
    ),
    (
        "src/logger.ts",
        include_str!("../../../runtime/ts/src/logger.ts"),
    ),
    (
        "src/logger-service.ts",
        include_str!("../../../runtime/ts/src/logger-service.ts"),
    ),
    (
        "src/effect.ts",
        include_str!("../../../runtime/ts/src/effect.ts"),
    ),
    (
        "src/foreign.ts",
        include_str!("../../../runtime/ts/src/foreign.ts"),
    ),
    (
        "src/test.ts",
        include_str!("../../../runtime/ts/src/test.ts"),
    ),
    (
        "src/cleanup-defect.ts",
        include_str!("../../../runtime/ts/src/cleanup-defect.ts"),
    ),
    (
        "src/deferred.ts",
        include_str!("../../../runtime/ts/src/deferred.ts"),
    ),
    (
        "src/queue.ts",
        include_str!("../../../runtime/ts/src/queue.ts"),
    ),
    (
        "src/semaphore.ts",
        include_str!("../../../runtime/ts/src/semaphore.ts"),
    ),
    (
        "src/stream.ts",
        include_str!("../../../runtime/ts/src/stream.ts"),
    ),
    ("src/sse.ts", include_str!("../../../runtime/ts/src/sse.ts")),
    ("src/ref.ts", include_str!("../../../runtime/ts/src/ref.ts")),
    ("src/int.ts", include_str!("../../../runtime/ts/src/int.ts")),
    ("src/map.ts", include_str!("../../../runtime/ts/src/map.ts")),
    ("src/set.ts", include_str!("../../../runtime/ts/src/set.ts")),
    (
        "src/persistent-index.ts",
        include_str!("../../../runtime/ts/src/persistent-index.ts"),
    ),
    (
        "src/sequence.ts",
        include_str!("../../../runtime/ts/src/sequence.ts"),
    ),
    (
        "src/equality.ts",
        include_str!("../../../runtime/ts/src/equality.ts"),
    ),
    (
        "src/hash.ts",
        include_str!("../../../runtime/ts/src/hash.ts"),
    ),
    (
        "src/number.ts",
        include_str!("../../../runtime/ts/src/number.ts"),
    ),
    (
        "src/float.ts",
        include_str!("../../../runtime/ts/src/float.ts"),
    ),
    (
        "src/string.ts",
        include_str!("../../../runtime/ts/src/string.ts"),
    ),
    (
        "src/array.ts",
        include_str!("../../../runtime/ts/src/array.ts"),
    ),
    (
        "src/bytes.ts",
        include_str!("../../../runtime/ts/src/bytes.ts"),
    ),
    (
        "src/json.ts",
        include_str!("../../../runtime/ts/src/json.ts"),
    ),
    (
        "src/text.ts",
        include_str!("../../../runtime/ts/src/text.ts"),
    ),
    (
        "src/collection.ts",
        include_str!("../../../runtime/ts/src/collection.ts"),
    ),
    (
        "src/traversable.ts",
        include_str!("../../../runtime/ts/src/traversable.ts"),
    ),
    (
        "src/clock-value.ts",
        include_str!("../../../runtime/ts/src/clock-value.ts"),
    ),
    (
        "src/clock.ts",
        include_str!("../../../runtime/ts/src/clock.ts"),
    ),
    (
        "src/time.ts",
        include_str!("../../../runtime/ts/src/time.ts"),
    ),
    (
        "src/timezone-rules.d.ts",
        include_str!("../../../runtime/ts/src/timezone-rules.d.ts"),
    ),
    (
        "src/timezone-rules.js",
        include_str!("../../../runtime/ts/src/timezone-rules.js"),
    ),
    (
        "src/range.ts",
        include_str!("../../../runtime/ts/src/range.ts"),
    ),
    (
        "src/iterator.ts",
        include_str!("../../../runtime/ts/src/iterator.ts"),
    ),
    (
        "src/list.ts",
        include_str!("../../../runtime/ts/src/list.ts"),
    ),
    (
        "src/service.ts",
        include_str!("../../../runtime/ts/src/service.ts"),
    ),
    (
        "src/provider.ts",
        include_str!("../../../runtime/ts/src/provider.ts"),
    ),
    (
        "src/provider-package.ts",
        include_str!("../../../runtime/ts/src/provider-package.ts"),
    ),
    (
        "src/provider-conformance.ts",
        include_str!("../../../runtime/ts/src/provider-conformance.ts"),
    ),
    (
        "src/provider-clock.ts",
        include_str!("../../../runtime/ts/src/provider-clock.ts"),
    ),
    (
        "src/provider-timezones.ts",
        include_str!("../../../runtime/ts/src/provider-timezones.ts"),
    ),
    (
        "src/provider-http-server.ts",
        include_str!("../../../runtime/ts/src/provider-http-server.ts"),
    ),
    (
        "src/provider-http-client.ts",
        include_str!("../../../runtime/ts/src/provider-http-client.ts"),
    ),
    (
        "src/provider-websocket.ts",
        include_str!("../../../runtime/ts/src/provider-websocket.ts"),
    ),
    (
        "src/provider-websocket-server.ts",
        include_str!("../../../runtime/ts/src/provider-websocket-server.ts"),
    ),
    (
        "src/websocket-host-provider.ts",
        include_str!("../../../runtime/ts/src/websocket-host-provider.ts"),
    ),
    (
        "src/provider-navigation.ts",
        include_str!("../../../runtime/ts/src/provider-navigation.ts"),
    ),
    (
        "src/provider-storage.ts",
        include_str!("../../../runtime/ts/src/provider-storage.ts"),
    ),
    (
        "src/provider-filesystem.ts",
        include_str!("../../../runtime/ts/src/provider-filesystem.ts"),
    ),
    (
        "src/provider-child-process.ts",
        include_str!("../../../runtime/ts/src/provider-child-process.ts"),
    ),
    (
        "src/provider-random.ts",
        include_str!("../../../runtime/ts/src/provider-random.ts"),
    ),
    (
        "src/provider-entropy.ts",
        include_str!("../../../runtime/ts/src/provider-entropy.ts"),
    ),
    (
        "src/provider-postgres.ts",
        include_str!("../../../runtime/ts/src/provider-postgres.ts"),
    ),
    (
        "src/provider-sqlite.ts",
        include_str!("../../../runtime/ts/src/provider-sqlite.ts"),
    ),
    (
        "src/show.ts",
        include_str!("../../../runtime/ts/src/show.ts"),
    ),
    (
        "src/html.ts",
        include_str!("../../../runtime/ts/src/html.ts"),
    ),
    (
        "src/multipart.ts",
        include_str!("../../../runtime/ts/src/multipart.ts"),
    ),
    (
        "src/web-file.ts",
        include_str!("../../../runtime/ts/src/web-file.ts"),
    ),
    (
        "src/http-server.ts",
        include_str!("../../../runtime/ts/src/http-server.ts"),
    ),
    (
        "src/http-client.ts",
        include_str!("../../../runtime/ts/src/http-client.ts"),
    ),
    (
        "src/websocket.ts",
        include_str!("../../../runtime/ts/src/websocket.ts"),
    ),
    (
        "src/navigation.ts",
        include_str!("../../../runtime/ts/src/navigation.ts"),
    ),
    (
        "src/storage.ts",
        include_str!("../../../runtime/ts/src/storage.ts"),
    ),
    (
        "src/filesystem.ts",
        include_str!("../../../runtime/ts/src/filesystem.ts"),
    ),
    (
        "src/path.ts",
        include_str!("../../../runtime/ts/src/path.ts"),
    ),
    (
        "src/process.ts",
        include_str!("../../../runtime/ts/src/process.ts"),
    ),
    (
        "src/child-process.ts",
        include_str!("../../../runtime/ts/src/child-process.ts"),
    ),
    (
        "src/random.ts",
        include_str!("../../../runtime/ts/src/random.ts"),
    ),
    (
        "src/entropy.ts",
        include_str!("../../../runtime/ts/src/entropy.ts"),
    ),
    (
        "src/postgres.ts",
        include_str!("../../../runtime/ts/src/postgres.ts"),
    ),
    (
        "src/sqlite.ts",
        include_str!("../../../runtime/ts/src/sqlite.ts"),
    ),
    ("src/dom.ts", include_str!("../../../runtime/ts/src/dom.ts")),
    (
        "src/signal.ts",
        include_str!("../../../runtime/ts/src/signal.ts"),
    ),
    (
        "src/stdin.ts",
        include_str!("../../../runtime/ts/src/stdin.ts"),
    ),
    (
        "src/stdin-service.ts",
        include_str!("../../../runtime/ts/src/stdin-service.ts"),
    ),
    ("src/sum.ts", include_str!("../../../runtime/ts/src/sum.ts")),
    (
        "src/validation.ts",
        include_str!("../../../runtime/ts/src/validation.ts"),
    ),
    (
        "src/browser/console.ts",
        include_str!("../../../runtime/ts/src/browser/console.ts"),
    ),
    (
        "src/browser/logger.ts",
        include_str!("../../../runtime/ts/src/browser/logger.ts"),
    ),
    (
        "src/browser/dom.ts",
        include_str!("../../../runtime/ts/src/browser/dom.ts"),
    ),
    (
        "src/browser/host.ts",
        include_str!("../../../runtime/ts/src/browser/host.ts"),
    ),
    (
        "src/browser/providers.ts",
        include_str!("../../../runtime/ts/src/browser/providers.ts"),
    ),
    (
        "src/browser/provider-clock.ts",
        include_str!("../../../runtime/ts/src/browser/provider-clock.ts"),
    ),
    (
        "src/browser/provider-http-client.ts",
        include_str!("../../../runtime/ts/src/browser/provider-http-client.ts"),
    ),
    (
        "src/browser/provider-websocket.ts",
        include_str!("../../../runtime/ts/src/browser/provider-websocket.ts"),
    ),
    (
        "src/browser/provider-navigation.ts",
        include_str!("../../../runtime/ts/src/browser/provider-navigation.ts"),
    ),
    (
        "src/browser/provider-storage.ts",
        include_str!("../../../runtime/ts/src/browser/provider-storage.ts"),
    ),
    (
        "src/browser/ime-input.ts",
        include_str!("../../../runtime/ts/src/browser/ime-input.ts"),
    ),
    (
        "src/browser/stdin.ts",
        include_str!("../../../runtime/ts/src/browser/stdin.ts"),
    ),
];

const PROVIDER_FILES: &[(&str, &str)] = &[
    (
        "package.json",
        include_str!("../../../runtime/providers/package.json"),
    ),
    (
        "runtime-bun/clock.ts",
        include_str!("../../../runtime/providers/bun/clock.ts"),
    ),
    (
        "runtime-browser/clock.ts",
        include_str!("../../../runtime/providers/browser/clock.ts"),
    ),
    (
        "runtime-bun/timezones.ts",
        include_str!("../../../runtime/providers/bun/timezones.ts"),
    ),
    (
        "runtime-browser/timezones.ts",
        include_str!("../../../runtime/providers/browser/timezones.ts"),
    ),
    (
        "runtime-browser/http-client.ts",
        include_str!("../../../runtime/providers/browser/http-client.ts"),
    ),
    (
        "runtime-browser/websocket-client.ts",
        include_str!("../../../runtime/providers/browser/websocket-client.ts"),
    ),
    (
        "runtime-browser/navigation.ts",
        include_str!("../../../runtime/providers/browser/navigation.ts"),
    ),
    (
        "runtime-browser/storage.ts",
        include_str!("../../../runtime/providers/browser/storage.ts"),
    ),
    (
        "runtime-browser/random.ts",
        include_str!("../../../runtime/providers/browser/random.ts"),
    ),
    (
        "runtime-browser/entropy.ts",
        include_str!("../../../runtime/providers/browser/entropy.ts"),
    ),
    (
        "runtime-bun/http-server.ts",
        include_str!("../../../runtime/providers/bun/http-server.ts"),
    ),
    (
        "websocket-server-common.ts",
        include_str!("../../../runtime/providers/websocket-server-common.ts"),
    ),
    (
        "runtime-bun/websocket-client.ts",
        include_str!("../../../runtime/providers/bun/websocket-client.ts"),
    ),
    (
        "runtime-bun/websocket-server.ts",
        include_str!("../../../runtime/providers/bun/websocket-server.ts"),
    ),
    (
        "http-client.ts",
        include_str!("../../../runtime/providers/http-client.ts"),
    ),
    (
        "http1-stream.ts",
        include_str!("../../../runtime/providers/http1-stream.ts"),
    ),
    (
        "filesystem.ts",
        include_str!("../../../runtime/providers/filesystem.ts"),
    ),
    (
        "child-process.ts",
        include_str!("../../../runtime/providers/child-process.ts"),
    ),
    (
        "random.ts",
        include_str!("../../../runtime/providers/random.ts"),
    ),
    (
        "entropy.ts",
        include_str!("../../../runtime/providers/entropy.ts"),
    ),
    (
        "timezones.ts",
        include_str!("../../../runtime/providers/timezones.ts"),
    ),
    (
        "runtime-bun/http-client.ts",
        include_str!("../../../runtime/providers/bun/http-client.ts"),
    ),
    (
        "runtime-bun/filesystem.ts",
        include_str!("../../../runtime/providers/bun/filesystem.ts"),
    ),
    (
        "runtime-bun/child-process.ts",
        include_str!("../../../runtime/providers/bun/child-process.ts"),
    ),
    (
        "runtime-bun/random.ts",
        include_str!("../../../runtime/providers/bun/random.ts"),
    ),
    (
        "runtime-bun/entropy.ts",
        include_str!("../../../runtime/providers/bun/entropy.ts"),
    ),
    (
        "runtime-node/http-client.ts",
        include_str!("../../../runtime/providers/node/http-client.ts"),
    ),
    (
        "runtime-node/http-server.ts",
        include_str!("../../../runtime/providers/node/http-server.ts"),
    ),
    (
        "runtime-node/websocket-client.ts",
        include_str!("../../../runtime/providers/node/websocket-client.ts"),
    ),
    (
        "runtime-node/websocket-server.ts",
        include_str!("../../../runtime/providers/node/websocket-server.ts"),
    ),
    (
        "runtime-node/filesystem.ts",
        include_str!("../../../runtime/providers/node/filesystem.ts"),
    ),
    (
        "runtime-node/child-process.ts",
        include_str!("../../../runtime/providers/node/child-process.ts"),
    ),
    (
        "runtime-postgres/adapter.ts",
        include_str!("../../../runtime/providers/postgres/adapter.ts"),
    ),
    (
        "runtime-postgres/pg.ts",
        include_str!("../../../runtime/providers/postgres/pg.ts"),
    ),
    (
        "runtime-postgres/pg.bundle.js",
        include_str!("../../../runtime/providers/postgres/pg.bundle.js"),
    ),
    (
        "runtime-sqlite/adapter.ts",
        include_str!("../../../runtime/providers/sqlite/adapter.ts"),
    ),
    (
        "runtime-sqlite/bun.ts",
        include_str!("../../../runtime/providers/sqlite/bun.ts"),
    ),
];

/// Stages the TypeScript runtime package embedded in this Rust crate.
///
/// Both product runners and conformance use this function, so the package
/// executed by a user-facing command is the package verified by fixtures.
pub fn stage_typescript_package(target: &Path) -> Result<(), String> {
    stage_files(
        &target.join("node_modules/@seseragi/runtime"),
        FILES,
        "runtime",
    )?;
    stage_files(
        &target.join("node_modules/seseragi"),
        PROVIDER_FILES,
        "provider",
    )
}

fn stage_files(package: &Path, files: &[(&str, &str)], kind: &str) -> Result<(), String> {
    for (relative, contents) in files {
        let path = package.join(relative);
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .map_err(|error| format!("failed to create {kind} directory: {error}"))?;
        }
        fs::write(&path, contents)
            .map_err(|error| format!("failed to stage {kind} file {relative}: {error}"))?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::stage_typescript_package;
    use std::fs;

    #[test]
    fn browser_exports_share_sources_with_the_playground_registry() {
        let repository = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../..");
        for (directory, files) in [
            ("runtime/ts", super::FILES),
            ("runtime/providers", super::PROVIDER_FILES),
        ] {
            let manifest: serde_json::Value = serde_json::from_str(
                files
                    .iter()
                    .find(|(name, _)| *name == "package.json")
                    .unwrap()
                    .1,
            )
            .unwrap();
            for (name, target) in manifest["exports"].as_object().unwrap() {
                let (staged, source) = if directory == "runtime/ts" {
                    let selected = target.get("browser").unwrap_or(&target["default"]);
                    let Some(path) = selected.as_str() else {
                        continue;
                    };
                    (path.trim_start_matches("./").to_owned(), path.to_owned())
                } else {
                    let Some(name) = name.strip_prefix("./runtime-browser/") else {
                        continue;
                    };
                    let staged = target["default"].as_str().unwrap().trim_start_matches("./");
                    assert_eq!(staged, format!("runtime-browser/{name}.ts"));
                    (staged.to_owned(), format!("browser/{name}.ts"))
                };
                let embedded = files
                    .iter()
                    .find(|(path, _)| *path == staged)
                    .unwrap_or_else(|| panic!("unstaged browser export {directory}/{staged}"));
                assert_eq!(
                    embedded.1,
                    fs::read_to_string(repository.join(directory).join(source)).unwrap()
                );
            }
        }
    }

    #[test]
    fn stages_the_provider_package_exports_and_sources() {
        let root = std::env::temp_dir().join(format!(
            "seseragi-runtime-provider-package-{}",
            std::process::id()
        ));
        if root.exists() {
            fs::remove_dir_all(&root).unwrap();
        }

        stage_typescript_package(&root).unwrap();

        let package = root.join("node_modules/@seseragi/runtime");
        let manifest = fs::read_to_string(package.join("package.json")).unwrap();
        let manifest: serde_json::Value = serde_json::from_str(&manifest).unwrap();
        assert_eq!(
            manifest.pointer("/exports/.~1provider/default"),
            Some(&serde_json::Value::String("./src/provider.ts".to_owned()))
        );
        assert_eq!(
            manifest.pointer("/exports/.~1provider-package/default"),
            Some(&serde_json::Value::String(
                "./src/provider-package.ts".to_owned()
            ))
        );
        assert_eq!(
            manifest.pointer("/exports/.~1provider-conformance/default"),
            Some(&serde_json::Value::String(
                "./src/provider-conformance.ts".to_owned()
            ))
        );
        assert!(package.join("src/provider.ts").is_file());
        assert!(package.join("src/provider-package.ts").is_file());
        assert!(package.join("src/provider-conformance.ts").is_file());
        assert!(package.join("src/clock.ts").is_file());
        assert!(package.join("src/ref.ts").is_file());
        assert!(package.join("src/deferred.ts").is_file());
        assert!(package.join("src/queue.ts").is_file());
        assert!(package.join("src/semaphore.ts").is_file());
        assert!(package.join("src/cleanup-defect.ts").is_file());
        assert!(package.join("src/foreign.ts").is_file());
        assert!(package.join("src/stream.ts").is_file());
        assert!(package.join("src/sse.ts").is_file());
        assert!(package.join("src/regex.ts").is_file());
        assert!(package.join("src/multipart.ts").is_file());
        assert!(package.join("src/web-file.ts").is_file());
        assert!(package.join("src/provider-clock.ts").is_file());
        assert!(package.join("src/http-client.ts").is_file());
        assert!(package.join("src/provider-http-client.ts").is_file());
        assert!(package.join("src/websocket.ts").is_file());
        assert!(package.join("src/provider-websocket.ts").is_file());
        assert!(package.join("src/provider-websocket-server.ts").is_file());
        assert!(package.join("src/websocket-host-provider.ts").is_file());
        assert!(package.join("src/filesystem.ts").is_file());
        assert!(package.join("src/path.ts").is_file());
        assert!(package.join("src/provider-filesystem.ts").is_file());
        assert!(package.join("src/postgres.ts").is_file());
        assert!(package.join("src/provider-postgres.ts").is_file());
        assert!(package.join("src/sqlite.ts").is_file());
        assert!(package.join("src/provider-sqlite.ts").is_file());
        assert!(package.join("src/bytes.ts").is_file());
        assert!(package.join("src/json.ts").is_file());
        assert!(package.join("src/text.ts").is_file());
        assert_eq!(
            manifest.pointer("/exports/.~1bytes/default"),
            Some(&serde_json::Value::String("./src/bytes.ts".to_owned()))
        );
        assert_eq!(
            manifest.pointer("/exports/.~1json/default"),
            Some(&serde_json::Value::String("./src/json.ts".to_owned()))
        );
        assert_eq!(
            manifest.pointer("/exports/.~1text/default"),
            Some(&serde_json::Value::String("./src/text.ts".to_owned()))
        );
        assert_eq!(
            manifest.pointer("/exports/.~1path/default"),
            Some(&serde_json::Value::String("./src/path.ts".to_owned()))
        );
        assert_eq!(
            manifest.pointer("/exports/.~1websocket/default"),
            Some(&serde_json::Value::String("./src/websocket.ts".to_owned()))
        );
        let providers = root.join("node_modules/seseragi");
        let provider_manifest = fs::read_to_string(providers.join("package.json")).unwrap();
        let provider_manifest: serde_json::Value =
            serde_json::from_str(&provider_manifest).unwrap();
        assert_eq!(
            provider_manifest.pointer("/exports/.~1runtime-bun~1clock/default"),
            Some(&serde_json::Value::String(
                "./runtime-bun/clock.ts".to_owned()
            ))
        );
        assert_eq!(
            provider_manifest.pointer("/exports/.~1runtime-bun~1http-client/default"),
            Some(&serde_json::Value::String(
                "./runtime-bun/http-client.ts".to_owned()
            ))
        );
        assert_eq!(
            provider_manifest.pointer("/exports/.~1runtime-node~1http-client/default"),
            Some(&serde_json::Value::String(
                "./runtime-node/http-client.ts".to_owned()
            ))
        );
        assert_eq!(
            provider_manifest.pointer("/exports/.~1runtime-node~1http-server/default"),
            Some(&serde_json::Value::String(
                "./runtime-node/http-server.ts".to_owned()
            ))
        );
        assert_eq!(
            provider_manifest.pointer("/exports/.~1runtime-browser~1websocket-client/default"),
            Some(&serde_json::Value::String(
                "./runtime-browser/websocket-client.ts".to_owned()
            ))
        );
        assert_eq!(
            provider_manifest.pointer("/exports/.~1runtime-bun~1websocket-server/default"),
            Some(&serde_json::Value::String(
                "./runtime-bun/websocket-server.ts".to_owned()
            ))
        );
        assert_eq!(
            provider_manifest.pointer("/exports/.~1runtime-node~1websocket-server/default"),
            Some(&serde_json::Value::String(
                "./runtime-node/websocket-server.ts".to_owned()
            ))
        );
        assert_eq!(
            provider_manifest.pointer("/exports/.~1runtime-bun~1filesystem/default"),
            Some(&serde_json::Value::String(
                "./runtime-bun/filesystem.ts".to_owned()
            ))
        );
        assert_eq!(
            provider_manifest.pointer("/exports/.~1runtime-node~1filesystem/default"),
            Some(&serde_json::Value::String(
                "./runtime-node/filesystem.ts".to_owned()
            ))
        );
        assert!(providers.join("runtime-bun/clock.ts").is_file());
        assert!(providers.join("runtime-bun/http-server.ts").is_file());
        assert!(providers.join("runtime-bun/http-client.ts").is_file());
        assert!(providers.join("runtime-node/http-client.ts").is_file());
        assert!(providers.join("http1-stream.ts").is_file());
        assert!(providers.join("runtime-node/http-server.ts").is_file());
        assert!(providers
            .join("runtime-browser/websocket-client.ts")
            .is_file());
        assert!(providers.join("runtime-bun/websocket-client.ts").is_file());
        assert!(providers.join("runtime-bun/websocket-server.ts").is_file());
        assert!(providers.join("runtime-node/websocket-client.ts").is_file());
        assert!(providers.join("runtime-node/websocket-server.ts").is_file());
        assert!(providers.join("websocket-server-common.ts").is_file());
        assert!(providers.join("runtime-bun/filesystem.ts").is_file());
        assert!(providers.join("runtime-node/filesystem.ts").is_file());
        assert_eq!(
            fs::read_to_string(providers.join("runtime-browser/storage.ts")).unwrap(),
            "export { provider } from \"@seseragi/runtime/browser/provider-storage\"\n"
        );
        assert!(providers.join("runtime-postgres/adapter.ts").is_file());
        assert!(providers.join("runtime-postgres/pg.ts").is_file());
        assert!(providers.join("runtime-postgres/pg.bundle.js").is_file());
        assert!(providers.join("runtime-sqlite/adapter.ts").is_file());
        assert!(providers.join("runtime-sqlite/bun.ts").is_file());
        fs::remove_dir_all(root).unwrap();
    }
}
