import { assertUnicodeVersion as $ssrg$assertUnicodeVersion } from "@seseragi/runtime/unicode-version"
import { intOrd as _ssrg_int_ord_dictionary } from "@seseragi/runtime/equality"
import { Right as _ssrg_either_Right, Left as _ssrg_either_Left, maybeApplicative as _ssrg_maybe_applicative, Just as _ssrg_maybe_Just, eitherApplicative as _ssrg_either_applicative } from "@seseragi/runtime/sum"
import { add as _ssrg_int_add } from "@seseragi/runtime/int"
import { flatMap as _ssrg_effect_flatMap } from "@seseragi/runtime/effect"
import { arrayTraversable as _ssrg_array_traversable } from "@seseragi/runtime/array"
import { listTraversable as _ssrg_list_traversable, fromArray as _ssrg_list_from_array, nonEmptyListTraversable as _ssrg_non_empty_list_traversable, consNonEmpty as _ssrg_non_empty_list_cons, type List as List, type NonEmptyList as NonEmptyList } from "@seseragi/runtime/list"
import { println as _ssrg_console_println } from "@seseragi/runtime/console"
import { intShow as _ssrg_show_intShow, arrayShow as _ssrg_show_arrayShow, maybeShow as _ssrg_show_maybeShow, stringShow as _ssrg_show_stringShow, listShow as _ssrg_show_listShow, eitherShow as _ssrg_show_eitherShow, nonEmptyListShow as _ssrg_show_nonEmptyListShow } from "@seseragi/runtime/show"
$ssrg$assertUnicodeVersion("17.0.0")

const checked = (value: number) => (_ssrg_int_ord_dictionary["compare"](value)(3))["tag"] === "Less" ? _ssrg_either_Right(_ssrg_int_add(value, 10)) : _ssrg_either_Left("stopped")
export const main = (_unit: undefined) => (() => { const array: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: ReadonlyArray<number> } = ((_ssrg_array_traversable["traverse"]((value: number) => _ssrg_maybe_Just(_ssrg_int_add(value, 1)))([1, 2, 3])(_ssrg_maybe_applicative)) as { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: ReadonlyArray<number> }); return (() => { const list: { readonly tag: "Left"; readonly value: string } | { readonly tag: "Right"; readonly value: List<number> } = ((_ssrg_list_traversable["traverse"](checked)(_ssrg_list_from_array([1, 2]))(_ssrg_either_applicative)) as { readonly tag: "Left"; readonly value: string } | { readonly tag: "Right"; readonly value: List<number> }); return (() => { const failed: { readonly tag: "Left"; readonly value: string } | { readonly tag: "Right"; readonly value: List<number> } = ((_ssrg_list_traversable["traverse"](checked)(_ssrg_list_from_array([1, 3, 4]))(_ssrg_either_applicative)) as { readonly tag: "Left"; readonly value: string } | { readonly tag: "Right"; readonly value: List<number> }); return (() => { const nonempty: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: NonEmptyList<number> } = ((_ssrg_non_empty_list_traversable["traverse"]((value: number) => _ssrg_maybe_Just(_ssrg_int_add(value, 1)))(_ssrg_non_empty_list_cons(1, _ssrg_list_from_array([2, 3])))(_ssrg_maybe_applicative)) as { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: NonEmptyList<number> }); return _ssrg_effect_flatMap(_ssrg_console_println(((_ssrg_show_maybeShow<ReadonlyArray<number>>(_ssrg_show_arrayShow<number>(_ssrg_show_intShow))["show"](array)) as string)), () => _ssrg_effect_flatMap(_ssrg_console_println(((_ssrg_show_eitherShow<string, List<number>>(_ssrg_show_stringShow, _ssrg_show_listShow<number>(_ssrg_show_intShow))["show"](list)) as string)), () => _ssrg_effect_flatMap(_ssrg_console_println(((_ssrg_show_eitherShow<string, List<number>>(_ssrg_show_stringShow, _ssrg_show_listShow<number>(_ssrg_show_intShow))["show"](failed)) as string)), () => _ssrg_console_println(((_ssrg_show_maybeShow<NonEmptyList<number>>(_ssrg_show_nonEmptyListShow<number>(_ssrg_show_intShow))["show"](nonempty)) as string))))); })(); })(); })(); })()
