const original = new Set([3, 1, 2])
const removed = new Set(original)
removed.delete(1)
const missing = new Set(original)
missing.delete(9)
console.log(JSON.stringify([...removed]))
console.log(JSON.stringify([...new Set(removed).add(1)]))
console.log(JSON.stringify([...missing]))
console.log(JSON.stringify([...original]))
const empty = new Set<number>()
empty.delete(1)
console.log(JSON.stringify([...empty]))
export {}
