import { stringShow as _ssrg_show_stringShow, intShow as _ssrg_show_intShow, listShow as _ssrg_show_listShow, eitherShow as _ssrg_show_eitherShow, maybeShow as _ssrg_show_maybeShow, arrayShow as _ssrg_show_arrayShow, stringDebug as _ssrg_debug_stringDebug, boolDebug as _ssrg_debug_boolDebug, listDebug as _ssrg_debug_listDebug, eitherDebug as _ssrg_debug_eitherDebug, maybeDebug as _ssrg_debug_maybeDebug, arrayDebug as _ssrg_debug_arrayDebug } from "@seseragi/runtime/show"
import { flatMap as _ssrg_effect_flatMap } from "@seseragi/runtime/effect"
import { println as _ssrg_console_println } from "@seseragi/runtime/console"
import { Just as _ssrg_maybe_Just, Right as _ssrg_either_Right, Nothing as _ssrg_maybe_Nothing, Left as _ssrg_either_Left } from "@seseragi/runtime/sum"
import { fromArray as _ssrg_list_from_array, type List as List } from "@seseragi/runtime/list"

type Badge =
  | { readonly tag: "Active" }
  | { readonly tag: "Paused" };
const Active: Badge = { tag: "Active" } as const;
const Paused: Badge = { tag: "Paused" } as const;
export const __ssrg$instance$Show$0 = { "show": (value: Badge) => (($ssrg_match: Badge): string => $ssrg_match.tag === "Active" ? "active" : "paused")(value) } as const;
export const __ssrg$instance$Debug$1 = { "debug": (value: Badge) => (($ssrg_match: Badge): string => $ssrg_match.tag === "Active" ? "Badge.Active" : "Badge.Paused")(value) } as const;
export const showNested = (value: ReadonlyArray<{ readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: { readonly tag: "Left"; readonly value: string } | { readonly tag: "Right"; readonly value: List<bigint> } }>) => _ssrg_show_arrayShow<{ readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: { readonly tag: "Left"; readonly value: string } | { readonly tag: "Right"; readonly value: List<bigint> } }>(_ssrg_show_maybeShow<{ readonly tag: "Left"; readonly value: string } | { readonly tag: "Right"; readonly value: List<bigint> }>(_ssrg_show_eitherShow<string, List<bigint>>(_ssrg_show_stringShow, _ssrg_show_listShow<bigint>(_ssrg_show_intShow))))["show"](value)
export const debugNested = (value: ReadonlyArray<{ readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: { readonly tag: "Left"; readonly value: string } | { readonly tag: "Right"; readonly value: List<boolean> } }>) => _ssrg_debug_arrayDebug<{ readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: { readonly tag: "Left"; readonly value: string } | { readonly tag: "Right"; readonly value: List<boolean> } }>(_ssrg_debug_maybeDebug<{ readonly tag: "Left"; readonly value: string } | { readonly tag: "Right"; readonly value: List<boolean> }>(_ssrg_debug_eitherDebug<string, List<boolean>>(_ssrg_debug_stringDebug, _ssrg_debug_listDebug<boolean>(_ssrg_debug_boolDebug))))["debug"](value)
export const showMany = <A,>(values: ReadonlyArray<A>) => (__ssrg$evidence$0: Readonly<Record<string, (...args: any[]) => any>>) => _ssrg_show_arrayShow<A>(__ssrg$evidence$0)["show"](values)
export const debugOptional = <A,>(value: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: A }) => (__ssrg$evidence$0: Readonly<Record<string, (...args: any[]) => any>>) => _ssrg_debug_maybeDebug<A>(__ssrg$evidence$0)["debug"](value)
export const main = (_unit: undefined) => _ssrg_effect_flatMap(_ssrg_console_println(showNested([_ssrg_maybe_Just(_ssrg_either_Right(_ssrg_list_from_array([1n, 2n]))), _ssrg_maybe_Nothing, _ssrg_maybe_Just(_ssrg_either_Left("oops"))])), () => _ssrg_effect_flatMap(_ssrg_console_println(debugNested([_ssrg_maybe_Just(_ssrg_either_Right(_ssrg_list_from_array([true, false]))), _ssrg_maybe_Nothing, _ssrg_maybe_Just(_ssrg_either_Left("oops"))])), () => _ssrg_effect_flatMap(_ssrg_console_println(_ssrg_show_arrayShow<Badge>(__ssrg$instance$Show$0)["show"]([Active, Paused])), () => _ssrg_console_println(_ssrg_debug_maybeDebug<Badge>(__ssrg$instance$Debug$1)["debug"](_ssrg_maybe_Just(Active))))))
