import { assertUnicodeVersion as $ssrg$assertUnicodeVersion } from "@seseragi/runtime/unicode-version"
import { intEq as _ssrg_int_eq_dictionary } from "@seseragi/runtime/equality"
import { subtract as _ssrg_int_subtract } from "@seseragi/runtime/int"
import { println as _ssrg_console_println, type Console as Console, type ConsoleError as ConsoleError } from "@seseragi/runtime/console"
import { effectApplicative as _ssrg_effect_applicative, flatMap as _ssrg_effect_flatMap, type Effect as Effect } from "@seseragi/runtime/effect"
import { boolShow as _ssrg_show_boolShow, tupleShow as _ssrg_show_tupleShow, intShow as _ssrg_show_intShow } from "@seseragi/runtime/show"
$ssrg$assertUnicodeVersion("17.0.0")

export const main = (_unit: undefined) => (() => { const outer: number = 7; return (() => { const first = (_unit: undefined) => 99; return (() => { const even = (n: number): boolean => _ssrg_int_eq_dictionary["eq"](n)(0) ? true : odd(_ssrg_int_subtract(n, 1)); const odd = (n: number): boolean => _ssrg_int_eq_dictionary["eq"](n)(0) ? false : even(_ssrg_int_subtract(n, 1)); const first = (n: number): number => _ssrg_int_eq_dictionary["eq"](n)(0) ? outer : second(_ssrg_int_subtract(n, 1)); const second = (n: number): number => third(n); const third = (n: number): number => first(n); const identity = <A,>(value: A): A => value; const render = <A,>(value: A) => (n: number) => (__ssrg$evidence$0: Readonly<Record<string, (...args: any[]) => any>>): string => _ssrg_int_eq_dictionary["eq"](n)(0) ? ((__ssrg$evidence$0["show"](value)) as string) : ((renderNext(value)(_ssrg_int_subtract(n, 1))(__ssrg$evidence$0)) as string); const renderNext = <B,>(value: B) => (n: number) => (__ssrg$evidence$0: Readonly<Record<string, (...args: any[]) => any>>): string => ((render(value)(n)(__ssrg$evidence$0)) as string); const count = (n: number): number => { const $ssrg$tail = Symbol(); while (true) { const $ssrg$result = _ssrg_int_eq_dictionary["eq"](n)(0) ? outer : ({ [$ssrg$tail]: [_ssrg_int_subtract(n, 1)] } as never); const $ssrg$tailResult: unknown = $ssrg$result; if (typeof $ssrg$tailResult === "object" && $ssrg$tailResult !== null && $ssrg$tail in $ssrg$tailResult) { const $ssrg$arguments = ($ssrg$tailResult as { readonly [$ssrg$tail]: readonly [number] })[$ssrg$tail]; n = $ssrg$arguments[0]; continue; } return $ssrg$result; } }; const cold = (_unit: undefined): Effect<{ readonly "console": Console }, ConsoleError, undefined> => _ssrg_console_println("must stay cold"); const left = (n: number): Effect<{  }, never, number> => _ssrg_int_eq_dictionary["eq"](n)(0) ? ((_ssrg_effect_applicative["pure"](outer)) as Effect<{  }, never, number>) : right(_ssrg_int_subtract(n, 1)); const right = (n: number): Effect<{  }, never, number> => left(n); return _ssrg_effect_flatMap(_ssrg_console_println(((_ssrg_show_tupleShow<readonly [boolean, boolean]>(_ssrg_show_boolShow, _ssrg_show_boolShow)["show"]([even(8), odd(9)] as const)) as string)), () => _ssrg_effect_flatMap(_ssrg_console_println(first(3)), () => _ssrg_effect_flatMap(_ssrg_console_println(((_ssrg_show_tupleShow<readonly [boolean, number]>(_ssrg_show_boolShow, _ssrg_show_intShow)["show"]([identity(true), identity(42)] as const)) as string)), () => _ssrg_effect_flatMap(_ssrg_console_println(((render(42)(3)(_ssrg_show_intShow)) as string)), () => _ssrg_effect_flatMap(_ssrg_console_println(count(100000)), () => _ssrg_effect_flatMap(left(3), (value: number) => _ssrg_console_println(value))))))); })(); })(); })()
