import { stringAdd as _ssrg_string_add_dictionary } from "@seseragi/runtime/string"
import { Nothing as _ssrg_maybe_Nothing, Just as _ssrg_maybe_Just } from "@seseragi/runtime/sum"
import { flatMap as _ssrg_effect_flatMap } from "@seseragi/runtime/effect"
import { println as _ssrg_console_println } from "@seseragi/runtime/console"

const profile = (name: string) => (score: number) => ({ "name": name, "score": score } as const)
const displayName = (user: { readonly "name": string }) => (($ssrg_match: { readonly "name": string }): string => ((name: string): string => name)($ssrg_match["name"]))(user)
const renderLabeled = (user: { readonly "label": string; readonly "name": string }) => (($ssrg_match: { readonly "label": string; readonly "name": string }): string => $ssrg_match["label"] === "Player" ? ((name: string): string => _ssrg_string_add_dictionary["add"]("Player: ")(name))($ssrg_match["name"]) : ((label: string, name: string): string => _ssrg_string_add_dictionary["add"](_ssrg_string_add_dictionary["add"](label)(": "))(name))($ssrg_match["label"], $ssrg_match["name"]))(user)
const renderProfile = (user: { readonly "label"?: string; readonly "name": string }) => (($ssrg_match: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: string }): string => $ssrg_match.tag === "Nothing" ? _ssrg_string_add_dictionary["add"]("Record profile: ")(displayName(user)) : $ssrg_match.tag === "Just" ? ((label: string): string => _ssrg_string_add_dictionary["add"](_ssrg_string_add_dictionary["add"](label)(": "))(displayName(user)))($ssrg_match.value) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())((($ssrg_record) => Object.prototype.hasOwnProperty.call($ssrg_record, "label") ? _ssrg_maybe_Just($ssrg_record["label"]) : _ssrg_maybe_Nothing)(user))
export const main = (_unit: undefined) => (() => { const base: { readonly "name": string; readonly "score": number } = profile("Mio")(42); return _ssrg_effect_flatMap(_ssrg_console_println(renderProfile(base)), () => _ssrg_console_println(renderLabeled(({ ...base, "label": "Player" } as const)))); })()
