import { intEq as _ssrg_int_eq_dictionary } from "@seseragi/runtime/equality"
import { remainder as _ssrg_int_remainder, subtract as _ssrg_int_subtract } from "@seseragi/runtime/int"
import { intShow as _ssrg_show_intShow } from "@seseragi/runtime/show"
import { arrayReducible as _ssrg_array_reducible, collectMap as _ssrg_array_comprehend, find as _ssrg_array_find, take as _ssrg_array_take, drop as _ssrg_array_drop } from "@seseragi/runtime/array"
import { join as _ssrg_collection_join } from "@seseragi/runtime/collection"
import { collectMap as _ssrg_list_comprehend, find as _ssrg_list_find, fromArray as _ssrg_list_from_array, take as _ssrg_list_take, drop as _ssrg_list_drop, type List as List } from "@seseragi/runtime/list"

const even = (value: number) => _ssrg_int_eq_dictionary["eq"](_ssrg_int_remainder(value, 2))(0)
const negative = (value: number) => value < 0
const showMaybe = (value: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: number }) => (($ssrg_match: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: number }): string => $ssrg_match.tag === "Nothing" ? "none" : $ssrg_match.tag === "Just" ? ((item: number): string => _ssrg_show_intShow["show"](item))($ssrg_match.value) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(value)
const showArray = (values: ReadonlyArray<number>) => _ssrg_collection_join(_ssrg_array_reducible, ",", _ssrg_array_comprehend(values, (value) => true, (value) => _ssrg_show_intShow["show"](value)))
const showList = (values: List<number>) => _ssrg_collection_join(_ssrg_array_reducible, ",", _ssrg_list_comprehend(values, (value) => true, (value) => _ssrg_show_intShow["show"](value)))
export const collectionSliceResults = (unit: undefined) => [showMaybe(_ssrg_array_find(even, [1, 2, 4])), showMaybe(_ssrg_array_find(negative, [1, 2, 4])), showArray(_ssrg_array_take(_ssrg_int_subtract(0, 1), [1, 2, 3])), showArray(_ssrg_array_take(2, [1, 2, 3])), showArray(_ssrg_array_take(20, [1, 2, 3])), showArray(_ssrg_array_drop(_ssrg_int_subtract(0, 1), [1, 2, 3])), showArray(_ssrg_array_drop(2, [1, 2, 3])), showArray(_ssrg_array_drop(20, [1, 2, 3])), showMaybe(_ssrg_list_find(even, _ssrg_list_from_array([1, 2, 4]))), showMaybe(_ssrg_list_find(negative, _ssrg_list_from_array([1, 2, 4]))), showList(_ssrg_list_take(_ssrg_int_subtract(0, 1), _ssrg_list_from_array([1, 2, 3]))), showList(_ssrg_list_take(2, _ssrg_list_from_array([1, 2, 3]))), showList(_ssrg_list_take(20, _ssrg_list_from_array([1, 2, 3]))), showList(_ssrg_list_drop(_ssrg_int_subtract(0, 1), _ssrg_list_from_array([1, 2, 3]))), showList(_ssrg_list_drop(2, _ssrg_list_from_array([1, 2, 3]))), showList(_ssrg_list_drop(20, _ssrg_list_from_array([1, 2, 3])))]
