import { remainder as _ssrg_int64_remainder, subtract as _ssrg_int64_subtract } from "@seseragi/runtime/int64"
import { intShow as _ssrg_show_intShow } from "@seseragi/runtime/show"
import { arrayReducible as _ssrg_array_reducible, collectMap as _ssrg_array_comprehend, find as _ssrg_array_find, take as _ssrg_array_take, drop as _ssrg_array_drop } from "@seseragi/runtime/array"
import { join as _ssrg_collection_join } from "@seseragi/runtime/collection"
import { collectMap as _ssrg_list_comprehend, find as _ssrg_list_find, fromArray as _ssrg_list_from_array, take as _ssrg_list_take, drop as _ssrg_list_drop, type List as List } from "@seseragi/runtime/list"

const even = (value: bigint) => _ssrg_int64_remainder(value, 2n) === 0n
const negative = (value: bigint) => value < 0n
const showMaybe = (value: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: bigint }) => (($ssrg_match: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: bigint }): string => $ssrg_match.tag === "Nothing" ? "none" : $ssrg_match.tag === "Just" ? ((item: bigint): string => _ssrg_show_intShow["show"](item))($ssrg_match.value) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(value)
const showArray = (values: ReadonlyArray<bigint>) => _ssrg_collection_join(_ssrg_array_reducible, ",", _ssrg_array_comprehend(values, (value) => true, (value) => _ssrg_show_intShow["show"](value)))
const showList = (values: List<bigint>) => _ssrg_collection_join(_ssrg_array_reducible, ",", _ssrg_list_comprehend(values, (value) => true, (value) => _ssrg_show_intShow["show"](value)))
export const collectionSliceResults = (unit: undefined) => [showMaybe(_ssrg_array_find(even, [1n, 2n, 4n])), showMaybe(_ssrg_array_find(negative, [1n, 2n, 4n])), showArray(_ssrg_array_take(_ssrg_int64_subtract(0n, 1n), [1n, 2n, 3n])), showArray(_ssrg_array_take(2n, [1n, 2n, 3n])), showArray(_ssrg_array_take(20n, [1n, 2n, 3n])), showArray(_ssrg_array_drop(_ssrg_int64_subtract(0n, 1n), [1n, 2n, 3n])), showArray(_ssrg_array_drop(2n, [1n, 2n, 3n])), showArray(_ssrg_array_drop(20n, [1n, 2n, 3n])), showMaybe(_ssrg_list_find(even, _ssrg_list_from_array([1n, 2n, 4n]))), showMaybe(_ssrg_list_find(negative, _ssrg_list_from_array([1n, 2n, 4n]))), showList(_ssrg_list_take(_ssrg_int64_subtract(0n, 1n), _ssrg_list_from_array([1n, 2n, 3n]))), showList(_ssrg_list_take(2n, _ssrg_list_from_array([1n, 2n, 3n]))), showList(_ssrg_list_take(20n, _ssrg_list_from_array([1n, 2n, 3n]))), showList(_ssrg_list_drop(_ssrg_int64_subtract(0n, 1n), _ssrg_list_from_array([1n, 2n, 3n]))), showList(_ssrg_list_drop(2n, _ssrg_list_from_array([1n, 2n, 3n]))), showList(_ssrg_list_drop(20n, _ssrg_list_from_array([1n, 2n, 3n])))]
