import { fromArray as _ssrg_list_from_array, length as _ssrg_list_length, isEmpty as _ssrg_list_isEmpty, get as _ssrg_list_get, head as _ssrg_list_head, tail as _ssrg_list_tail, type List as List } from "@seseragi/runtime/list"
import { intShow as _ssrg_show_intShow } from "@seseragi/runtime/show"
import { length as _ssrg_array_length, isEmpty as _ssrg_array_isEmpty, get as _ssrg_array_get, head as _ssrg_array_head, tail as _ssrg_array_tail } from "@seseragi/runtime/array"
import { subtract as _ssrg_int_subtract } from "@seseragi/runtime/int"

const emptyArray = (unit: undefined) => [] as ReadonlyArray<number>
const emptyList = (unit: undefined) => _ssrg_list_from_array([] as ReadonlyArray<number>)
const number = (value: number) => _ssrg_show_intShow["show"](value)
const yesNo = (value: boolean) => value ? "true" : "false"
const showMaybeInt = (value: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: number }) => (($ssrg_match: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: number }): string => $ssrg_match.tag === "Nothing" ? "none" : $ssrg_match.tag === "Just" ? ((item: number): string => number(item))($ssrg_match.value) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(value)
const showMaybeArray = (value: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: ReadonlyArray<number> }) => (($ssrg_match: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: ReadonlyArray<number> }): string => $ssrg_match.tag === "Nothing" ? "none" : $ssrg_match.tag === "Just" ? ((items: ReadonlyArray<number>): string => number(_ssrg_array_length(items)))($ssrg_match.value) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(value)
const showMaybeList = (value: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: List<number> }) => (($ssrg_match: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: List<number> }): string => $ssrg_match.tag === "Nothing" ? "none" : $ssrg_match.tag === "Just" ? ((items: List<number>): string => number(_ssrg_list_length(items)))($ssrg_match.value) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(value)
export const collectionAccessResults = (unit: undefined) => [number(_ssrg_array_length([10, 20])), yesNo(_ssrg_array_isEmpty(emptyArray(undefined))), showMaybeInt(_ssrg_array_get(1, [10, 20])), showMaybeInt(_ssrg_array_get(_ssrg_int_subtract(0, 1), [10, 20])), showMaybeInt(_ssrg_array_get(2, [10, 20])), showMaybeInt(_ssrg_array_head([10, 20])), showMaybeInt(_ssrg_array_head(emptyArray(undefined))), showMaybeArray(_ssrg_array_tail([10])), showMaybeArray(_ssrg_array_tail(emptyArray(undefined))), number(_ssrg_list_length(_ssrg_list_from_array([10, 20]))), yesNo(_ssrg_list_isEmpty(emptyList(undefined))), showMaybeInt(_ssrg_list_get(1, _ssrg_list_from_array([10, 20]))), showMaybeInt(_ssrg_list_get(_ssrg_int_subtract(0, 1), _ssrg_list_from_array([10, 20]))), showMaybeInt(_ssrg_list_get(2, _ssrg_list_from_array([10, 20]))), showMaybeInt(_ssrg_list_head(_ssrg_list_from_array([10, 20]))), showMaybeInt(_ssrg_list_head(emptyList(undefined))), showMaybeList(_ssrg_list_tail(_ssrg_list_from_array([10]))), showMaybeList(_ssrg_list_tail(emptyList(undefined)))]
