import { fromArray as _ssrg_list_from_array, length as _ssrg_list_length, isEmpty as _ssrg_list_isEmpty, get as _ssrg_list_get, head as _ssrg_list_head, tail as _ssrg_list_tail, type List as List } from "@seseragi/runtime/list"
import { intShow as _ssrg_show_intShow } from "@seseragi/runtime/show"
import { length as _ssrg_array_length, isEmpty as _ssrg_array_isEmpty, get as _ssrg_array_get, head as _ssrg_array_head, tail as _ssrg_array_tail } from "@seseragi/runtime/array"
import { subtract as _ssrg_int64_subtract } from "@seseragi/runtime/int64"

const emptyArray = (unit: undefined) => [] as ReadonlyArray<bigint>
const emptyList = (unit: undefined) => _ssrg_list_from_array([] as ReadonlyArray<bigint>)
const number = (value: bigint) => _ssrg_show_intShow["show"](value)
const yesNo = (value: boolean) => value ? "true" : "false"
const showMaybeInt = (value: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: bigint }) => (($ssrg_match: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: bigint }): string => $ssrg_match.tag === "Nothing" ? "none" : $ssrg_match.tag === "Just" ? ((item: bigint): string => number(item))($ssrg_match.value) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(value)
const showMaybeArray = (value: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: ReadonlyArray<bigint> }) => (($ssrg_match: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: ReadonlyArray<bigint> }): string => $ssrg_match.tag === "Nothing" ? "none" : $ssrg_match.tag === "Just" ? ((items: ReadonlyArray<bigint>): string => number(_ssrg_array_length(items)))($ssrg_match.value) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(value)
const showMaybeList = (value: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: List<bigint> }) => (($ssrg_match: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: List<bigint> }): string => $ssrg_match.tag === "Nothing" ? "none" : $ssrg_match.tag === "Just" ? ((items: List<bigint>): string => number(_ssrg_list_length(items)))($ssrg_match.value) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(value)
export const collectionAccessResults = (unit: undefined) => [number(_ssrg_array_length([10n, 20n])), yesNo(_ssrg_array_isEmpty(emptyArray(undefined))), showMaybeInt(_ssrg_array_get(1n, [10n, 20n])), showMaybeInt(_ssrg_array_get(_ssrg_int64_subtract(0n, 1n), [10n, 20n])), showMaybeInt(_ssrg_array_get(2n, [10n, 20n])), showMaybeInt(_ssrg_array_head([10n, 20n])), showMaybeInt(_ssrg_array_head(emptyArray(undefined))), showMaybeArray(_ssrg_array_tail([10n])), showMaybeArray(_ssrg_array_tail(emptyArray(undefined))), number(_ssrg_list_length(_ssrg_list_from_array([10n, 20n]))), yesNo(_ssrg_list_isEmpty(emptyList(undefined))), showMaybeInt(_ssrg_list_get(1n, _ssrg_list_from_array([10n, 20n]))), showMaybeInt(_ssrg_list_get(_ssrg_int64_subtract(0n, 1n), _ssrg_list_from_array([10n, 20n]))), showMaybeInt(_ssrg_list_get(2n, _ssrg_list_from_array([10n, 20n]))), showMaybeInt(_ssrg_list_head(_ssrg_list_from_array([10n, 20n]))), showMaybeInt(_ssrg_list_head(emptyList(undefined))), showMaybeList(_ssrg_list_tail(_ssrg_list_from_array([10n]))), showMaybeList(_ssrg_list_tail(emptyList(undefined)))]
