import { assertUnicodeVersion as $ssrg$assertUnicodeVersion } from "@seseragi/runtime/unicode-version"
import { format as _ssrg_int_format, parse as _ssrg_int_parse, checkedAdd as _ssrg_int_checkedAdd, maxValue as _ssrg_int_maxValue, saturatingSubtract as _ssrg_int_saturatingSubtract, minValue as _ssrg_int_minValue, formatRadix as _ssrg_int_formatRadix, type IntParseError as IntParseError } from "@seseragi/runtime/int"
import { format as _ssrg_float_format, fromInt as _ssrg_float_fromInt, toInt as _ssrg_float_toInt, totalCompare as _ssrg_float_totalCompare, type FloatConversionError as FloatConversionError } from "@seseragi/runtime/float"
import { HalfEven as _ssrg_number_HalfEven, type RoundingMode as RoundingMode } from "@seseragi/runtime/number"
$ssrg$assertUnicodeVersion("17.0.0")

const renderParsed = (value: { readonly tag: "Left"; readonly value: IntParseError } | { readonly tag: "Right"; readonly value: number }) => (($ssrg_match: { readonly tag: "Left"; readonly value: IntParseError } | { readonly tag: "Right"; readonly value: number }): string => $ssrg_match.tag === "Left" ? "parse error" : $ssrg_match.tag === "Right" ? ((parsed: number): string => _ssrg_int_format(parsed))($ssrg_match.value) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(value)
const renderMaybe = (value: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: number }) => (($ssrg_match: { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: number }): string => $ssrg_match.tag === "Nothing" ? "Nothing" : $ssrg_match.tag === "Just" ? ((integer: number): string => _ssrg_int_format(integer))($ssrg_match.value) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(value)
const renderFormatted = (value: { readonly tag: "Left"; readonly value: IntParseError } | { readonly tag: "Right"; readonly value: string }) => (($ssrg_match: { readonly tag: "Left"; readonly value: IntParseError } | { readonly tag: "Right"; readonly value: string }): string => $ssrg_match.tag === "Left" ? "radix error" : $ssrg_match.tag === "Right" ? ((text: string): string => text)($ssrg_match.value) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(value)
const renderConverted = (value: { readonly tag: "Left"; readonly value: FloatConversionError } | { readonly tag: "Right"; readonly value: number }) => (($ssrg_match: { readonly tag: "Left"; readonly value: FloatConversionError } | { readonly tag: "Right"; readonly value: number }): string => $ssrg_match.tag === "Left" ? "conversion error" : $ssrg_match.tag === "Right" ? ((integer: number): string => _ssrg_int_format(integer))($ssrg_match.value) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(value)
const renderOrdering = (value: { readonly tag: "Less" } | { readonly tag: "Equal" } | { readonly tag: "Greater" }) => (($ssrg_match: { readonly tag: "Less" } | { readonly tag: "Equal" } | { readonly tag: "Greater" }): string => $ssrg_match.tag === "Less" ? "Less" : $ssrg_match.tag === "Equal" ? "Equal" : "Greater")(value)
export const numericSafeApi = (unit: undefined) => [renderParsed(_ssrg_int_parse("9007199254740991")), renderMaybe(_ssrg_int_checkedAdd(1, _ssrg_int_maxValue(undefined))), _ssrg_int_saturatingSubtract(1, _ssrg_int_minValue(undefined)), renderFormatted(_ssrg_int_formatRadix(16, 255)), _ssrg_float_format(_ssrg_float_fromInt(42)), renderConverted(_ssrg_float_toInt(_ssrg_number_HalfEven, 2.5)), renderOrdering(_ssrg_float_totalCompare(-(0.0), 0.0))] as const
