import { assertUnicodeVersion as $ssrg$assertUnicodeVersion } from "@seseragi/runtime/unicode-version"
import { intEq as _ssrg_int_eq_dictionary, intOrd as _ssrg_int_ord_dictionary, tupleEq as _ssrg_tuple_eq_dictionary, tupleOrd as _ssrg_tuple_ord_dictionary, stringEq as _ssrg_string_eq_dictionary, eitherEq as _ssrg_either_eq_dictionary, maybeEq as _ssrg_maybe_eq_dictionary, listEq as _ssrg_list_eq_dictionary, arrayEq as _ssrg_array_eq_dictionary } from "@seseragi/runtime/equality"
import { intHash as _ssrg_int_hash_dictionary, tupleHash as _ssrg_tuple_hash_dictionary } from "@seseragi/runtime/hash"
import { type List as List } from "@seseragi/runtime/list"
$ssrg$assertUnicodeVersion("17.0.0")

export type UserId =
  | { readonly tag: "UserId"; readonly value: number };
export const UserId = (value: number): UserId => ({ tag: "UserId", value } as const);
export type Tree<A> =
  | { readonly tag: "Leaf"; readonly value: A }
  | { readonly tag: "Branch"; readonly value: readonly [Tree<A>, Tree<A>] };
export const Leaf = <A>(value: A): Tree<A> => ({ tag: "Leaf", value } as const);
export const Branch = <A>(value: readonly [Tree<A>, Tree<A>]): Tree<A> => ({ tag: "Branch", value } as const);
export type Phase =
  | { readonly tag: "Zebra"; readonly value: number }
  | { readonly tag: "Alpha"; readonly value: number }
  | { readonly tag: "Empty" };
export const Zebra = (value: number): Phase => ({ tag: "Zebra", value } as const);
export const Alpha = (value: number): Phase => ({ tag: "Alpha", value } as const);
export const Empty: Phase = { tag: "Empty" } as const;
export type Phantom<A> =
  | { readonly tag: "Phantom" };
export const Phantom = { tag: "Phantom" } as const;
declare const __ssrg$brand$Profile: unique symbol;
export type Profile<A> = {
  readonly "id": UserId;
  readonly "value": A;
  readonly [__ssrg$brand$Profile]: true;
};
declare const __ssrg$brand$Nested: unique symbol;
export type Nested<A> = {
  readonly "values": ReadonlyArray<List<{ readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: { readonly tag: "Left"; readonly value: string } | { readonly tag: "Right"; readonly value: A } }>>;
  readonly [__ssrg$brand$Nested]: true;
};
declare const __ssrg$brand$Reordered: unique symbol;
export type Reordered = {
  readonly "z": number;
  readonly "a": number;
  readonly [__ssrg$brand$Reordered]: true;
};
export const __ssrg$instance$Eq$0: { eq: (left: UserId) => (right: UserId) => boolean } = { eq: (left: UserId) => (right: UserId): boolean => { if (left.tag !== right.tag) return false; switch (left.tag) { case "UserId": { if (right.tag !== "UserId") throw new Error("invalid derived comparison"); return _ssrg_int_eq_dictionary.eq(left.value)(right.value); } } throw new Error("invalid derived value"); } };
export const __ssrg$instance$Ord$1 = (__ssrg$input$0: Readonly<Record<string, (...args: any[]) => any>>): { eq: (left: UserId) => (right: UserId) => boolean; compare: (left: UserId) => (right: UserId) => { readonly tag: "Less" | "Equal" | "Greater" } } => { const __ssrg$evidence$0 = __ssrg$input$0 as { eq: (left: UserId) => (right: UserId) => boolean }; return { ...__ssrg$evidence$0, compare: (left: UserId) => (right: UserId): { readonly tag: "Less" | "Equal" | "Greater" } => { switch (left.tag) { case "UserId": { if (right.tag !== "UserId") throw new Error("invalid derived comparison"); const order0 = _ssrg_int_ord_dictionary.compare(left.value)(right.value); if (order0.tag !== "Equal") return order0; return { tag: "Equal" }; } } throw new Error("invalid derived value"); } }; };
export const __ssrg$instance$Hash$2 = (__ssrg$input$0: Readonly<Record<string, (...args: any[]) => any>>): { hash: (value: UserId) => number } => { const __ssrg$evidence$0 = __ssrg$input$0 as { eq: (left: UserId) => (right: UserId) => boolean }; return { hash: (left: UserId): number => { switch (left.tag) { case "UserId": { return _ssrg_int_hash_dictionary.hash(left.value); } } throw new Error("invalid derived value"); } }; };
export const __ssrg$instance$Eq$3 = <A,>(__ssrg$input$0: Readonly<Record<string, (...args: any[]) => any>>): { eq: (left: Profile<A>) => (right: Profile<A>) => boolean } => { const __ssrg$evidence$0 = __ssrg$input$0 as { eq: (left: A) => (right: A) => boolean }; return { eq: (left: Profile<A>) => (right: Profile<A>): boolean => { return __ssrg$instance$Eq$0.eq(left["id"])(right["id"]) && (__ssrg$evidence$0).eq(left["value"])(right["value"]); } }; };
export const __ssrg$instance$Ord$4 = <A,>(__ssrg$input$0: Readonly<Record<string, (...args: any[]) => any>>, __ssrg$input$1: Readonly<Record<string, (...args: any[]) => any>>): { eq: (left: Profile<A>) => (right: Profile<A>) => boolean; compare: (left: Profile<A>) => (right: Profile<A>) => { readonly tag: "Less" | "Equal" | "Greater" } } => { const __ssrg$evidence$0 = __ssrg$input$0 as { eq: (left: Profile<A>) => (right: Profile<A>) => boolean }; const __ssrg$evidence$1 = __ssrg$input$1 as { eq: (left: A) => (right: A) => boolean; compare: (left: A) => (right: A) => { readonly tag: "Less" | "Equal" | "Greater" } }; return { ...__ssrg$evidence$0, compare: (left: Profile<A>) => (right: Profile<A>): { readonly tag: "Less" | "Equal" | "Greater" } => { const order0 = (__ssrg$instance$Ord$1(__ssrg$instance$Eq$0)).compare(left["id"])(right["id"]); if (order0.tag !== "Equal") return order0; const order1 = (__ssrg$evidence$1).compare(left["value"])(right["value"]); if (order1.tag !== "Equal") return order1; return { tag: "Equal" }; } }; };
export const __ssrg$instance$Hash$5 = <A,>(__ssrg$input$0: Readonly<Record<string, (...args: any[]) => any>>, __ssrg$input$1: Readonly<Record<string, (...args: any[]) => any>>): { hash: (value: Profile<A>) => number } => { const __ssrg$evidence$0 = __ssrg$input$0 as { eq: (left: Profile<A>) => (right: Profile<A>) => boolean }; const __ssrg$evidence$1 = __ssrg$input$1 as { hash: (value: A) => number }; return { hash: (left: Profile<A>): number => { let state = 0; state = Math.imul(state ^ ((__ssrg$instance$Hash$2(__ssrg$instance$Eq$0)).hash(left["id"])), 16777619); state = Math.imul(state ^ ((__ssrg$evidence$1).hash(left["value"])), 16777619); return state | 0; } }; };
export const __ssrg$instance$Eq$6 = <A,>(__ssrg$input$0: Readonly<Record<string, (...args: any[]) => any>>): { eq: (left: Tree<A>) => (right: Tree<A>) => boolean } => { const __ssrg$evidence$0 = __ssrg$input$0 as { eq: (left: A) => (right: A) => boolean }; return { eq: (left: Tree<A>) => (right: Tree<A>): boolean => { if (left.tag !== right.tag) return false; switch (left.tag) { case "Leaf": { if (right.tag !== "Leaf") throw new Error("invalid derived comparison"); return (__ssrg$evidence$0).eq(left.value)(right.value); } case "Branch": { if (right.tag !== "Branch") throw new Error("invalid derived comparison"); return (_ssrg_tuple_eq_dictionary<readonly [Tree<A>, Tree<A>]>(__ssrg$instance$Eq$6<A>(__ssrg$evidence$0), __ssrg$instance$Eq$6<A>(__ssrg$evidence$0))).eq(left.value)(right.value); } } throw new Error("invalid derived value"); } }; };
export const __ssrg$instance$Ord$7 = <A,>(__ssrg$input$0: Readonly<Record<string, (...args: any[]) => any>>, __ssrg$input$1: Readonly<Record<string, (...args: any[]) => any>>): { eq: (left: Tree<A>) => (right: Tree<A>) => boolean; compare: (left: Tree<A>) => (right: Tree<A>) => { readonly tag: "Less" | "Equal" | "Greater" } } => { const __ssrg$evidence$0 = __ssrg$input$0 as { eq: (left: Tree<A>) => (right: Tree<A>) => boolean }; const __ssrg$evidence$1 = __ssrg$input$1 as { eq: (left: A) => (right: A) => boolean; compare: (left: A) => (right: A) => { readonly tag: "Less" | "Equal" | "Greater" } }; return { ...__ssrg$evidence$0, compare: (left: Tree<A>) => (right: Tree<A>): { readonly tag: "Less" | "Equal" | "Greater" } => { if (left.tag !== right.tag) return { tag: ["Leaf", "Branch"].indexOf(left.tag) < ["Leaf", "Branch"].indexOf(right.tag) ? "Less" : "Greater" }; switch (left.tag) { case "Leaf": { if (right.tag !== "Leaf") throw new Error("invalid derived comparison"); const order0 = (__ssrg$evidence$1).compare(left.value)(right.value); if (order0.tag !== "Equal") return order0; return { tag: "Equal" }; } case "Branch": { if (right.tag !== "Branch") throw new Error("invalid derived comparison"); const order0 = (_ssrg_tuple_ord_dictionary<readonly [Tree<A>, Tree<A>]>(__ssrg$instance$Ord$7<A>(__ssrg$evidence$0, __ssrg$evidence$1), __ssrg$instance$Ord$7<A>(__ssrg$evidence$0, __ssrg$evidence$1))).compare(left.value)(right.value); if (order0.tag !== "Equal") return order0; return { tag: "Equal" }; } } throw new Error("invalid derived value"); } }; };
export const __ssrg$instance$Hash$8 = <A,>(__ssrg$input$0: Readonly<Record<string, (...args: any[]) => any>>, __ssrg$input$1: Readonly<Record<string, (...args: any[]) => any>>): { hash: (value: Tree<A>) => number } => { const __ssrg$evidence$0 = __ssrg$input$0 as { eq: (left: Tree<A>) => (right: Tree<A>) => boolean }; const __ssrg$evidence$1 = __ssrg$input$1 as { hash: (value: A) => number }; return { hash: (left: Tree<A>): number => { switch (left.tag) { case "Leaf": { let state = 0; state = Math.imul(state ^ ((__ssrg$evidence$1).hash(left.value)), 16777619); return state | 0; } case "Branch": { let state = 1; state = Math.imul(state ^ ((_ssrg_tuple_hash_dictionary<readonly [Tree<A>, Tree<A>]>(__ssrg$instance$Hash$8<A>(__ssrg$evidence$0, __ssrg$evidence$1), __ssrg$instance$Hash$8<A>(__ssrg$evidence$0, __ssrg$evidence$1))).hash(left.value)), 16777619); return state | 0; } } throw new Error("invalid derived value"); } }; };
export const __ssrg$instance$Eq$9: { eq: (left: Phase) => (right: Phase) => boolean } = { eq: (left: Phase) => (right: Phase): boolean => { if (left.tag !== right.tag) return false; switch (left.tag) { case "Zebra": { if (right.tag !== "Zebra") throw new Error("invalid derived comparison"); return _ssrg_int_eq_dictionary.eq(left.value)(right.value); } case "Alpha": { if (right.tag !== "Alpha") throw new Error("invalid derived comparison"); return _ssrg_int_eq_dictionary.eq(left.value)(right.value); } case "Empty": { if (right.tag !== "Empty") throw new Error("invalid derived comparison"); return true; } } throw new Error("invalid derived value"); } };
export const __ssrg$instance$Ord$10 = (__ssrg$input$0: Readonly<Record<string, (...args: any[]) => any>>): { eq: (left: Phase) => (right: Phase) => boolean; compare: (left: Phase) => (right: Phase) => { readonly tag: "Less" | "Equal" | "Greater" } } => { const __ssrg$evidence$0 = __ssrg$input$0 as { eq: (left: Phase) => (right: Phase) => boolean }; return { ...__ssrg$evidence$0, compare: (left: Phase) => (right: Phase): { readonly tag: "Less" | "Equal" | "Greater" } => { if (left.tag !== right.tag) return { tag: ["Zebra", "Alpha", "Empty"].indexOf(left.tag) < ["Zebra", "Alpha", "Empty"].indexOf(right.tag) ? "Less" : "Greater" }; switch (left.tag) { case "Zebra": { if (right.tag !== "Zebra") throw new Error("invalid derived comparison"); const order0 = _ssrg_int_ord_dictionary.compare(left.value)(right.value); if (order0.tag !== "Equal") return order0; return { tag: "Equal" }; } case "Alpha": { if (right.tag !== "Alpha") throw new Error("invalid derived comparison"); const order0 = _ssrg_int_ord_dictionary.compare(left.value)(right.value); if (order0.tag !== "Equal") return order0; return { tag: "Equal" }; } case "Empty": { if (right.tag !== "Empty") throw new Error("invalid derived comparison");  return { tag: "Equal" }; } } throw new Error("invalid derived value"); } }; };
export const __ssrg$instance$Hash$11 = (__ssrg$input$0: Readonly<Record<string, (...args: any[]) => any>>): { hash: (value: Phase) => number } => { const __ssrg$evidence$0 = __ssrg$input$0 as { eq: (left: Phase) => (right: Phase) => boolean }; return { hash: (left: Phase): number => { switch (left.tag) { case "Zebra": { let state = 0; state = Math.imul(state ^ (_ssrg_int_hash_dictionary.hash(left.value)), 16777619); return state | 0; } case "Alpha": { let state = 1; state = Math.imul(state ^ (_ssrg_int_hash_dictionary.hash(left.value)), 16777619); return state | 0; } case "Empty": { let state = 2;  return state | 0; } } throw new Error("invalid derived value"); } }; };
export const __ssrg$instance$Eq$12 = <A,>(__ssrg$input$0: Readonly<Record<string, (...args: any[]) => any>>): { eq: (left: Nested<A>) => (right: Nested<A>) => boolean } => { const __ssrg$evidence$0 = __ssrg$input$0 as { eq: (left: A) => (right: A) => boolean }; return { eq: (left: Nested<A>) => (right: Nested<A>): boolean => { return (_ssrg_array_eq_dictionary<List<{ readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: { readonly tag: "Left"; readonly value: string } | { readonly tag: "Right"; readonly value: A } }>>(_ssrg_list_eq_dictionary<{ readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: { readonly tag: "Left"; readonly value: string } | { readonly tag: "Right"; readonly value: A } }>(_ssrg_maybe_eq_dictionary<{ readonly tag: "Left"; readonly value: string } | { readonly tag: "Right"; readonly value: A }>(_ssrg_either_eq_dictionary<string, A>(_ssrg_string_eq_dictionary, __ssrg$evidence$0))))).eq(left["values"])(right["values"]); } }; };
export const __ssrg$instance$Eq$13: { eq: (left: Reordered) => (right: Reordered) => boolean } = { eq: (left: Reordered) => (right: Reordered): boolean => { return _ssrg_int_eq_dictionary.eq(left["z"])(right["z"]) && _ssrg_int_eq_dictionary.eq(left["a"])(right["a"]); } };
export const __ssrg$instance$Ord$14 = (__ssrg$input$0: Readonly<Record<string, (...args: any[]) => any>>): { eq: (left: Reordered) => (right: Reordered) => boolean; compare: (left: Reordered) => (right: Reordered) => { readonly tag: "Less" | "Equal" | "Greater" } } => { const __ssrg$evidence$0 = __ssrg$input$0 as { eq: (left: Reordered) => (right: Reordered) => boolean }; return { ...__ssrg$evidence$0, compare: (left: Reordered) => (right: Reordered): { readonly tag: "Less" | "Equal" | "Greater" } => { const order0 = _ssrg_int_ord_dictionary.compare(left["z"])(right["z"]); if (order0.tag !== "Equal") return order0; const order1 = _ssrg_int_ord_dictionary.compare(left["a"])(right["a"]); if (order1.tag !== "Equal") return order1; return { tag: "Equal" }; } }; };
export const __ssrg$instance$Hash$15 = (__ssrg$input$0: Readonly<Record<string, (...args: any[]) => any>>): { hash: (value: Reordered) => number } => { const __ssrg$evidence$0 = __ssrg$input$0 as { eq: (left: Reordered) => (right: Reordered) => boolean }; return { hash: (left: Reordered): number => { let state = 0; state = Math.imul(state ^ (_ssrg_int_hash_dictionary.hash(left["z"])), 16777619); state = Math.imul(state ^ (_ssrg_int_hash_dictionary.hash(left["a"])), 16777619); return state | 0; } }; };
export const __ssrg$instance$Eq$16 = <A,>(): { eq: (left: Phantom<A>) => (right: Phantom<A>) => boolean } => {  return { eq: (left: Phantom<A>) => (right: Phantom<A>): boolean => { if (left.tag !== right.tag) return false; switch (left.tag) { case "Phantom": { if (right.tag !== "Phantom") throw new Error("invalid derived comparison"); return true; } } throw new Error("invalid derived value"); } }; };
export const __ssrg$instance$Ord$17 = <A,>(__ssrg$input$0: Readonly<Record<string, (...args: any[]) => any>>): { eq: (left: Phantom<A>) => (right: Phantom<A>) => boolean; compare: (left: Phantom<A>) => (right: Phantom<A>) => { readonly tag: "Less" | "Equal" | "Greater" } } => { const __ssrg$evidence$0 = __ssrg$input$0 as { eq: (left: Phantom<A>) => (right: Phantom<A>) => boolean }; return { ...__ssrg$evidence$0, compare: (left: Phantom<A>) => (right: Phantom<A>): { readonly tag: "Less" | "Equal" | "Greater" } => { if (left.tag !== right.tag) return { tag: ["Phantom"].indexOf(left.tag) < ["Phantom"].indexOf(right.tag) ? "Less" : "Greater" }; switch (left.tag) { case "Phantom": { if (right.tag !== "Phantom") throw new Error("invalid derived comparison");  return { tag: "Equal" }; } } throw new Error("invalid derived value"); } }; };
export const __ssrg$instance$Hash$18 = <A,>(__ssrg$input$0: Readonly<Record<string, (...args: any[]) => any>>): { hash: (value: Phantom<A>) => number } => { const __ssrg$evidence$0 = __ssrg$input$0 as { eq: (left: Phantom<A>) => (right: Phantom<A>) => boolean }; return { hash: (left: Phantom<A>): number => { switch (left.tag) { case "Phantom": { let state = 0;  return state | 0; } } throw new Error("invalid derived value"); } }; };
