import { assertUnicodeVersion as $ssrg$assertUnicodeVersion } from "@seseragi/runtime/unicode-version"
import { println as _ssrg_console_println, type Console as Console, type ConsoleError as ConsoleError } from "@seseragi/runtime/console"
import { effectApplicative as _ssrg_effect_applicative, flatMap as _ssrg_effect_flatMap, type Effect as Effect } from "@seseragi/runtime/effect"
import { intEq as _ssrg_int_eq_dictionary } from "@seseragi/runtime/equality"
import { subtract as _ssrg_int_subtract } from "@seseragi/runtime/int"
import { boolShow as _ssrg_show_boolShow, intShow as _ssrg_show_intShow, tupleShow as _ssrg_show_tupleShow } from "@seseragi/runtime/show"
$ssrg$assertUnicodeVersion("17.0.0")

const silent = (_unit: undefined) => (() => { const ignored = (_unit: undefined) => _ssrg_console_println("must stay cold"); return undefined; })()
export const main = (_unit: undefined) => (() => { const outer: number = 7; return (() => { const unused = (_unit: undefined) => _ssrg_console_println("must stay cold"); return (() => { const captured = (_unit: undefined) => ((_ssrg_effect_applicative["pure"](outer)) as Effect<{  }, never, number>); return (() => { const identity = <A,>(value: A) => ((_ssrg_effect_applicative["pure"](value)) as Effect<{  }, never, A>); return (() => { const render = <A,>(value: A) => (__ssrg$evidence$0: Readonly<Record<string, (...args: any[]) => any>>) => ((_ssrg_effect_applicative["pure"](((__ssrg$evidence$0["show"](value)) as string))) as Effect<{  }, never, string>); return (() => { const count = (n: number) => { const $ssrg$tail = Symbol(); while (true) { const $ssrg$result = _ssrg_int_eq_dictionary["eq"](n)(0) ? ((_ssrg_effect_applicative["pure"](1)) as Effect<{  }, never, number>) : ({ [$ssrg$tail]: [_ssrg_int_subtract(n, 1)] } as never); const $ssrg$tailResult: unknown = $ssrg$result; if (typeof $ssrg$tailResult === "object" && $ssrg$tailResult !== null && $ssrg$tail in $ssrg$tailResult) { const $ssrg$arguments = ($ssrg$tailResult as { readonly [$ssrg$tail]: readonly [number] })[$ssrg$tail]; n = $ssrg$arguments[0]; continue; } return $ssrg$result; } }; return (() => { const log = (value: number) => _ssrg_console_println(value); return (() => { const fromPure: Effect<{  }, never, number> = (() => { const step = (_unit: undefined) => 1; return (() => { const step = (_unit: undefined) => ((_ssrg_effect_applicative["pure"](2)) as Effect<{  }, never, number>); return step(undefined); })(); })(); return (() => { const fromEffect: number = (() => { const step = (_unit: undefined) => ((_ssrg_effect_applicative["pure"](1)) as Effect<{  }, never, number>); return (() => { const step = (_unit: undefined) => 3; return step(undefined); })(); })(); return _ssrg_effect_flatMap(captured(undefined), (value: number) => _ssrg_effect_flatMap(log(value), () => _ssrg_effect_flatMap(identity(true), (first: boolean) => _ssrg_effect_flatMap(identity(9), (second: number) => _ssrg_effect_flatMap(_ssrg_console_println(((_ssrg_show_tupleShow<readonly [boolean, number]>(_ssrg_show_boolShow, _ssrg_show_intShow)["show"]([first, second] as const)) as string)), () => _ssrg_effect_flatMap(count(3), (result: number) => _ssrg_effect_flatMap(_ssrg_console_println(result), () => _ssrg_effect_flatMap(((render(42)(_ssrg_show_intShow)) as Effect<{  }, never, string>), (rendered: string) => _ssrg_effect_flatMap(_ssrg_console_println(rendered), () => _ssrg_effect_flatMap(fromPure, (shadowed: number) => _ssrg_console_println(((_ssrg_show_tupleShow<readonly [number, number]>(_ssrg_show_intShow, _ssrg_show_intShow)["show"]([shadowed, fromEffect] as const)) as string)))))))))))); })(); })(); })(); })(); })(); })(); })(); })(); })()
const quiet: undefined = silent(undefined);
