import { type Box, Boxed, Profile, bind, __ssrg$instance$Applicative$1, __ssrg$instance$Functor$0, __ssrg$instance$Monad$2 } from "./domain.js"
import { assertUnicodeVersion as $ssrg$assertUnicodeVersion } from "@seseragi/runtime/unicode-version"
import { add as _ssrg_int_add } from "@seseragi/runtime/int"
import { stringShow as _ssrg_show_stringShow, intShow as _ssrg_show_intShow } from "@seseragi/runtime/show"
import { flatMap as _ssrg_effect_flatMap, succeed as _ssrg_effect_succeed } from "@seseragi/runtime/effect"
import { println as _ssrg_console_println } from "@seseragi/runtime/console"
$ssrg$assertUnicodeVersion("17.0.0")

const incrementBox = (value: number) => Boxed(_ssrg_int_add(value, 1))
const render = (value: Box<number>) => (($ssrg_match: Box<number>): string => $ssrg_match.tag === "Boxed" && $ssrg_match.value === 42 ? "Imported Box Monad: 42" : "Imported Box Monad: another value")(value)
const addBox = (left: Box<number>) => (right: Box<number>) => __ssrg$instance$Monad$2(__ssrg$instance$Applicative$1(__ssrg$instance$Functor$0))["flatMap"]((first: number) => __ssrg$instance$Monad$2(__ssrg$instance$Applicative$1(__ssrg$instance$Functor$0))["flatMap"]((second: number) => Boxed(_ssrg_int_add(first, second)))(right))(left)
const incrementProfileBox = (value: Box<Profile>) => __ssrg$instance$Monad$2(__ssrg$instance$Applicative$1(__ssrg$instance$Functor$0))["flatMap"]((__ssrg$pattern$481: Profile) => (() => { const profileName: string = (($ssrg_match: Profile): string => $ssrg_match.tag === "Profile" ? ((profileName: string, profileAge: number): string => profileName)($ssrg_match.value[0], $ssrg_match.value[1]) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(__ssrg$pattern$481); return (() => { const profileAge: number = (($ssrg_match: Profile): number => $ssrg_match.tag === "Profile" ? ((profileName: string, profileAge: number): number => profileAge)($ssrg_match.value[0], $ssrg_match.value[1]) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(__ssrg$pattern$481); return (() => { const __ssrg$pattern$528: Profile = Profile([profileName, profileAge] as const); return (() => { const typedName: string = (($ssrg_match: Profile): string => $ssrg_match.tag === "Profile" ? ((typedName: string, typedAge: number): string => typedName)($ssrg_match.value[0], $ssrg_match.value[1]) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(__ssrg$pattern$528); return (() => { const typedAge: number = (($ssrg_match: Profile): number => $ssrg_match.tag === "Profile" ? ((typedName: string, typedAge: number): number => typedAge)($ssrg_match.value[0], $ssrg_match.value[1]) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(__ssrg$pattern$528); return Boxed(Profile([typedName, _ssrg_int_add(typedAge, 1)] as const)); })(); })(); })(); })(); })())(value)
const renderProfileBox = (value: Box<Profile>) => (($ssrg_match: Box<Profile>): string => $ssrg_match.tag === "Boxed" && $ssrg_match.value.tag === "Profile" ? ((profileName: string, profileAge: number): string => "Imported Box Pattern: " + _ssrg_show_stringShow["show"](profileName) + ": " + _ssrg_show_intShow["show"](profileAge))($ssrg_match.value.value[0], $ssrg_match.value.value[1]) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(value)
export const main = (_unit: undefined) => (() => { const __ssrg$pattern$878: Box<Profile> = Boxed(Profile(["Aki", 40] as const)); return (() => { const localName: string = (($ssrg_match: Box<Profile>): string => $ssrg_match.tag === "Boxed" && $ssrg_match.value.tag === "Profile" ? ((localName: string, localAge: number): string => localName)($ssrg_match.value.value[0], $ssrg_match.value.value[1]) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(__ssrg$pattern$878); return (() => { const localAge: number = (($ssrg_match: Box<Profile>): number => $ssrg_match.tag === "Boxed" && $ssrg_match.value.tag === "Profile" ? ((localName: string, localAge: number): number => localAge)($ssrg_match.value.value[0], $ssrg_match.value.value[1]) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(__ssrg$pattern$878); return _ssrg_effect_flatMap(_ssrg_console_println("Imported Box Let: " + _ssrg_show_stringShow["show"](localName) + ": " + _ssrg_show_intShow["show"](localAge)), () => _ssrg_effect_flatMap(_ssrg_effect_succeed(Boxed(Profile(["Ren", 41] as const))), (__ssrg$pattern$1035: Box<Profile>) => (() => { const boundName: string = (($ssrg_match: Box<Profile>): string => $ssrg_match.tag === "Boxed" && $ssrg_match.value.tag === "Profile" ? ((boundName: string, boundAge: number): string => boundName)($ssrg_match.value.value[0], $ssrg_match.value.value[1]) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(__ssrg$pattern$1035); return (() => { const boundAge: number = (($ssrg_match: Box<Profile>): number => $ssrg_match.tag === "Boxed" && $ssrg_match.value.tag === "Profile" ? ((boundName: string, boundAge: number): number => boundAge)($ssrg_match.value.value[0], $ssrg_match.value.value[1]) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(__ssrg$pattern$1035); return _ssrg_effect_flatMap(_ssrg_console_println("Imported Box Bind: " + _ssrg_show_stringShow["show"](boundName) + ": " + _ssrg_show_intShow["show"](boundAge)), () => _ssrg_effect_flatMap(_ssrg_console_println(render(((bind(incrementBox)(Boxed(41))(__ssrg$instance$Monad$2(__ssrg$instance$Applicative$1(__ssrg$instance$Functor$0)))) as Box<number>))), () => _ssrg_effect_flatMap(_ssrg_console_println(render(addBox(Boxed(20))(Boxed(22)))), () => _ssrg_console_println(renderProfileBox(incrementProfileBox(Boxed(Profile(["Mio", 41] as const)))))))); })(); })())); })(); })(); })()
