[package]
name = "seseragi-syntax"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
seseragi-source = { path = "../seseragi-source" }
seseragi-release = { path = "../seseragi-release" }
unicode-ident.workspace = true

[dev-dependencies]
serde_json.workspace = true
