import { gather, gatherEither, accumulated } from "./operations.js"
import { assertUnicodeVersion as $ssrg$assertUnicodeVersion } from "@seseragi/runtime/unicode-version"
import { flatMap as _ssrg_effect_flatMap } from "@seseragi/runtime/effect"
import { fromArray as _ssrg_list_from_array, listTraversable as _ssrg_list_traversable, type List as List } from "@seseragi/runtime/list"
import { Just as _ssrg_maybe_Just, Right as _ssrg_either_Right, Left as _ssrg_either_Left, Nothing as _ssrg_maybe_Nothing } from "@seseragi/runtime/sum"
import { println as _ssrg_console_println } from "@seseragi/runtime/console"
import { intShow as _ssrg_show_intShow, listShow as _ssrg_show_listShow, maybeShow as _ssrg_show_maybeShow, stringShow as _ssrg_show_stringShow, arrayShow as _ssrg_show_arrayShow, eitherShow as _ssrg_show_eitherShow } from "@seseragi/runtime/show"
import { arrayTraversable as _ssrg_array_traversable } from "@seseragi/runtime/array"
import { stringSemigroup as _ssrg_string_semigroup } from "@seseragi/runtime/string"
$ssrg$assertUnicodeVersion("17.0.0")

export const main = (_unit: undefined) => (() => { const values: List<{ readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: number }> = _ssrg_list_from_array([_ssrg_maybe_Just(1), _ssrg_maybe_Just(2)]); return (() => { const errors: ReadonlyArray<{ readonly tag: "Left"; readonly value: string } | { readonly tag: "Right"; readonly value: number }> = [_ssrg_either_Right(1), _ssrg_either_Left("first"), _ssrg_either_Left("second")]; return (() => { const strings: ReadonlyArray<{ readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: string }> = [_ssrg_maybe_Just("a"), _ssrg_maybe_Nothing, _ssrg_maybe_Just("b")]; return _ssrg_effect_flatMap(_ssrg_console_println(_ssrg_show_maybeShow<List<number>>(_ssrg_show_listShow<number>(_ssrg_show_intShow))["show"](((gather(values)(_ssrg_list_traversable)) as { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: List<number> }))), () => _ssrg_effect_flatMap(_ssrg_console_println(_ssrg_show_eitherShow<string, ReadonlyArray<number>>(_ssrg_show_stringShow, _ssrg_show_arrayShow<number>(_ssrg_show_intShow))["show"](((gatherEither(errors)(_ssrg_array_traversable)) as { readonly tag: "Left"; readonly value: string } | { readonly tag: "Right"; readonly value: ReadonlyArray<number> }))), () => _ssrg_console_println(_ssrg_show_maybeShow<string>(_ssrg_show_stringShow)["show"](((accumulated(strings)(_ssrg_string_semigroup)) as { readonly tag: "Nothing" } | { readonly tag: "Just"; readonly value: string }))))); })(); })(); })()
