import { resolve } from "node:path"

const root = resolve(import.meta.dir, "../../..")

for (const command of [
  ["node_modules/.bin/biome", "check", "apps/site"],
  [
    "node_modules/.bin/tsc",
    "--noEmit",
    "--skipLibCheck",
    "--types",
    "bun",
    "--target",
    "ES2022",
    "--module",
    "Preserve",
    "--moduleResolution",
    "Bundler",
    "apps/site/scripts/build.ts",
    "apps/site/client/mobile-navigation.ts",
    "apps/site/client/language-menu.ts",
    "apps/site/scripts/check-examples.ts",
    "apps/site/scripts/check-content-map.ts",
    "apps/site/tests/build.test.ts",
    "apps/site/tests/browser.test.ts",
    "apps/site/tests/deployment.test.ts",
    "apps/site/tests/coverage.test.ts",
    "apps/site/tests/reference-titles.test.ts",
    "apps/site/tests/library-titles.test.ts",
    "apps/site/tests/explanations.test.ts",
    "apps/site/tests/first-run.test.ts",
    "apps/site/tests/comparisons.test.ts",
    "apps/site/tests/entrance.test.ts",
    "apps/site/tests/values-functions.test.ts",
    "apps/site/tests/array-editorial.test.ts",
    "apps/site/tests/examples-releases.test.ts",
    "apps/site/tests/data-choices.test.ts",
    "apps/site/tests/render-generator.test.ts",
    "apps/site/tests/text-editorial.test.ts",
    "apps/site/tests/failure-readers.test.ts",
    "apps/site/tests/syntax-reader.test.ts",
    "apps/site/tests/sequence-editorial.test.ts",
    "apps/site/tests/type-readers.test.ts",
    "apps/site/tests/data-operations.test.ts",
    "apps/site/tests/module-projects.test.ts",
    "apps/site/tests/explanation-groups.test.ts",
    "apps/site/tests/modules-reader.test.ts",
    "apps/site/tests/type-limits.test.ts",
    "apps/site/tests/model-reader.test.ts",
    "apps/site/tests/model-concepts.test.ts",
    "apps/site/tests/lifecycle-readers.test.ts",
    "apps/site/tests/trait-readers.test.ts",
    "apps/site/tests/list-editorial.test.ts",
    "apps/site/tests/library-landing.test.ts",
    "apps/site/tests/api-corrections.test.ts",
    "apps/site/tests/map-editorial.test.ts",
    "apps/site/tests/unicode-reader.test.ts",
    "apps/site/tests/regex-readers.test.ts",
    "apps/site/tests/set-editorial.test.ts",
    "apps/site/tests/nonempty-iterator-readers.test.ts",
    "apps/site/tests/char-text-reader.test.ts",
    "apps/site/tests/collection-type-readers.test.ts",
    "apps/site/tests/data-validation-readers.test.ts",
    "apps/site/tests/numeric-readers.test.ts",
    "apps/site/tests/result-foundation-readers.test.ts",
  ],
  ["python3", "-B", "apps/site/tests/prose.test.py"],
  ["cargo", "build", "-p", "seseragi-cli"],
  ["bun", "apps/site/scripts/check-examples.ts"],
  [
    "cargo",
    "test",
    "-p",
    "seseragi-conformance",
    "stdlib_surface::tests::canonical_",
  ],
]) {
  const result = Bun.spawnSync(command, {
    cwd: root,
    stdout: "inherit",
    stderr: "inherit",
  })
  if (result.exitCode !== 0) process.exit(result.exitCode)
}

const contentMap = Bun.spawnSync(
  ["bun", "apps/site/scripts/check-content-map.ts"],
  {
    cwd: root,
    stdout: "inherit",
    stderr: "inherit",
  }
)
if (contentMap.exitCode !== 0) process.exit(contentMap.exitCode)

const test = Bun.spawnSync(
  [
    "bun",
    "test",
    "apps/site/tests/build.test.ts",
    "apps/site/tests/deployment.test.ts",
    "apps/site/tests/coverage.test.ts",
    "apps/site/tests/reference-titles.test.ts",
    "apps/site/tests/library-titles.test.ts",
    "apps/site/tests/explanations.test.ts",
    "apps/site/tests/first-run.test.ts",
    "apps/site/tests/comparisons.test.ts",
    "apps/site/tests/entrance.test.ts",
    "apps/site/tests/values-functions.test.ts",
    "apps/site/tests/array-editorial.test.ts",
    "apps/site/tests/examples-releases.test.ts",
    "apps/site/tests/data-choices.test.ts",
    "apps/site/tests/render-generator.test.ts",
    "apps/site/tests/text-editorial.test.ts",
    "apps/site/tests/failure-readers.test.ts",
    "apps/site/tests/syntax-reader.test.ts",
    "apps/site/tests/sequence-editorial.test.ts",
    "apps/site/tests/type-readers.test.ts",
    "apps/site/tests/data-operations.test.ts",
    "apps/site/tests/module-projects.test.ts",
    "apps/site/tests/explanation-groups.test.ts",
    "apps/site/tests/modules-reader.test.ts",
    "apps/site/tests/type-limits.test.ts",
    "apps/site/tests/model-reader.test.ts",
    "apps/site/tests/model-concepts.test.ts",
    "apps/site/tests/lifecycle-readers.test.ts",
    "apps/site/tests/trait-readers.test.ts",
    "apps/site/tests/list-editorial.test.ts",
    "apps/site/tests/library-landing.test.ts",
    "apps/site/tests/api-corrections.test.ts",
    "apps/site/tests/map-editorial.test.ts",
    "apps/site/tests/unicode-reader.test.ts",
    "apps/site/tests/regex-readers.test.ts",
    "apps/site/tests/set-editorial.test.ts",
    "apps/site/tests/nonempty-iterator-readers.test.ts",
    "apps/site/tests/char-text-reader.test.ts",
    "apps/site/tests/collection-type-readers.test.ts",
    "apps/site/tests/data-validation-readers.test.ts",
    "apps/site/tests/numeric-readers.test.ts",
    "apps/site/tests/result-foundation-readers.test.ts",
  ],
  {
    cwd: root,
    env: {
      ...process.env,
      SESERAGI_BIN: resolve(root, "target/debug/seseragi"),
    },
    stdout: "inherit",
    stderr: "inherit",
  }
)
if (test.exitCode !== 0) process.exit(test.exitCode)

const browser = Bun.spawnSync(["bun", "apps/site/tests/browser.test.ts"], {
  cwd: root,
  env: {
    ...process.env,
    SESERAGI_BIN: resolve(root, "target/debug/seseragi"),
  },
  stdout: "inherit",
  stderr: "inherit",
})
process.exit(browser.exitCode)
