import { canonicalExample } from "./canonical-example"

export const jsonReaderCases = [
  {
    slug: "array-counts",
    output: "[2,0,5]\n[]\nCounts rejected\n",
  },
  {
    slug: "codec-stages",
    output: '{"name":"Mio","retries":2}\nReady: Mio\n',
  },
  {
    slug: "greeting",
    output: "Hello, Mio\nHello, \nName rejected\n",
  },
  {
    slug: "optional-name",
    output: "Name is missing\nPresent: \nPresent: Mio\nName must be text\n",
  },
  {
    slug: "parse-errors",
    output: 'Valid JSON: {"name":"Mio"}\nInvalid JSON syntax\n',
  },
  {
    slug: "parse-normalize",
    output:
      '{"name":"Mio","retries":2}\n[true,null,"ready"]\nInvalid JSON text\n',
  },
  {
    slug: "people-names",
    output:
      '["Mio","Aki"]\n[]\n$.people[1].name | expected JsonString\n$.people[1] | missing name\n$.people[0] | expected object\n$.people | expected array\n$ | missing people\n',
  },
  {
    slug: "read-errors",
    output: "Ready: Mio\nSettings shape rejected\nJSON text rejected\n",
  },
  {
    slug: "required-name",
    output: "Name: Mio\nName is missing\nName must be text\n",
  },
  {
    slug: "settings-first-look",
    output: "Ready: Mio\nSettings rejected\nSettings rejected\n",
  },
  {
    slug: "settings-write",
    output:
      '{"name":"Mio","retries":2}\n{"name":"Line\\n\\"two\\"","retries":0}\n',
  },
  {
    slug: "two-labels",
    output:
      '[["first","A"],["second","B"]]\nLabels rejected\nLabels rejected\n',
  },
] as const

export const jsonReaderRoutes = [
  {
    identity: "std/json",
    module: "std/json",
    namespace: "module",
    kind: "module",
    name: "std/json",
    slug: "module",
    example: "settings-first-look",
    route: "/docs/library/json/",
  },
  {
    identity: "std/json::Json",
    module: "std/json",
    namespace: "type",
    kind: "opaque-type",
    name: "Json",
    slug: "json",
    example: "parse-normalize",
    route: "/docs/library/json/opaque-type/json/",
  },
  {
    identity: "std/json::Decoder",
    module: "std/json",
    namespace: "type",
    kind: "alias",
    name: "Decoder",
    slug: "decoder",
    example: "required-name",
    route: "/docs/library/json/alias/decoder/",
  },
  {
    identity: "std/json::Encoder",
    module: "std/json",
    namespace: "type",
    kind: "alias",
    name: "Encoder",
    slug: "encoder",
    example: "codec-stages",
    route: "/docs/library/json/alias/encoder/",
  },
  {
    identity: "std/json::DecodeError",
    module: "std/json",
    namespace: "type",
    kind: "opaque-struct",
    name: "DecodeError",
    slug: "decodeerror",
    example: "people-names",
    route: "/docs/library/json/opaque-struct/decodeerror/",
  },
  {
    identity: "std/json::JsonParseError",
    module: "std/json",
    namespace: "type",
    kind: "opaque-type",
    name: "JsonParseError",
    slug: "jsonparseerror",
    example: "parse-errors",
    route: "/docs/library/json/opaque-type/jsonparseerror/",
  },
  {
    identity: "std/json::JsonReadError",
    module: "std/json",
    namespace: "type",
    kind: "opaque-type",
    name: "JsonReadError",
    slug: "jsonreaderror",
    example: "read-errors",
    route: "/docs/library/json/opaque-type/jsonreaderror/",
  },
  {
    identity: "std/json::parse",
    module: "std/json",
    namespace: "value",
    kind: "function",
    name: "parse",
    slug: "parse",
    example: "parse-normalize",
    route: "/docs/library/json/function/parse/",
  },
  {
    identity: "std/json::stringify",
    module: "std/json",
    namespace: "value",
    kind: "function",
    name: "stringify",
    slug: "stringify",
    example: "parse-normalize",
    route: "/docs/library/json/function/stringify/",
  },
  {
    identity: "std/json::encodeString",
    module: "std/json",
    namespace: "value",
    kind: "function",
    name: "encodeString",
    slug: "encodestring",
    example: "settings-write",
    route: "/docs/library/json/function/encodestring/",
  },
  {
    identity: "std/json::decodeString",
    module: "std/json",
    namespace: "value",
    kind: "function",
    name: "decodeString",
    slug: "decodestring",
    example: "settings-first-look",
    route: "/docs/library/json/function/decodestring/",
  },
  {
    identity: "std/json::field",
    module: "std/json",
    namespace: "value",
    kind: "function",
    name: "field",
    slug: "field",
    example: "required-name",
    route: "/docs/library/json/function/field/",
  },
  {
    identity: "std/json::optionalField",
    module: "std/json",
    namespace: "value",
    kind: "function",
    name: "optionalField",
    slug: "optionalfield",
    example: "optional-name",
    route: "/docs/library/json/function/optionalfield/",
  },
  {
    identity: "std/json::array",
    module: "std/json",
    namespace: "value",
    kind: "function",
    name: "array",
    slug: "array",
    example: "array-counts",
    route: "/docs/library/json/function/array/",
  },
  {
    identity: "std/json::record",
    module: "std/json",
    namespace: "value",
    kind: "function",
    name: "record",
    slug: "record",
    example: "two-labels",
    route: "/docs/library/json/function/record/",
  },
  {
    identity: "std/json::map",
    module: "std/json",
    namespace: "value",
    kind: "function",
    name: "map",
    slug: "map",
    example: "greeting",
    route: "/docs/library/json/function/map/",
  },
  {
    identity: "std/prelude::JsonEncode",
    module: "std/prelude",
    namespace: "trait",
    kind: "trait",
    name: "JsonEncode",
    slug: "jsonencode",
    example: "settings-write",
    route: "/docs/library/prelude/trait/jsonencode/",
  },
  {
    identity: "std/prelude::JsonDecode",
    module: "std/prelude",
    namespace: "trait",
    kind: "trait",
    name: "JsonDecode",
    slug: "jsondecode",
    example: "settings-first-look",
    route: "/docs/library/prelude/trait/jsondecode/",
  },
  {
    identity: "std/prelude::JsonEncode::encodeJson",
    module: "std/prelude",
    namespace: "value",
    kind: "function",
    name: "encodeJson",
    slug: "encodejson",
    example: "codec-stages",
    route: "/docs/library/prelude/function/encodejson/",
  },
  {
    identity: "std/prelude::JsonDecode::decodeJson",
    module: "std/prelude",
    namespace: "value",
    kind: "function",
    name: "decodeJson",
    slug: "decodejson",
    example: "codec-stages",
    route: "/docs/library/prelude/function/decodejson/",
  },
] as const

export function jsonReaderExamples(playgroundUrl: string) {
  return jsonReaderCases.flatMap(({ slug }) => [
    canonicalExample(
      `json-reader-${slug}`,
      `apps/site/examples/src/json-reader/${slug}.ssrg`,
      playgroundUrl
    ),
    canonicalExample(
      `json-reader-${slug}-ts`,
      `apps/site/examples/comparisons/json-reader/${slug}.ts`,
      playgroundUrl,
      false,
      "typescript"
    ),
  ])
}
