import { canonicalExample } from "./canonical-example"

export const practicalCollectionCases = [
  {
    slug: "array-optional-access",
    output:
      'present: ""\npresent: "Review"\nmissing\nmissing\nmissing\npresent: ""\nmissing\n',
  },
  {
    slug: "array-result-state",
    output: "true\nfalse\nfalse\nfalse\n0\n1\n3\n",
  },
  {
    slug: "array-filter-tasks",
    output: '["Review","Ship"]\n["Read","Review","Ship"]\n[]\n',
  },
  {
    slug: "array-find-task",
    output: 'Review\nnot found\nnot found\n["Read","Review","Ship"]\n',
  },
  {
    slug: "array-page-records",
    output:
      '["Review","Ship"]\n[]\n[]\n["Read","Review","Ship"]\n["Read","Review","Ship"]\n["Read","Review","Ship"]\n["Read","Review","Ship"]\n[]\n[]\n[]\n[]\n["Read","Review","Ship"]\n',
  },
  {
    slug: "list-optional-access",
    output:
      'present: ""\npresent: "Review"\nmissing\nmissing\nmissing\npresent: ""\nmissing\n',
  },
  {
    slug: "list-result-state",
    output: "true\nfalse\nfalse\nfalse\n0\n1\n3\n",
  },
  {
    slug: "list-filter-tasks",
    output: '["Review","Ship"]\n["Read","Review","Ship"]\n[]\n',
  },
  {
    slug: "list-find-task",
    output: 'Review\nnot found\nnot found\n["Read","Review","Ship"]\n',
  },
  {
    slug: "list-page-records",
    output:
      '["Review","Ship"]\n[]\n[]\n["Read","Review","Ship"]\n["Read","Review","Ship"]\n["Read","Review","Ship"]\n["Read","Review","Ship"]\n[]\n[]\n[]\n[]\n["Read","Review","Ship"]\n',
  },
  {
    slug: "map-filter-stock",
    output:
      '[["tea",2],["coffee",3]]\n[["tea",2],["hold",5],["coffee",3],["empty",0]]\n[]\n',
  },
  {
    slug: "map-empty-state",
    output: "true\nfalse\nfalse\nfalse\n",
  },
  {
    slug: "set-filter-ids",
    output: "[4,3]\n[4,1,3,0]\n[]\n",
  },
  {
    slug: "set-empty-state",
    output: "true\nfalse\nfalse\nfalse\n",
  },
] as const

export const practicalCollectionRoutes = [
  {
    identity: "std/array::get",
    module: "std/array",
    namespace: "value",
    kind: "function",
    name: "get",
    slug: "array-get",
    example: "array-optional-access",
    route: "/docs/library/array/function/get/",
  },
  {
    identity: "std/array::head",
    module: "std/array",
    namespace: "value",
    kind: "function",
    name: "head",
    slug: "array-head",
    example: "array-optional-access",
    route: "/docs/library/array/function/head/",
  },
  {
    identity: "std/array::isEmpty",
    module: "std/array",
    namespace: "value",
    kind: "function",
    name: "isEmpty",
    slug: "array-isempty",
    example: "array-result-state",
    route: "/docs/library/array/function/isempty/",
  },
  {
    identity: "std/array::length",
    module: "std/array",
    namespace: "value",
    kind: "function",
    name: "length",
    slug: "array-length",
    example: "array-result-state",
    route: "/docs/library/array/function/length/",
  },
  {
    identity: "std/array::filter",
    module: "std/array",
    namespace: "value",
    kind: "function",
    name: "filter",
    slug: "array-filter",
    example: "array-filter-tasks",
    route: "/docs/library/array/function/filter/",
  },
  {
    identity: "std/array::find",
    module: "std/array",
    namespace: "value",
    kind: "function",
    name: "find",
    slug: "array-find",
    example: "array-find-task",
    route: "/docs/library/array/function/find/",
  },
  {
    identity: "std/array::take",
    module: "std/array",
    namespace: "value",
    kind: "function",
    name: "take",
    slug: "array-take",
    example: "array-page-records",
    route: "/docs/library/array/function/take/",
  },
  {
    identity: "std/array::drop",
    module: "std/array",
    namespace: "value",
    kind: "function",
    name: "drop",
    slug: "array-drop",
    example: "array-page-records",
    route: "/docs/library/array/function/drop/",
  },
  {
    identity: "std/list::get",
    module: "std/list",
    namespace: "value",
    kind: "function",
    name: "get",
    slug: "list-get",
    example: "list-optional-access",
    route: "/docs/library/list/function/get/",
  },
  {
    identity: "std/list::head",
    module: "std/list",
    namespace: "value",
    kind: "function",
    name: "head",
    slug: "list-head",
    example: "list-optional-access",
    route: "/docs/library/list/function/head/",
  },
  {
    identity: "std/list::isEmpty",
    module: "std/list",
    namespace: "value",
    kind: "function",
    name: "isEmpty",
    slug: "list-isempty",
    example: "list-result-state",
    route: "/docs/library/list/function/isempty/",
  },
  {
    identity: "std/list::length",
    module: "std/list",
    namespace: "value",
    kind: "function",
    name: "length",
    slug: "list-length",
    example: "list-result-state",
    route: "/docs/library/list/function/length/",
  },
  {
    identity: "std/list::filter",
    module: "std/list",
    namespace: "value",
    kind: "function",
    name: "filter",
    slug: "list-filter",
    example: "list-filter-tasks",
    route: "/docs/library/list/function/filter/",
  },
  {
    identity: "std/list::find",
    module: "std/list",
    namespace: "value",
    kind: "function",
    name: "find",
    slug: "list-find",
    example: "list-find-task",
    route: "/docs/library/list/function/find/",
  },
  {
    identity: "std/list::take",
    module: "std/list",
    namespace: "value",
    kind: "function",
    name: "take",
    slug: "list-take",
    example: "list-page-records",
    route: "/docs/library/list/function/take/",
  },
  {
    identity: "std/list::drop",
    module: "std/list",
    namespace: "value",
    kind: "function",
    name: "drop",
    slug: "list-drop",
    example: "list-page-records",
    route: "/docs/library/list/function/drop/",
  },
  {
    identity: "std/map::filter",
    module: "std/map",
    namespace: "value",
    kind: "function",
    name: "filter",
    slug: "map-filter",
    example: "map-filter-stock",
    route: "/docs/library/map/function/filter/",
  },
  {
    identity: "std/map::isEmpty",
    module: "std/map",
    namespace: "value",
    kind: "function",
    name: "isEmpty",
    slug: "map-isempty",
    example: "map-empty-state",
    route: "/docs/library/map/function/isempty/",
  },
  {
    identity: "std/set::filter",
    module: "std/set",
    namespace: "value",
    kind: "function",
    name: "filter",
    slug: "set-filter",
    example: "set-filter-ids",
    route: "/docs/library/set/function/filter/",
  },
  {
    identity: "std/set::isEmpty",
    module: "std/set",
    namespace: "value",
    kind: "function",
    name: "isEmpty",
    slug: "set-isempty",
    example: "set-empty-state",
    route: "/docs/library/set/function/isempty/",
  },
] as const

export function practicalCollectionExamples(playgroundUrl: string) {
  return practicalCollectionCases.flatMap(({ slug }) => [
    canonicalExample(
      `practical-collection-${slug}`,
      `apps/site/examples/src/practical-collection/${slug}.ssrg`,
      playgroundUrl
    ),
    canonicalExample(
      `practical-collection-${slug}-ts`,
      `apps/site/examples/src/practical-collection/${slug}.ts`,
      playgroundUrl,
      false,
      "typescript"
    ),
  ])
}
