import { assertUnicodeVersion as $ssrg$assertUnicodeVersion } from "@seseragi/runtime/unicode-version"
import { empty as _ssrg_bytes_empty, toInts as _ssrg_bytes_toInts, fromInts as _ssrg_bytes_fromInts, type ByteError as ByteError, type Bytes as Bytes } from "@seseragi/runtime/bytes"
import { decode as _ssrg_hex_decode, encode as _ssrg_hex_encode, hexDecodeErrorEq as _ssrg_hexDecodeErrorEq, OddHexLength as _ssrg_hex_OddHexLength, type HexDecodeError as HexDecodeError } from "@seseragi/runtime/bytes-hex"
import { intEq as _ssrg_int_eq_dictionary, arrayEq as _ssrg_array_eq_dictionary } from "@seseragi/runtime/equality"
import { decode as _ssrg_base64_decode, decodeUrl as _ssrg_base64_decodeUrl, encode as _ssrg_base64_encode, encodeUrl as _ssrg_base64_encodeUrl, base64DecodeErrorEq as _ssrg_base64DecodeErrorEq, InvalidBase64Padding as _ssrg_base64_InvalidBase64Padding, type Base64DecodeError as Base64DecodeError } from "@seseragi/runtime/bytes-base64"
import { hexDecodeErrorShow as _ssrg_hexDecodeErrorShow, base64DecodeErrorShow as _ssrg_base64DecodeErrorShow, stringShow as _ssrg_show_stringShow, boolShow as _ssrg_show_boolShow } from "@seseragi/runtime/show"
import { arrayIterable as _ssrg_array_iterable } from "@seseragi/runtime/array"
import { forEach as _ssrg_collection_for_each } from "@seseragi/runtime/collection"
import { println as _ssrg_console_println, type Console as Console, type ConsoleError as ConsoleError } from "@seseragi/runtime/console"
import { type Effect as Effect } from "@seseragi/runtime/effect"
$ssrg$assertUnicodeVersion("17.0.0")

const requireBytes = (result: { readonly tag: "Left"; readonly value: ByteError } | { readonly tag: "Right"; readonly value: Bytes }) => (($ssrg_match: { readonly tag: "Left"; readonly value: ByteError } | { readonly tag: "Right"; readonly value: Bytes }): Bytes => $ssrg_match.tag === "Left" ? ((_error: ByteError): Bytes => _ssrg_bytes_empty(undefined))($ssrg_match.value) : $ssrg_match.tag === "Right" ? ((value: Bytes): Bytes => value)($ssrg_match.value) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(result)
const hexRoundTrips = (original: Bytes) => (encoded: string) => (($ssrg_match: { readonly tag: "Left"; readonly value: HexDecodeError } | { readonly tag: "Right"; readonly value: Bytes }): boolean => $ssrg_match.tag === "Left" ? ((_error: HexDecodeError): boolean => false)($ssrg_match.value) : $ssrg_match.tag === "Right" ? ((decoded: Bytes): boolean => _ssrg_array_eq_dictionary<number>(_ssrg_int_eq_dictionary)["eq"](_ssrg_bytes_toInts(decoded))(_ssrg_bytes_toInts(original)))($ssrg_match.value) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(_ssrg_hex_decode(encoded))
const base64RoundTrips = (original: Bytes) => (encoded: string) => (($ssrg_match: { readonly tag: "Left"; readonly value: Base64DecodeError } | { readonly tag: "Right"; readonly value: Bytes }): boolean => $ssrg_match.tag === "Left" ? ((_error: Base64DecodeError): boolean => false)($ssrg_match.value) : $ssrg_match.tag === "Right" ? ((decoded: Bytes): boolean => _ssrg_array_eq_dictionary<number>(_ssrg_int_eq_dictionary)["eq"](_ssrg_bytes_toInts(decoded))(_ssrg_bytes_toInts(original)))($ssrg_match.value) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(_ssrg_base64_decode(encoded))
const base64UrlRoundTrips = (original: Bytes) => (encoded: string) => (($ssrg_match: { readonly tag: "Left"; readonly value: Base64DecodeError } | { readonly tag: "Right"; readonly value: Bytes }): boolean => $ssrg_match.tag === "Left" ? ((_error: Base64DecodeError): boolean => false)($ssrg_match.value) : $ssrg_match.tag === "Right" ? ((decoded: Bytes): boolean => _ssrg_array_eq_dictionary<number>(_ssrg_int_eq_dictionary)["eq"](_ssrg_bytes_toInts(decoded))(_ssrg_bytes_toInts(original)))($ssrg_match.value) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(_ssrg_base64_decodeUrl(encoded))
const describeHex = (result: { readonly tag: "Left"; readonly value: HexDecodeError } | { readonly tag: "Right"; readonly value: Bytes }) => (($ssrg_match: { readonly tag: "Left"; readonly value: HexDecodeError } | { readonly tag: "Right"; readonly value: Bytes }): string => $ssrg_match.tag === "Left" ? ((error: HexDecodeError): string => _ssrg_hexDecodeErrorShow["show"](error))($ssrg_match.value) : $ssrg_match.tag === "Right" ? ((_value: Bytes): string => "unexpected success")($ssrg_match.value) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(result)
const describeBase64 = (result: { readonly tag: "Left"; readonly value: Base64DecodeError } | { readonly tag: "Right"; readonly value: Bytes }) => (($ssrg_match: { readonly tag: "Left"; readonly value: Base64DecodeError } | { readonly tag: "Right"; readonly value: Bytes }): string => $ssrg_match.tag === "Left" ? ((error: Base64DecodeError): string => _ssrg_base64DecodeErrorShow["show"](error))($ssrg_match.value) : $ssrg_match.tag === "Right" ? ((_value: Bytes): string => "unexpected success")($ssrg_match.value) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(result)
export const exercise = (_unit: undefined) => (() => { const value: Bytes = requireBytes(_ssrg_bytes_fromInts([0, 15, 16, 251, 239, 255])); return (() => { const hexadecimal: string = _ssrg_hex_encode(value); return (() => { const standard: string = _ssrg_base64_encode(value); return (() => { const urlSafe: string = _ssrg_base64_encodeUrl(value); return ["hex: " + _ssrg_show_stringShow["show"](hexadecimal) + " / " + _ssrg_show_boolShow["show"](hexRoundTrips(value)(hexadecimal)) + " / " + _ssrg_show_boolShow["show"](hexRoundTrips(value)("000F10FBEFFF")), "base64: " + _ssrg_show_stringShow["show"](standard) + " / " + _ssrg_show_boolShow["show"](base64RoundTrips(value)(standard)), "base64url: " + _ssrg_show_stringShow["show"](urlSafe) + " / " + _ssrg_show_boolShow["show"](base64UrlRoundTrips(value)(urlSafe)), "hex-errors: " + _ssrg_show_stringShow["show"](describeHex(_ssrg_hex_decode("abc"))) + " / " + _ssrg_show_stringShow["show"](describeHex(_ssrg_hex_decode("00é"))), "base64-errors: " + _ssrg_show_stringShow["show"](describeBase64(_ssrg_base64_decode("Zg"))) + " / " + _ssrg_show_stringShow["show"](describeBase64(_ssrg_base64_decode("AA A"))) + " / " + _ssrg_show_stringShow["show"](describeBase64(_ssrg_base64_decode("AA=A"))) + " / " + _ssrg_show_stringShow["show"](describeBase64(_ssrg_base64_decode("AB=="))), "base64url-errors: " + _ssrg_show_stringShow["show"](describeBase64(_ssrg_base64_decodeUrl("A"))) + " / " + _ssrg_show_stringShow["show"](describeBase64(_ssrg_base64_decodeUrl("AA="))), "error-eq: " + _ssrg_show_boolShow["show"](_ssrg_hexDecodeErrorEq["eq"](_ssrg_hex_OddHexLength(3))(_ssrg_hex_OddHexLength(3))) + " / " + _ssrg_show_boolShow["show"](_ssrg_base64DecodeErrorEq["eq"](_ssrg_base64_InvalidBase64Padding(({ "offset": 2 } as const)))(_ssrg_base64_InvalidBase64Padding(({ "offset": 2 } as const))))]; })(); })(); })(); })()
export const main = (_unit: undefined) => _ssrg_collection_for_each(_ssrg_array_iterable, ($ssrg_for_value: string) => (($ssrg_match: string): Effect<{ readonly "console": Console }, ConsoleError, undefined> => ((line: string): Effect<{ readonly "console": Console }, ConsoleError, undefined> => _ssrg_console_println(line))($ssrg_match))($ssrg_for_value), exercise(undefined))
