#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(crate) struct RuntimePreludeDictionary {
    pub(crate) semantic_identity: &'static str,
    pub(crate) runtime_feature: &'static str,
    pub(crate) local_name: &'static str,
    pub(crate) module: &'static str,
    pub(crate) export_name: &'static str,
    pub(crate) source_map_name: &'static str,
}

const RUNTIME_PRELUDE_DICTIONARIES: &[RuntimePreludeDictionary] = &[
    RuntimePreludeDictionary {
        semantic_identity: "std/int::Ord",
        runtime_feature: "core.int.ord-dictionary",
        local_name: "_ssrg_int_ord_dictionary",
        module: "@seseragi/runtime/equality",
        export_name: "intOrd",
        source_map_name: "intOrd",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/bool::Ord",
        runtime_feature: "core.bool.ord-dictionary",
        local_name: "_ssrg_bool_ord_dictionary",
        module: "@seseragi/runtime/equality",
        export_name: "boolOrd",
        source_map_name: "boolOrd",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/char::Ord",
        runtime_feature: "core.char.ord-dictionary",
        local_name: "_ssrg_char_ord_dictionary",
        module: "@seseragi/runtime/equality",
        export_name: "charOrd",
        source_map_name: "charOrd",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/string::Ord",
        runtime_feature: "core.string.ord-dictionary",
        local_name: "_ssrg_string_ord_dictionary",
        module: "@seseragi/runtime/equality",
        export_name: "stringOrd",
        source_map_name: "stringOrd",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/unit::Ord",
        runtime_feature: "core.unit.ord-dictionary",
        local_name: "_ssrg_unit_ord_dictionary",
        module: "@seseragi/runtime/equality",
        export_name: "unitOrd",
        source_map_name: "unitOrd",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/collection::EqSizeError",
        runtime_feature: "core.collection.size-error.eq",
        local_name: "_ssrg_sizeErrorEq",
        module: "@seseragi/runtime/collection",
        export_name: "sizeErrorEq",
        source_map_name: "sizeErrorEq",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/map::JsonEncode",
        runtime_feature: "core.map.json-encode",
        local_name: "_ssrg_map_jsonencode",
        module: "@seseragi/runtime/json",
        export_name: "mapJsonEncode",
        source_map_name: "mapJsonEncode",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/map::JsonDecode",
        runtime_feature: "core.map.json-decode",
        local_name: "_ssrg_map_jsondecode",
        module: "@seseragi/runtime/json",
        export_name: "mapJsonDecode",
        source_map_name: "mapJsonDecode",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/set::JsonEncode",
        runtime_feature: "core.set.json-encode",
        local_name: "_ssrg_set_jsonencode",
        module: "@seseragi/runtime/json",
        export_name: "setJsonEncode",
        source_map_name: "setJsonEncode",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/set::JsonDecode",
        runtime_feature: "core.set.json-decode",
        local_name: "_ssrg_set_jsondecode",
        module: "@seseragi/runtime/json",
        export_name: "setJsonDecode",
        source_map_name: "setJsonDecode",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/map::Eq",
        runtime_feature: "core.map.eq",
        local_name: "_ssrg_map_eq",
        module: "@seseragi/runtime/map",
        export_name: "mapEq",
        source_map_name: "mapEq",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/map::Functor",
        runtime_feature: "core.map.functor",
        local_name: "_ssrg_map_functor",
        module: "@seseragi/runtime/map",
        export_name: "mapFunctor",
        source_map_name: "mapFunctor",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/map::Iterable",
        runtime_feature: "core.map.iterable",
        local_name: "_ssrg_map_iterable",
        module: "@seseragi/runtime/map",
        export_name: "mapIterable",
        source_map_name: "mapIterable",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/map::Reducible",
        runtime_feature: "core.map.reducible",
        local_name: "_ssrg_map_reducible",
        module: "@seseragi/runtime/map",
        export_name: "mapReducible",
        source_map_name: "mapReducible",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/set::Eq",
        runtime_feature: "core.set.eq",
        local_name: "_ssrg_set_eq",
        module: "@seseragi/runtime/set",
        export_name: "setEq",
        source_map_name: "setEq",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/set::Iterable",
        runtime_feature: "core.set.iterable",
        local_name: "_ssrg_set_iterable",
        module: "@seseragi/runtime/set",
        export_name: "setIterable",
        source_map_name: "setIterable",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/set::Reducible",
        runtime_feature: "core.set.reducible",
        local_name: "_ssrg_set_reducible",
        module: "@seseragi/runtime/set",
        export_name: "setReducible",
        source_map_name: "setReducible",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/int::Hash",
        runtime_feature: "core.int.hash-dictionary",
        local_name: "_ssrg_int_hash_dictionary",
        module: "@seseragi/runtime/hash",
        export_name: "intHash",
        source_map_name: "intHash",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/bool::Hash",
        runtime_feature: "core.bool.hash-dictionary",
        local_name: "_ssrg_bool_hash_dictionary",
        module: "@seseragi/runtime/hash",
        export_name: "boolHash",
        source_map_name: "boolHash",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/char::Hash",
        runtime_feature: "core.char.hash-dictionary",
        local_name: "_ssrg_char_hash_dictionary",
        module: "@seseragi/runtime/hash",
        export_name: "charHash",
        source_map_name: "charHash",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/string::Hash",
        runtime_feature: "core.string.hash-dictionary",
        local_name: "_ssrg_string_hash_dictionary",
        module: "@seseragi/runtime/hash",
        export_name: "stringHash",
        source_map_name: "stringHash",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/unit::Hash",
        runtime_feature: "core.unit.hash-dictionary",
        local_name: "_ssrg_unit_hash_dictionary",
        module: "@seseragi/runtime/hash",
        export_name: "unitHash",
        source_map_name: "unitHash",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/int::Eq",
        runtime_feature: "core.int.eq-dictionary",
        local_name: "_ssrg_int_eq_dictionary",
        module: "@seseragi/runtime/equality",
        export_name: "intEq",
        source_map_name: "intEq",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/bool::Eq",
        runtime_feature: "core.bool.eq-dictionary",
        local_name: "_ssrg_bool_eq_dictionary",
        module: "@seseragi/runtime/equality",
        export_name: "boolEq",
        source_map_name: "boolEq",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/string::Eq",
        runtime_feature: "core.string.eq-dictionary",
        local_name: "_ssrg_string_eq_dictionary",
        module: "@seseragi/runtime/equality",
        export_name: "stringEq",
        source_map_name: "stringEq",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/char::Eq",
        runtime_feature: "core.char.eq-dictionary",
        local_name: "_ssrg_char_eq_dictionary",
        module: "@seseragi/runtime/equality",
        export_name: "charEq",
        source_map_name: "charEq",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/unit::Eq",
        runtime_feature: "core.unit.eq-dictionary",
        local_name: "_ssrg_unit_eq_dictionary",
        module: "@seseragi/runtime/equality",
        export_name: "unitEq",
        source_map_name: "unitEq",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/array::Eq",
        runtime_feature: "core.array.eq-dictionary",
        local_name: "_ssrg_array_eq_dictionary",
        module: "@seseragi/runtime/equality",
        export_name: "arrayEq",
        source_map_name: "arrayEq",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/list::Eq",
        runtime_feature: "core.list.eq-dictionary",
        local_name: "_ssrg_list_eq_dictionary",
        module: "@seseragi/runtime/equality",
        export_name: "listEq",
        source_map_name: "listEq",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/tuple::Eq",
        runtime_feature: "core.tuple.eq-dictionary",
        local_name: "_ssrg_tuple_eq_dictionary",
        module: "@seseragi/runtime/equality",
        export_name: "tupleEq",
        source_map_name: "tupleEq",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/record::Eq",
        runtime_feature: "core.record.eq-dictionary",
        local_name: "_ssrg_record_eq_dictionary",
        module: "@seseragi/runtime/equality",
        export_name: "recordEq",
        source_map_name: "recordEq",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/int::Zero",
        runtime_feature: "core.int.zero-dictionary",
        local_name: "_ssrg_int_zero",
        module: "@seseragi/runtime/int",
        export_name: "intZero",
        source_map_name: "intZero",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/int::One",
        runtime_feature: "core.int.one-dictionary",
        local_name: "_ssrg_int_one",
        module: "@seseragi/runtime/int",
        export_name: "intOne",
        source_map_name: "intOne",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/int::Add",
        runtime_feature: "core.int.add-dictionary",
        local_name: "_ssrg_int_add_dictionary",
        module: "@seseragi/runtime/int",
        export_name: "intAdd",
        source_map_name: "intAdd",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/int::Sub",
        runtime_feature: "core.int.sub-dictionary",
        local_name: "_ssrg_int_sub_dictionary",
        module: "@seseragi/runtime/int",
        export_name: "intSub",
        source_map_name: "intSub",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/int::Mul",
        runtime_feature: "core.int.mul-dictionary",
        local_name: "_ssrg_int_mul_dictionary",
        module: "@seseragi/runtime/int",
        export_name: "intMul",
        source_map_name: "intMul",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/int::Div",
        runtime_feature: "core.int.div-dictionary",
        local_name: "_ssrg_int_div_dictionary",
        module: "@seseragi/runtime/int",
        export_name: "intDiv",
        source_map_name: "intDiv",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/int::Rem",
        runtime_feature: "core.int.rem-dictionary",
        local_name: "_ssrg_int_rem_dictionary",
        module: "@seseragi/runtime/int",
        export_name: "intRem",
        source_map_name: "intRem",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/int::Pow",
        runtime_feature: "core.int.pow-dictionary",
        local_name: "_ssrg_int_pow_dictionary",
        module: "@seseragi/runtime/int",
        export_name: "intPow",
        source_map_name: "intPow",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/float::Zero",
        runtime_feature: "core.float.zero-dictionary",
        local_name: "_ssrg_float_zero_dictionary",
        module: "@seseragi/runtime/float",
        export_name: "floatZero",
        source_map_name: "floatZero",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/float::One",
        runtime_feature: "core.float.one-dictionary",
        local_name: "_ssrg_float_one_dictionary",
        module: "@seseragi/runtime/float",
        export_name: "floatOne",
        source_map_name: "floatOne",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/float::Add",
        runtime_feature: "core.float.add-dictionary",
        local_name: "_ssrg_float_add_dictionary",
        module: "@seseragi/runtime/float",
        export_name: "floatAdd",
        source_map_name: "floatAdd",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/float::Sub",
        runtime_feature: "core.float.sub-dictionary",
        local_name: "_ssrg_float_sub_dictionary",
        module: "@seseragi/runtime/float",
        export_name: "floatSub",
        source_map_name: "floatSub",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/float::Mul",
        runtime_feature: "core.float.mul-dictionary",
        local_name: "_ssrg_float_mul_dictionary",
        module: "@seseragi/runtime/float",
        export_name: "floatMul",
        source_map_name: "floatMul",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/float::Div",
        runtime_feature: "core.float.div-dictionary",
        local_name: "_ssrg_float_div_dictionary",
        module: "@seseragi/runtime/float",
        export_name: "floatDiv",
        source_map_name: "floatDiv",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/float::Rem",
        runtime_feature: "core.float.rem-dictionary",
        local_name: "_ssrg_float_rem_dictionary",
        module: "@seseragi/runtime/float",
        export_name: "floatRem",
        source_map_name: "floatRem",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/float::Pow",
        runtime_feature: "core.float.pow-dictionary",
        local_name: "_ssrg_float_pow_dictionary",
        module: "@seseragi/runtime/float",
        export_name: "floatPow",
        source_map_name: "floatPow",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/string::Add",
        runtime_feature: "core.string.add-dictionary",
        local_name: "_ssrg_string_add_dictionary",
        module: "@seseragi/runtime/string",
        export_name: "stringAdd",
        source_map_name: "stringAdd",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/string::Semigroup",
        runtime_feature: "core.string.semigroup",
        local_name: "_ssrg_string_semigroup",
        module: "@seseragi/runtime/string",
        export_name: "stringSemigroup",
        source_map_name: "stringSemigroup",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/string::Monoid",
        runtime_feature: "core.string.monoid",
        local_name: "_ssrg_string_monoid",
        module: "@seseragi/runtime/string",
        export_name: "stringMonoid",
        source_map_name: "stringMonoid",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/array::Semigroup",
        runtime_feature: "core.array.semigroup",
        local_name: "_ssrg_array_semigroup",
        module: "@seseragi/runtime/array",
        export_name: "arraySemigroup",
        source_map_name: "arraySemigroup",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/array::Monoid",
        runtime_feature: "core.array.monoid",
        local_name: "_ssrg_array_monoid",
        module: "@seseragi/runtime/array",
        export_name: "arrayMonoid",
        source_map_name: "arrayMonoid",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/list::Semigroup",
        runtime_feature: "core.list.semigroup",
        local_name: "_ssrg_list_semigroup",
        module: "@seseragi/runtime/list",
        export_name: "listSemigroup",
        source_map_name: "listSemigroup",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/list::Monoid",
        runtime_feature: "core.list.monoid",
        local_name: "_ssrg_list_monoid",
        module: "@seseragi/runtime/list",
        export_name: "listMonoid",
        source_map_name: "listMonoid",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/array::Iterable",
        runtime_feature: "core.array.iterable",
        local_name: "_ssrg_array_iterable",
        module: "@seseragi/runtime/array",
        export_name: "arrayIterable",
        source_map_name: "arrayIterable",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/list::Iterable",
        runtime_feature: "core.list.iterable",
        local_name: "_ssrg_list_iterable",
        module: "@seseragi/runtime/list",
        export_name: "listIterable",
        source_map_name: "listIterable",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/range::Iterable",
        runtime_feature: "core.range.iterable",
        local_name: "_ssrg_range_iterable",
        module: "@seseragi/runtime/range",
        export_name: "rangeIterable",
        source_map_name: "rangeIterable",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/iterator::Iterable",
        runtime_feature: "core.iterator.iterable",
        local_name: "_ssrg_iterator_iterable",
        module: "@seseragi/runtime/iterator",
        export_name: "iteratorIterable",
        source_map_name: "iteratorIterable",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/array::Reducible",
        runtime_feature: "core.array.reducible",
        local_name: "_ssrg_array_reducible",
        module: "@seseragi/runtime/array",
        export_name: "arrayReducible",
        source_map_name: "arrayReducible",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/list::Reducible",
        runtime_feature: "core.list.reducible",
        local_name: "_ssrg_list_reducible",
        module: "@seseragi/runtime/list",
        export_name: "listReducible",
        source_map_name: "listReducible",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/range::Reducible",
        runtime_feature: "core.range.reducible",
        local_name: "_ssrg_range_reducible",
        module: "@seseragi/runtime/range",
        export_name: "rangeReducible",
        source_map_name: "rangeReducible",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/maybe::Semigroup",
        runtime_feature: "core.maybe.semigroup",
        local_name: "_ssrg_maybe_semigroup",
        module: "@seseragi/runtime/sum",
        export_name: "maybeSemigroup",
        source_map_name: "maybeSemigroup",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/maybe::Monoid",
        runtime_feature: "core.maybe.monoid",
        local_name: "_ssrg_maybe_monoid",
        module: "@seseragi/runtime/sum",
        export_name: "maybeMonoid",
        source_map_name: "maybeMonoid",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/maybe::Functor",
        runtime_feature: "core.maybe.functor",
        local_name: "_ssrg_maybe_functor",
        module: "@seseragi/runtime/sum",
        export_name: "maybeFunctor",
        source_map_name: "maybeFunctor",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/maybe::Applicative",
        runtime_feature: "core.maybe.applicative",
        local_name: "_ssrg_maybe_applicative",
        module: "@seseragi/runtime/sum",
        export_name: "maybeApplicative",
        source_map_name: "maybeApplicative",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/maybe::Monad",
        runtime_feature: "core.maybe.monad",
        local_name: "_ssrg_maybe_monad",
        module: "@seseragi/runtime/sum",
        export_name: "maybeMonad",
        source_map_name: "maybeMonad",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/either::Functor",
        runtime_feature: "core.either.functor",
        local_name: "_ssrg_either_functor",
        module: "@seseragi/runtime/sum",
        export_name: "eitherFunctor",
        source_map_name: "eitherFunctor",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/either::Applicative",
        runtime_feature: "core.either.applicative",
        local_name: "_ssrg_either_applicative",
        module: "@seseragi/runtime/sum",
        export_name: "eitherApplicative",
        source_map_name: "eitherApplicative",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/either::Monad",
        runtime_feature: "core.either.monad",
        local_name: "_ssrg_either_monad",
        module: "@seseragi/runtime/sum",
        export_name: "eitherMonad",
        source_map_name: "eitherMonad",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/array::Functor",
        runtime_feature: "core.array.functor",
        local_name: "_ssrg_array_functor",
        module: "@seseragi/runtime/array",
        export_name: "arrayFunctor",
        source_map_name: "arrayFunctor",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/array::Applicative",
        runtime_feature: "core.array.applicative",
        local_name: "_ssrg_array_applicative",
        module: "@seseragi/runtime/array",
        export_name: "arrayApplicative",
        source_map_name: "arrayApplicative",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/array::Monad",
        runtime_feature: "core.array.monad",
        local_name: "_ssrg_array_monad",
        module: "@seseragi/runtime/array",
        export_name: "arrayMonad",
        source_map_name: "arrayMonad",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/array::Traversable",
        runtime_feature: "core.array.traversable",
        local_name: "_ssrg_array_traversable",
        module: "@seseragi/runtime/array",
        export_name: "arrayTraversable",
        source_map_name: "arrayTraversable",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/list::Functor",
        runtime_feature: "core.list.functor",
        local_name: "_ssrg_list_functor",
        module: "@seseragi/runtime/list",
        export_name: "listFunctor",
        source_map_name: "listFunctor",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/list::Applicative",
        runtime_feature: "core.list.applicative",
        local_name: "_ssrg_list_applicative",
        module: "@seseragi/runtime/list",
        export_name: "listApplicative",
        source_map_name: "listApplicative",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/list::Monad",
        runtime_feature: "core.list.monad",
        local_name: "_ssrg_list_monad",
        module: "@seseragi/runtime/list",
        export_name: "listMonad",
        source_map_name: "listMonad",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/list::Traversable",
        runtime_feature: "core.list.traversable",
        local_name: "_ssrg_list_traversable",
        module: "@seseragi/runtime/list",
        export_name: "listTraversable",
        source_map_name: "listTraversable",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/non-empty-list::Eq",
        runtime_feature: "core.non-empty-list.eq-dictionary",
        local_name: "_ssrg_non_empty_list_eq_dictionary",
        module: "@seseragi/runtime/equality",
        export_name: "nonEmptyListEq",
        source_map_name: "nonEmptyListEq",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/non-empty-list::Ord",
        runtime_feature: "core.non-empty-list.ord-dictionary",
        local_name: "_ssrg_non_empty_list_ord_dictionary",
        module: "@seseragi/runtime/list",
        export_name: "nonEmptyListOrd",
        source_map_name: "nonEmptyListOrd",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/non-empty-list::Hash",
        runtime_feature: "core.non-empty-list.hash-dictionary",
        local_name: "_ssrg_non_empty_list_hash_dictionary",
        module: "@seseragi/runtime/hash",
        export_name: "nonEmptyListHash",
        source_map_name: "nonEmptyListHash",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/non-empty-list::Semigroup",
        runtime_feature: "core.non-empty-list.semigroup",
        local_name: "_ssrg_non_empty_list_semigroup",
        module: "@seseragi/runtime/list",
        export_name: "nonEmptyListSemigroup",
        source_map_name: "nonEmptyListSemigroup",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/non-empty-list::Iterable",
        runtime_feature: "core.non-empty-list.iterable",
        local_name: "_ssrg_non_empty_list_iterable",
        module: "@seseragi/runtime/list",
        export_name: "nonEmptyListIterable",
        source_map_name: "nonEmptyListIterable",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/non-empty-list::Reducible",
        runtime_feature: "core.non-empty-list.reducible",
        local_name: "_ssrg_non_empty_list_reducible",
        module: "@seseragi/runtime/list",
        export_name: "nonEmptyListReducible",
        source_map_name: "nonEmptyListReducible",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/non-empty-list::Functor",
        runtime_feature: "core.non-empty-list.functor",
        local_name: "_ssrg_non_empty_list_functor",
        module: "@seseragi/runtime/list",
        export_name: "nonEmptyListFunctor",
        source_map_name: "nonEmptyListFunctor",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/non-empty-list::Applicative",
        runtime_feature: "core.non-empty-list.applicative",
        local_name: "_ssrg_non_empty_list_applicative",
        module: "@seseragi/runtime/list",
        export_name: "nonEmptyListApplicative",
        source_map_name: "nonEmptyListApplicative",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/non-empty-list::Monad",
        runtime_feature: "core.non-empty-list.monad",
        local_name: "_ssrg_non_empty_list_monad",
        module: "@seseragi/runtime/list",
        export_name: "nonEmptyListMonad",
        source_map_name: "nonEmptyListMonad",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/non-empty-list::Traversable",
        runtime_feature: "core.non-empty-list.traversable",
        local_name: "_ssrg_non_empty_list_traversable",
        module: "@seseragi/runtime/list",
        export_name: "nonEmptyListTraversable",
        source_map_name: "nonEmptyListTraversable",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/effect::Functor",
        runtime_feature: "effect.core.functor",
        local_name: "_ssrg_effect_functor",
        module: "@seseragi/runtime/effect",
        export_name: "effectFunctor",
        source_map_name: "effectFunctor",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/effect::Applicative",
        runtime_feature: "effect.core.applicative",
        local_name: "_ssrg_effect_applicative",
        module: "@seseragi/runtime/effect",
        export_name: "effectApplicative",
        source_map_name: "effectApplicative",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/effect::Monad",
        runtime_feature: "effect.core.monad",
        local_name: "_ssrg_effect_monad",
        module: "@seseragi/runtime/effect",
        export_name: "effectMonad",
        source_map_name: "effectMonad",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/stream::Functor",
        runtime_feature: "stream.functor",
        local_name: "_ssrg_stream_functor",
        module: "@seseragi/runtime/stream",
        export_name: "streamFunctor",
        source_map_name: "streamFunctor",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/stream::Applicative",
        runtime_feature: "stream.applicative",
        local_name: "_ssrg_stream_applicative",
        module: "@seseragi/runtime/stream",
        export_name: "streamApplicative",
        source_map_name: "streamApplicative",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/stream::Monad",
        runtime_feature: "stream.monad",
        local_name: "_ssrg_stream_monad",
        module: "@seseragi/runtime/stream",
        export_name: "streamMonad",
        source_map_name: "streamMonad",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/signal::Functor",
        runtime_feature: "signal.functor",
        local_name: "_ssrg_signal_functor",
        module: "@seseragi/runtime/signal",
        export_name: "signalFunctor",
        source_map_name: "signalFunctor",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/signal::Applicative",
        runtime_feature: "signal.applicative",
        local_name: "_ssrg_signal_applicative",
        module: "@seseragi/runtime/signal",
        export_name: "signalApplicative",
        source_map_name: "signalApplicative",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/bool::JsonEncode",
        runtime_feature: "json.bool.encode",
        local_name: "_ssrg_bool_json_encode",
        module: "@seseragi/runtime/json",
        export_name: "boolJsonEncode",
        source_map_name: "boolJsonEncode",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/bool::JsonDecode",
        runtime_feature: "json.bool.decode",
        local_name: "_ssrg_bool_json_decode",
        module: "@seseragi/runtime/json",
        export_name: "boolJsonDecode",
        source_map_name: "boolJsonDecode",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/string::JsonEncode",
        runtime_feature: "json.string.encode",
        local_name: "_ssrg_string_json_encode",
        module: "@seseragi/runtime/json",
        export_name: "stringJsonEncode",
        source_map_name: "stringJsonEncode",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/string::JsonDecode",
        runtime_feature: "json.string.decode",
        local_name: "_ssrg_string_json_decode",
        module: "@seseragi/runtime/json",
        export_name: "stringJsonDecode",
        source_map_name: "stringJsonDecode",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/int::JsonEncode",
        runtime_feature: "json.int.encode",
        local_name: "_ssrg_int_json_encode",
        module: "@seseragi/runtime/json",
        export_name: "intJsonEncode",
        source_map_name: "intJsonEncode",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/int::JsonDecode",
        runtime_feature: "json.int.decode",
        local_name: "_ssrg_int_json_decode",
        module: "@seseragi/runtime/json",
        export_name: "intJsonDecode",
        source_map_name: "intJsonDecode",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/unit::JsonEncode",
        runtime_feature: "json.unit.encode",
        local_name: "_ssrg_unit_json_encode",
        module: "@seseragi/runtime/json",
        export_name: "unitJsonEncode",
        source_map_name: "unitJsonEncode",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/unit::JsonDecode",
        runtime_feature: "json.unit.decode",
        local_name: "_ssrg_unit_json_decode",
        module: "@seseragi/runtime/json",
        export_name: "unitJsonDecode",
        source_map_name: "unitJsonDecode",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/json::JsonEncode",
        runtime_feature: "json.value.encode",
        local_name: "_ssrg_json_json_encode",
        module: "@seseragi/runtime/json",
        export_name: "jsonJsonEncode",
        source_map_name: "jsonJsonEncode",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/json::JsonDecode",
        runtime_feature: "json.value.decode",
        local_name: "_ssrg_json_json_decode",
        module: "@seseragi/runtime/json",
        export_name: "jsonJsonDecode",
        source_map_name: "jsonJsonDecode",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/maybe::JsonEncode",
        runtime_feature: "json.maybe.encode",
        local_name: "_ssrg_maybe_json_encode",
        module: "@seseragi/runtime/json",
        export_name: "maybeJsonEncode",
        source_map_name: "maybeJsonEncode",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/maybe::JsonDecode",
        runtime_feature: "json.maybe.decode",
        local_name: "_ssrg_maybe_json_decode",
        module: "@seseragi/runtime/json",
        export_name: "maybeJsonDecode",
        source_map_name: "maybeJsonDecode",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/either::JsonEncode",
        runtime_feature: "json.either.encode",
        local_name: "_ssrg_either_json_encode",
        module: "@seseragi/runtime/json",
        export_name: "eitherJsonEncode",
        source_map_name: "eitherJsonEncode",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/either::JsonDecode",
        runtime_feature: "json.either.decode",
        local_name: "_ssrg_either_json_decode",
        module: "@seseragi/runtime/json",
        export_name: "eitherJsonDecode",
        source_map_name: "eitherJsonDecode",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/array::JsonEncode",
        runtime_feature: "json.array.encode",
        local_name: "_ssrg_array_json_encode",
        module: "@seseragi/runtime/json",
        export_name: "arrayJsonEncode",
        source_map_name: "arrayJsonEncode",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/array::JsonDecode",
        runtime_feature: "json.array.decode",
        local_name: "_ssrg_array_json_decode",
        module: "@seseragi/runtime/json",
        export_name: "arrayJsonDecode",
        source_map_name: "arrayJsonDecode",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/list::JsonEncode",
        runtime_feature: "json.list.encode",
        local_name: "_ssrg_list_json_encode",
        module: "@seseragi/runtime/json",
        export_name: "listJsonEncode",
        source_map_name: "listJsonEncode",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/list::JsonDecode",
        runtime_feature: "json.list.decode",
        local_name: "_ssrg_list_json_decode",
        module: "@seseragi/runtime/json",
        export_name: "listJsonDecode",
        source_map_name: "listJsonDecode",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/tuple::JsonEncode",
        runtime_feature: "json.tuple.encode",
        local_name: "_ssrg_tuple_json_encode",
        module: "@seseragi/runtime/json",
        export_name: "tupleJsonEncode",
        source_map_name: "tupleJsonEncode",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/tuple::JsonDecode",
        runtime_feature: "json.tuple.decode",
        local_name: "_ssrg_tuple_json_decode",
        module: "@seseragi/runtime/json",
        export_name: "tupleJsonDecode",
        source_map_name: "tupleJsonDecode",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/record::JsonEncode",
        runtime_feature: "json.record.encode",
        local_name: "_ssrg_record_json_encode",
        module: "@seseragi/runtime/json",
        export_name: "recordJsonEncode",
        source_map_name: "recordJsonEncode",
    },
    RuntimePreludeDictionary {
        semantic_identity: "std/record::JsonDecode",
        runtime_feature: "json.record.decode",
        local_name: "_ssrg_record_json_decode",
        module: "@seseragi/runtime/json",
        export_name: "recordJsonDecode",
        source_map_name: "recordJsonDecode",
    },
];

pub(crate) fn runtime_prelude_dictionary_for_feature(
    feature: &str,
) -> Option<RuntimePreludeDictionary> {
    RUNTIME_PRELUDE_DICTIONARIES
        .iter()
        .copied()
        .find(|dictionary| dictionary.runtime_feature == feature)
}

pub(crate) fn runtime_prelude_dictionary_for_identity(
    identity: &str,
) -> Option<RuntimePreludeDictionary> {
    RUNTIME_PRELUDE_DICTIONARIES
        .iter()
        .copied()
        .find(|dictionary| dictionary.semantic_identity == identity)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn maps_the_standard_prelude_dictionary_families() {
        for (identity, feature, module, export_name) in [
            (
                "std/int::Hash",
                "core.int.hash-dictionary",
                "@seseragi/runtime/hash",
                "intHash",
            ),
            (
                "std/bool::Hash",
                "core.bool.hash-dictionary",
                "@seseragi/runtime/hash",
                "boolHash",
            ),
            (
                "std/char::Hash",
                "core.char.hash-dictionary",
                "@seseragi/runtime/hash",
                "charHash",
            ),
            (
                "std/string::Hash",
                "core.string.hash-dictionary",
                "@seseragi/runtime/hash",
                "stringHash",
            ),
            (
                "std/unit::Hash",
                "core.unit.hash-dictionary",
                "@seseragi/runtime/hash",
                "unitHash",
            ),
            (
                "std/int::Zero",
                "core.int.zero-dictionary",
                "@seseragi/runtime/int",
                "intZero",
            ),
            (
                "std/int::Add",
                "core.int.add-dictionary",
                "@seseragi/runtime/int",
                "intAdd",
            ),
            (
                "std/string::Semigroup",
                "core.string.semigroup",
                "@seseragi/runtime/string",
                "stringSemigroup",
            ),
            (
                "std/string::Monoid",
                "core.string.monoid",
                "@seseragi/runtime/string",
                "stringMonoid",
            ),
            (
                "std/array::Semigroup",
                "core.array.semigroup",
                "@seseragi/runtime/array",
                "arraySemigroup",
            ),
            (
                "std/array::Monoid",
                "core.array.monoid",
                "@seseragi/runtime/array",
                "arrayMonoid",
            ),
            (
                "std/list::Semigroup",
                "core.list.semigroup",
                "@seseragi/runtime/list",
                "listSemigroup",
            ),
            (
                "std/list::Monoid",
                "core.list.monoid",
                "@seseragi/runtime/list",
                "listMonoid",
            ),
            (
                "std/array::Iterable",
                "core.array.iterable",
                "@seseragi/runtime/array",
                "arrayIterable",
            ),
            (
                "std/list::Iterable",
                "core.list.iterable",
                "@seseragi/runtime/list",
                "listIterable",
            ),
            (
                "std/range::Iterable",
                "core.range.iterable",
                "@seseragi/runtime/range",
                "rangeIterable",
            ),
            (
                "std/array::Reducible",
                "core.array.reducible",
                "@seseragi/runtime/array",
                "arrayReducible",
            ),
            (
                "std/list::Reducible",
                "core.list.reducible",
                "@seseragi/runtime/list",
                "listReducible",
            ),
            (
                "std/range::Reducible",
                "core.range.reducible",
                "@seseragi/runtime/range",
                "rangeReducible",
            ),
            (
                "std/maybe::Functor",
                "core.maybe.functor",
                "@seseragi/runtime/sum",
                "maybeFunctor",
            ),
            (
                "std/maybe::Applicative",
                "core.maybe.applicative",
                "@seseragi/runtime/sum",
                "maybeApplicative",
            ),
            (
                "std/maybe::Monad",
                "core.maybe.monad",
                "@seseragi/runtime/sum",
                "maybeMonad",
            ),
            (
                "std/either::Functor",
                "core.either.functor",
                "@seseragi/runtime/sum",
                "eitherFunctor",
            ),
            (
                "std/either::Applicative",
                "core.either.applicative",
                "@seseragi/runtime/sum",
                "eitherApplicative",
            ),
            (
                "std/either::Monad",
                "core.either.monad",
                "@seseragi/runtime/sum",
                "eitherMonad",
            ),
            (
                "std/array::Functor",
                "core.array.functor",
                "@seseragi/runtime/array",
                "arrayFunctor",
            ),
            (
                "std/array::Applicative",
                "core.array.applicative",
                "@seseragi/runtime/array",
                "arrayApplicative",
            ),
            (
                "std/array::Monad",
                "core.array.monad",
                "@seseragi/runtime/array",
                "arrayMonad",
            ),
            (
                "std/array::Traversable",
                "core.array.traversable",
                "@seseragi/runtime/array",
                "arrayTraversable",
            ),
            (
                "std/list::Functor",
                "core.list.functor",
                "@seseragi/runtime/list",
                "listFunctor",
            ),
            (
                "std/list::Applicative",
                "core.list.applicative",
                "@seseragi/runtime/list",
                "listApplicative",
            ),
            (
                "std/list::Monad",
                "core.list.monad",
                "@seseragi/runtime/list",
                "listMonad",
            ),
            (
                "std/list::Traversable",
                "core.list.traversable",
                "@seseragi/runtime/list",
                "listTraversable",
            ),
            (
                "std/non-empty-list::Traversable",
                "core.non-empty-list.traversable",
                "@seseragi/runtime/list",
                "nonEmptyListTraversable",
            ),
            (
                "std/effect::Functor",
                "effect.core.functor",
                "@seseragi/runtime/effect",
                "effectFunctor",
            ),
            (
                "std/effect::Applicative",
                "effect.core.applicative",
                "@seseragi/runtime/effect",
                "effectApplicative",
            ),
            (
                "std/effect::Monad",
                "effect.core.monad",
                "@seseragi/runtime/effect",
                "effectMonad",
            ),
            (
                "std/stream::Functor",
                "stream.functor",
                "@seseragi/runtime/stream",
                "streamFunctor",
            ),
            (
                "std/stream::Applicative",
                "stream.applicative",
                "@seseragi/runtime/stream",
                "streamApplicative",
            ),
            (
                "std/stream::Monad",
                "stream.monad",
                "@seseragi/runtime/stream",
                "streamMonad",
            ),
            (
                "std/signal::Functor",
                "signal.functor",
                "@seseragi/runtime/signal",
                "signalFunctor",
            ),
            (
                "std/signal::Applicative",
                "signal.applicative",
                "@seseragi/runtime/signal",
                "signalApplicative",
            ),
        ] {
            let dictionary = runtime_prelude_dictionary_for_feature(feature).unwrap();
            assert_eq!(dictionary.module, module);
            assert_eq!(dictionary.export_name, export_name);
            assert_eq!(dictionary.source_map_name, export_name);
            assert_eq!(
                runtime_prelude_dictionary_for_identity(identity),
                Some(dictionary)
            );
        }
    }

    #[test]
    fn rejects_unknown_prelude_dictionaries() {
        assert!(runtime_prelude_dictionary_for_feature("core.result.monad").is_none());
        assert!(runtime_prelude_dictionary_for_identity("fixture/local::Monad").is_none());
    }

    #[test]
    fn materializes_every_registered_special_standard_instance() {
        for instance in seseragi_semantics::special_standard_instances() {
            assert!(
                runtime_prelude_dictionary_for_identity(instance.identity).is_some(),
                "{} has no canonical runtime dictionary",
                instance.identity
            );
        }
    }
}
