use crate::runtime_modules::RuntimeDataOperation;

macro_rules! operation {
    ($canonical:literal, $feature:literal, $prefix:literal, $module:literal, $name:literal) => {
        RuntimeDataOperation {
            canonical: $canonical,
            runtime_feature: $feature,
            local_name: concat!("_ssrg_", $prefix, "_", $name),
            module: concat!("@seseragi/runtime/", $module),
            export_name: $name,
            source_map_name: $name,
        }
    };
}

const OPERATIONS: &[RuntimeDataOperation] = &[
    operation!(
        "std/text::InvalidUtf8",
        "core.text.invalid-utf8",
        "text",
        "text",
        "InvalidUtf8"
    ),
    operation!(
        "std/text::encodeUtf8",
        "core.text.encode-utf8",
        "text",
        "text",
        "encodeUtf8"
    ),
    operation!(
        "std/text::decodeUtf8",
        "core.text.decode-utf8",
        "text",
        "text",
        "decodeUtf8"
    ),
    operation!(
        "std/text::decodeUtf8Lossy",
        "core.text.decode-utf8-lossy",
        "text",
        "text",
        "decodeUtf8Lossy"
    ),
    operation!(
        "std/text::InvalidScalarRange",
        "core.text.invalid-scalar-range",
        "text",
        "text",
        "InvalidScalarRange"
    ),
    operation!(
        "std/text::isEmpty",
        "core.text.is-empty",
        "text",
        "text",
        "isEmpty"
    ),
    operation!(
        "std/text::lengthScalars",
        "core.text.length-scalars",
        "text",
        "text",
        "lengthScalars"
    ),
    operation!(
        "std/text::lengthBytes",
        "core.text.length-bytes",
        "text",
        "text",
        "lengthBytes"
    ),
    operation!(
        "std/text::concat",
        "core.text.concat",
        "text",
        "text",
        "concat"
    ),
    operation!("std/text::join", "core.text.join", "text", "text", "join"),
    operation!(
        "std/text::split",
        "core.text.split",
        "text",
        "text",
        "split"
    ),
    operation!(
        "std/text::lines",
        "core.text.lines",
        "text",
        "text",
        "lines"
    ),
    operation!(
        "std/text::words",
        "core.text.words",
        "text",
        "text",
        "words"
    ),
    operation!("std/text::trim", "core.text.trim", "text", "text", "trim"),
    operation!(
        "std/text::trimStart",
        "core.text.trim-start",
        "text",
        "text",
        "trimStart"
    ),
    operation!(
        "std/text::trimEnd",
        "core.text.trim-end",
        "text",
        "text",
        "trimEnd"
    ),
    operation!(
        "std/text::startsWith",
        "core.text.starts-with",
        "text",
        "text",
        "startsWith"
    ),
    operation!(
        "std/text::endsWith",
        "core.text.ends-with",
        "text",
        "text",
        "endsWith"
    ),
    operation!(
        "std/text::contains",
        "core.text.contains",
        "text",
        "text",
        "contains"
    ),
    operation!(
        "std/text::replace",
        "core.text.replace",
        "text",
        "text",
        "replace"
    ),
    operation!(
        "std/text::replaceAll",
        "core.text.replace-all",
        "text",
        "text",
        "replaceAll"
    ),
    operation!(
        "std/text::toLower",
        "core.text.to-lower",
        "text",
        "text",
        "toLower"
    ),
    operation!(
        "std/text::toUpper",
        "core.text.to-upper",
        "text",
        "text",
        "toUpper"
    ),
    operation!(
        "std/text::caseFold",
        "core.text.case-fold",
        "text",
        "text",
        "caseFold"
    ),
    operation!(
        "std/text::sliceScalars",
        "core.text.slice-scalars",
        "text",
        "text",
        "sliceScalars"
    ),
    operation!(
        "std/text::scalarAt",
        "core.text.scalar-at",
        "text",
        "text",
        "scalarAt"
    ),
    operation!(
        "std/char::codePoint",
        "core.char.code-point",
        "char",
        "char",
        "codePoint"
    ),
    operation!(
        "std/char::fromCodePoint",
        "core.char.from-code-point",
        "char",
        "char",
        "fromCodePoint"
    ),
    operation!(
        "std/char::toString",
        "core.char.to-string",
        "char",
        "char",
        "toString"
    ),
    operation!(
        "std/text/grapheme::InvalidGraphemeRange",
        "core.text.grapheme.invalid-grapheme-range",
        "grapheme",
        "grapheme",
        "InvalidGraphemeRange"
    ),
    operation!(
        "std/text/grapheme::length",
        "core.text.grapheme.length",
        "grapheme",
        "grapheme",
        "length"
    ),
    operation!(
        "std/text/grapheme::clusters",
        "core.text.grapheme.clusters",
        "grapheme",
        "grapheme",
        "clusters"
    ),
    operation!(
        "std/text/grapheme::byteBoundaries",
        "core.text.grapheme.byte-boundaries",
        "grapheme",
        "grapheme",
        "byteBoundaries"
    ),
    operation!(
        "std/text/grapheme::at",
        "core.text.grapheme.at",
        "grapheme",
        "grapheme",
        "at"
    ),
    operation!(
        "std/text/grapheme::slice",
        "core.text.grapheme.slice",
        "grapheme",
        "grapheme",
        "slice"
    ),
    operation!(
        "std/text/unicode::NFC",
        "core.text.unicode.nfc",
        "unicode",
        "unicode",
        "NFC"
    ),
    operation!(
        "std/text/unicode::NFD",
        "core.text.unicode.nfd",
        "unicode",
        "unicode",
        "NFD"
    ),
    operation!(
        "std/text/unicode::NFKC",
        "core.text.unicode.nfkc",
        "unicode",
        "unicode",
        "NFKC"
    ),
    operation!(
        "std/text/unicode::NFKD",
        "core.text.unicode.nfkd",
        "unicode",
        "unicode",
        "NFKD"
    ),
    operation!(
        "std/text/unicode::UppercaseLetter",
        "core.text.unicode.uppercase-letter",
        "unicode",
        "unicode",
        "UppercaseLetter"
    ),
    operation!(
        "std/text/unicode::LowercaseLetter",
        "core.text.unicode.lowercase-letter",
        "unicode",
        "unicode",
        "LowercaseLetter"
    ),
    operation!(
        "std/text/unicode::TitlecaseLetter",
        "core.text.unicode.titlecase-letter",
        "unicode",
        "unicode",
        "TitlecaseLetter"
    ),
    operation!(
        "std/text/unicode::ModifierLetter",
        "core.text.unicode.modifier-letter",
        "unicode",
        "unicode",
        "ModifierLetter"
    ),
    operation!(
        "std/text/unicode::OtherLetter",
        "core.text.unicode.other-letter",
        "unicode",
        "unicode",
        "OtherLetter"
    ),
    operation!(
        "std/text/unicode::NonspacingMark",
        "core.text.unicode.nonspacing-mark",
        "unicode",
        "unicode",
        "NonspacingMark"
    ),
    operation!(
        "std/text/unicode::SpacingMark",
        "core.text.unicode.spacing-mark",
        "unicode",
        "unicode",
        "SpacingMark"
    ),
    operation!(
        "std/text/unicode::EnclosingMark",
        "core.text.unicode.enclosing-mark",
        "unicode",
        "unicode",
        "EnclosingMark"
    ),
    operation!(
        "std/text/unicode::DecimalNumber",
        "core.text.unicode.decimal-number",
        "unicode",
        "unicode",
        "DecimalNumber"
    ),
    operation!(
        "std/text/unicode::LetterNumber",
        "core.text.unicode.letter-number",
        "unicode",
        "unicode",
        "LetterNumber"
    ),
    operation!(
        "std/text/unicode::OtherNumber",
        "core.text.unicode.other-number",
        "unicode",
        "unicode",
        "OtherNumber"
    ),
    operation!(
        "std/text/unicode::ConnectorPunctuation",
        "core.text.unicode.connector-punctuation",
        "unicode",
        "unicode",
        "ConnectorPunctuation"
    ),
    operation!(
        "std/text/unicode::DashPunctuation",
        "core.text.unicode.dash-punctuation",
        "unicode",
        "unicode",
        "DashPunctuation"
    ),
    operation!(
        "std/text/unicode::OpenPunctuation",
        "core.text.unicode.open-punctuation",
        "unicode",
        "unicode",
        "OpenPunctuation"
    ),
    operation!(
        "std/text/unicode::ClosePunctuation",
        "core.text.unicode.close-punctuation",
        "unicode",
        "unicode",
        "ClosePunctuation"
    ),
    operation!(
        "std/text/unicode::InitialPunctuation",
        "core.text.unicode.initial-punctuation",
        "unicode",
        "unicode",
        "InitialPunctuation"
    ),
    operation!(
        "std/text/unicode::FinalPunctuation",
        "core.text.unicode.final-punctuation",
        "unicode",
        "unicode",
        "FinalPunctuation"
    ),
    operation!(
        "std/text/unicode::OtherPunctuation",
        "core.text.unicode.other-punctuation",
        "unicode",
        "unicode",
        "OtherPunctuation"
    ),
    operation!(
        "std/text/unicode::MathSymbol",
        "core.text.unicode.math-symbol",
        "unicode",
        "unicode",
        "MathSymbol"
    ),
    operation!(
        "std/text/unicode::CurrencySymbol",
        "core.text.unicode.currency-symbol",
        "unicode",
        "unicode",
        "CurrencySymbol"
    ),
    operation!(
        "std/text/unicode::ModifierSymbol",
        "core.text.unicode.modifier-symbol",
        "unicode",
        "unicode",
        "ModifierSymbol"
    ),
    operation!(
        "std/text/unicode::OtherSymbol",
        "core.text.unicode.other-symbol",
        "unicode",
        "unicode",
        "OtherSymbol"
    ),
    operation!(
        "std/text/unicode::SpaceSeparator",
        "core.text.unicode.space-separator",
        "unicode",
        "unicode",
        "SpaceSeparator"
    ),
    operation!(
        "std/text/unicode::LineSeparator",
        "core.text.unicode.line-separator",
        "unicode",
        "unicode",
        "LineSeparator"
    ),
    operation!(
        "std/text/unicode::ParagraphSeparator",
        "core.text.unicode.paragraph-separator",
        "unicode",
        "unicode",
        "ParagraphSeparator"
    ),
    operation!(
        "std/text/unicode::Control",
        "core.text.unicode.control",
        "unicode",
        "unicode",
        "Control"
    ),
    operation!(
        "std/text/unicode::Format",
        "core.text.unicode.format",
        "unicode",
        "unicode",
        "Format"
    ),
    operation!(
        "std/text/unicode::PrivateUse",
        "core.text.unicode.private-use",
        "unicode",
        "unicode",
        "PrivateUse"
    ),
    operation!(
        "std/text/unicode::Unassigned",
        "core.text.unicode.unassigned",
        "unicode",
        "unicode",
        "Unassigned"
    ),
    operation!(
        "std/text/unicode::version",
        "core.text.unicode.version",
        "unicode",
        "unicode",
        "version"
    ),
    operation!(
        "std/text/unicode::normalize",
        "core.text.unicode.normalize",
        "unicode",
        "unicode",
        "normalize"
    ),
    operation!(
        "std/text/unicode::isNormalized",
        "core.text.unicode.is-normalized",
        "unicode",
        "unicode",
        "isNormalized"
    ),
    operation!(
        "std/text/unicode::generalCategory",
        "core.text.unicode.general-category",
        "unicode",
        "unicode",
        "generalCategory"
    ),
    operation!(
        "std/text/unicode::isAlphabetic",
        "core.text.unicode.is-alphabetic",
        "unicode",
        "unicode",
        "isAlphabetic"
    ),
    operation!(
        "std/text/unicode::isWhitespace",
        "core.text.unicode.is-whitespace",
        "unicode",
        "unicode",
        "isWhitespace"
    ),
    operation!(
        "std/text/unicode::isDecimalDigit",
        "core.text.unicode.is-decimal-digit",
        "unicode",
        "unicode",
        "isDecimalDigit"
    ),
    operation!(
        "std/text/unicode::isMark",
        "core.text.unicode.is-mark",
        "unicode",
        "unicode",
        "isMark"
    ),
    operation!(
        "std/text/unicode::simpleCaseFold",
        "core.text.unicode.simple-case-fold",
        "unicode",
        "unicode",
        "simpleCaseFold"
    ),
    operation!(
        "std/text/unicode::fullCaseFold",
        "core.text.unicode.full-case-fold",
        "unicode",
        "unicode",
        "fullCaseFold"
    ),
];

pub(crate) fn runtime_text_operation(canonical: &str) -> Option<RuntimeDataOperation> {
    OPERATIONS
        .iter()
        .copied()
        .find(|operation| operation.canonical == canonical)
}

pub(crate) fn runtime_text_operation_for_feature(feature: &str) -> Option<RuntimeDataOperation> {
    OPERATIONS
        .iter()
        .copied()
        .find(|operation| operation.runtime_feature == feature)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn maps_all_text_operations_only_by_canonical_identity() {
        for operation in OPERATIONS {
            assert_eq!(
                runtime_text_operation(operation.canonical),
                Some(*operation)
            );
            assert_eq!(
                runtime_text_operation_for_feature(operation.runtime_feature),
                Some(*operation)
            );
        }
        for shadow in [
            "text::trim",
            "app/unicode::normalize",
            "std/regex::compile",
            "std/bytes/hex::encode",
        ] {
            assert!(runtime_text_operation(shadow).is_none());
        }
    }
}
