[package]
name = "docs/modules-example"
version = "0.0.0"
language = ">=0.1.0 <0.2.0"

[run]
entry = "main"
target = "process"

[dependencies]
"docs/greetings" = { package = "docs/greetings", path = "../greetings-library" }
