import { add as _ssrg_int64_add } from "@seseragi/runtime/int64"
import { flatMap as _ssrg_effect_flatMap, type Effect as Effect } from "@seseragi/runtime/effect"
import { make as _ssrg_signal_make, map as _ssrg_signal_map, combine as _ssrg_signal_combine, planSet as _ssrg_signal_planSet, planUpdate as _ssrg_signal_planUpdate, set as _ssrg_signal_set, transaction as _ssrg_signal_transaction, read as _ssrg_signal_read, type MutableSignal as MutableSignal, type Signal as Signal, type SignalChange as SignalChange } from "@seseragi/runtime/signal"
import { println as _ssrg_console_println } from "@seseragi/runtime/console"
import { intShow as _ssrg_show_intShow } from "@seseragi/runtime/show"

const twice = (value: bigint) => _ssrg_int64_add(value, value)
const add = (left: bigint) => (right: bigint) => _ssrg_int64_add(left, right)
export const main = (_unit: undefined) => _ssrg_effect_flatMap(_ssrg_signal_make<bigint>(20n), (left: MutableSignal<bigint>) => _ssrg_effect_flatMap(_ssrg_signal_make<bigint>(1n), (right: MutableSignal<bigint>) => (() => { const doubled: Signal<bigint> = _ssrg_signal_map(twice, left); return (() => { const total: Signal<bigint> = _ssrg_signal_combine(add, doubled, right); return (() => { const setLeft: (argument: MutableSignal<bigint>) => SignalChange = _ssrg_signal_planSet(21n); return (() => { const updateRight: (argument: MutableSignal<bigint>) => SignalChange = _ssrg_signal_planUpdate((value: bigint) => _ssrg_int64_add(value, 20n)); return _ssrg_effect_flatMap(_ssrg_signal_set(10n, left), () => _ssrg_effect_flatMap(_ssrg_signal_transaction([setLeft(left), updateRight(right)]), () => _ssrg_effect_flatMap(_ssrg_signal_read(total), (current: bigint) => _ssrg_console_println("signal: " + _ssrg_show_intShow["show"](current))))); })(); })(); })(); })()))
