import { mkdir, readFile, writeFile } from "node:fs/promises"
import { relative, resolve, sep } from "node:path"
import { loadValidatedTourCurriculum } from "./tour-curriculum"
import { repositoryPath } from "./tour-lessons"

const repositoryRoot = resolve(import.meta.dir, "..")
const outputPath = resolve(
  repositoryRoot,
  "apps/playground/src/generated/tour-manifest.ts"
)
const checkOnly = process.argv.includes("--check")
const { lessons } = await loadValidatedTourCurriculum(repositoryRoot)

const imports = [
  'import type { GeneratedTourLessonContent, TourLessonFormat } from "../tour/content"',
  "",
]
const records: string[] = []
for (const [index, lesson] of lessons.entries()) {
  const sourceImport = importName(index, "source")
  const guideImport = lesson.guidePath ? importName(index, "guide") : undefined
  const stdinImport = lesson.stdinPath ? importName(index, "stdin") : undefined
  const outputImport = lesson.expectedOutputPath
    ? importName(index, "output")
    : undefined
  const exerciseImport = lesson.exercisePath
    ? importName(index, "exercise")
    : undefined
  const exerciseOutputImport = lesson.exerciseExpectedOutputPath
    ? importName(index, "exerciseOutput")
    : undefined
  const diagnosticImport = lesson.diagnosticExamplePath
    ? importName(index, "diagnostic")
    : undefined
  const diagnosticOutputImport = lesson.diagnosticOutputPath
    ? importName(index, "diagnosticOutput")
    : undefined
  imports.push(renderImport(sourceImport, lesson.sourcePath))
  if (guideImport && lesson.guidePath) {
    imports.push(renderImport(guideImport, lesson.guidePath))
  }
  if (stdinImport && lesson.stdinPath) {
    imports.push(renderImport(stdinImport, lesson.stdinPath))
  }
  if (outputImport && lesson.expectedOutputPath) {
    imports.push(renderImport(outputImport, lesson.expectedOutputPath))
  }
  if (exerciseImport && lesson.exercisePath) {
    imports.push(renderImport(exerciseImport, lesson.exercisePath))
  }
  if (exerciseOutputImport && lesson.exerciseExpectedOutputPath) {
    imports.push(
      renderImport(exerciseOutputImport, lesson.exerciseExpectedOutputPath)
    )
  }
  if (diagnosticImport && lesson.diagnosticExamplePath) {
    imports.push(renderImport(diagnosticImport, lesson.diagnosticExamplePath))
  }
  if (diagnosticOutputImport && lesson.diagnosticOutputPath) {
    imports.push(
      renderImport(diagnosticOutputImport, lesson.diagnosticOutputPath)
    )
  }
  if (index < lessons.length - 1) imports.push("")
  records.push(
    [
      "  {",
      `    id: ${JSON.stringify(lesson.metadata.id)},`,
      `    challenge: ${JSON.stringify(lesson.metadata.challenge ?? "")},`,
      `    interactive: ${lesson.metadata.interactive},`,
      `    sourcePath: ${JSON.stringify(repositoryPath(repositoryRoot, lesson.sourcePath))},`,
      `    source: ${sourceImport},`,
      `    guide: ${guideImport ?? '""'},`,
      `    stdin: ${stdinImport ?? '""'},`,
      `    expectedOutput: (${outputImport ?? '""'}).replace(/\\r?\\n$/u, ""),`,
      ...(lesson.metadata.format
        ? [
            `    format: ${renderJson(lesson.metadata.format, 4)} as unknown as TourLessonFormat,`,
          ]
        : []),
      `    exerciseSource: ${exerciseImport ?? '""'},`,
      `    exerciseExpectedOutput: (${exerciseOutputImport ?? '""'}).replace(/\\r?\\n$/u, ""),`,
      `    diagnosticSource: ${diagnosticImport ?? '""'},`,
      `    diagnosticOutput: (${diagnosticOutputImport ?? '""'}).replace(/\\r?\\n$/u, ""),`,
      "  }",
    ].join("\n")
  )
}

const generated = [
  "// Generated by scripts/generate-playground-tour.ts. Do not edit.",
  "// biome-ignore-all lint/suspicious/noTemplateCurlyInString: Tour prose documents literal Seseragi interpolation.",
  ...imports,
  "",
  "export const generatedTourLessons: readonly GeneratedTourLessonContent[] = [",
  records.join(",\n"),
  "]",
  "",
].join("\n")

if (checkOnly) {
  const current = await readFile(outputPath, "utf8").catch(() => "")
  if (current !== generated) {
    throw new Error(
      "Playground Tour manifest is stale. Run `bun run tour:generate` in apps/playground."
    )
  }
  console.log(`Validated ${lessons.length} canonical Tour lessons.`)
} else {
  await mkdir(resolve(outputPath, ".."), { recursive: true })
  await writeFile(outputPath, generated)
  console.log(
    `Generated ${repositoryPath(repositoryRoot, outputPath)} (${lessons.length} Tour lessons).`
  )
}

function renderImport(name: string, repositoryFile: string): string {
  const relativeFile = relative(
    resolve(outputPath, ".."),
    resolve(repositoryRoot, repositoryFile)
  )
    .split(sep)
    .join("/")
  const specifier = relativeFile.startsWith(".")
    ? relativeFile
    : `./${relativeFile}`
  return `import ${name} from ${JSON.stringify(`${specifier}?raw`)}`
}

function importName(index: number, role: string): string {
  return `lesson${index}${role[0]?.toUpperCase()}${role.slice(1)}`
}

function renderJson(value: unknown, indentation: number): string {
  return JSON.stringify(value, null, 2).replaceAll(
    "\n",
    `\n${" ".repeat(indentation)}`
  )
}
