import { mkdir, readFile, writeFile } from "node:fs/promises"
import { relative, resolve, sep } from "node:path"
import { loadValidatedTourCurriculum } from "./tour-curriculum"
import { repositoryPath } from "./tour-lessons"

const repositoryRoot = resolve(import.meta.dir, "..")
const outputPath = resolve(
  repositoryRoot,
  "apps/playground/src/generated/tour-manifest.ts"
)
const checkOnly = process.argv.includes("--check")
const { lessons } = await loadValidatedTourCurriculum(repositoryRoot)

const imports = [
  'import type { GeneratedTourLessonContent } from "../tour/content"',
  "",
]
const records: string[] = []
for (const [index, lesson] of lessons.entries()) {
  const sourceImport = importName(index, "source")
  const guideImport = importName(index, "guide")
  const stdinImport = lesson.stdinPath ? importName(index, "stdin") : undefined
  const outputImport = lesson.expectedOutputPath
    ? importName(index, "output")
    : undefined
  imports.push(renderImport(sourceImport, lesson.sourcePath))
  imports.push(renderImport(guideImport, lesson.guidePath))
  if (stdinImport && lesson.stdinPath) {
    imports.push(renderImport(stdinImport, lesson.stdinPath))
  }
  if (outputImport && lesson.expectedOutputPath) {
    imports.push(renderImport(outputImport, lesson.expectedOutputPath))
  }
  if (index < lessons.length - 1) imports.push("")
  records.push(
    [
      "  {",
      `    id: ${JSON.stringify(lesson.metadata.id)},`,
      `    challenge: ${JSON.stringify(lesson.metadata.challenge)},`,
      `    interactive: ${lesson.metadata.interactive},`,
      `    sourcePath: ${JSON.stringify(repositoryPath(repositoryRoot, lesson.sourcePath))},`,
      `    source: ${sourceImport},`,
      `    guide: ${guideImport},`,
      `    stdin: ${stdinImport ?? '""'},`,
      `    expectedOutput: (${outputImport ?? '""'}).replace(/\\r?\\n$/u, ""),`,
      "  }",
    ].join("\n")
  )
}

const generated = [
  "// Generated by scripts/generate-playground-tour.ts. Do not edit.",
  ...imports,
  "",
  "export const generatedTourLessons: readonly GeneratedTourLessonContent[] = [",
  records.join(",\n"),
  "]",
  "",
].join("\n")

if (checkOnly) {
  const current = await readFile(outputPath, "utf8").catch(() => "")
  if (current !== generated) {
    throw new Error(
      "Playground Tour manifest is stale. Run `bun run tour:generate` in apps/playground."
    )
  }
  console.log(`Validated ${lessons.length} canonical Tour lessons.`)
} else {
  await mkdir(resolve(outputPath, ".."), { recursive: true })
  await writeFile(outputPath, generated)
  console.log(
    `Generated ${repositoryPath(repositoryRoot, outputPath)} (${lessons.length} Tour lessons).`
  )
}

function renderImport(name: string, repositoryFile: string): string {
  const relativeFile = relative(
    resolve(outputPath, ".."),
    resolve(repositoryRoot, repositoryFile)
  )
    .split(sep)
    .join("/")
  const specifier = relativeFile.startsWith(".")
    ? relativeFile
    : `./${relativeFile}`
  return `import ${name} from ${JSON.stringify(`${specifier}?raw`)}`
}

function importName(index: number, role: string): string {
  return `lesson${index}${role[0]?.toUpperCase()}${role.slice(1)}`
}
