import { mkdir, readFile, writeFile } from "node:fs/promises"
import { resolve } from "node:path"
import { loadValidatedDeepDive } from "./deep-dive"

const repositoryRoot = resolve(import.meta.dir, "..")
const outputPath = resolve(
  repositoryRoot,
  "apps/playground/src/generated/deep-dive-manifest.ts"
)
const checkOnly = process.argv.includes("--check")
const { catalog, articles } = await loadValidatedDeepDive(repositoryRoot)

const serializedCatalog = JSON.stringify(
  {
    title: catalog.title,
    categories: catalog.categories.map((category) => ({
      id: category.id,
      order: category.order,
      title: category.title,
      summary: category.summary,
      chapters: category.chapters.map((chapter) => ({
        id: chapter.id,
        order: chapter.order,
        title: chapter.title,
        summary: chapter.summary,
        articles: chapter.articles.map((reference) => {
          const loaded = articles.find(
            ({ content }) => content.id === reference.id
          )!
          return {
            order: reference.order,
            ...loaded.content,
          }
        }),
      })),
    })),
  },
  null,
  2
)
  .replaceAll("\\", "\\\\")
  .replaceAll("`", "\\`")
  .replaceAll("${", "\\${")

const generated = [
  "// Generated by scripts/generate-playground-deep-dive.ts. Do not edit.",
  "// biome-ignore-all lint/suspicious/noTemplateCurlyInString: Deep Dive prose may document literal interpolation.",
  'import type { DeepDiveCatalogData } from "../deep-dive/catalog"',
  "",
  `export const generatedDeepDive = JSON.parse(\`${serializedCatalog}\`) as DeepDiveCatalogData`,
  "",
].join("\n")

if (checkOnly) {
  const current = await readFile(outputPath, "utf8").catch(() => "")
  if (current !== generated) {
    throw new Error(
      "Playground Deep Dive manifest is stale. Run `bun run deep-dive:generate` in apps/playground."
    )
  }
  console.log(`Validated ${articles.length} canonical Deep Dive article(s).`)
} else {
  await mkdir(resolve(outputPath, ".."), { recursive: true })
  await writeFile(outputPath, generated)
  console.log(
    `Generated ${outputPath} (${articles.length} Deep Dive article(s)).`
  )
}
