import { readFile, writeFile } from "node:fs/promises"
import { relative, resolve } from "node:path"

const root = resolve(import.meta.dir, "..")
export const runtimeRegistryPath = resolve(
  root,
  "apps/playground/src/runtime/runtime-modules.ts"
)

type ExportTarget = Readonly<{
  default: string
  browser?: string | null
}>

export type RuntimePackage = Readonly<{
  name: string
  exports: Readonly<Record<string, ExportTarget>>
}>

export type BrowserRuntimeEntry = Readonly<{
  specifier: string
  source: string
}>

// Public module identities belong to the package manifests, not Playground.
// Native-only exports opt out with browser: null; host adapters select their
// browser implementation using the same condition consumed by browser bundlers.
export function browserRuntimeEntries(
  runtime: RuntimePackage,
  providers: RuntimePackage
): BrowserRuntimeEntry[] {
  const entries: BrowserRuntimeEntry[] = []
  for (const [name, target] of Object.entries(runtime.exports)) {
    const source =
      target.browser === undefined ? target.default : target.browser
    if (source === null) continue
    if (!source.startsWith("./src/") || source.includes("..", 2)) {
      throw new Error(`invalid runtime export source: ${name} -> ${source}`)
    }
    entries.push({
      specifier: runtime.name + (name === "." ? "" : name.slice(1)),
      source: `runtime/ts/${source.slice(2)}`,
    })
  }
  for (const [name, target] of Object.entries(providers.exports)) {
    // This is the canonical provider package's target namespace. Process/DB
    // provider exports must never become browser resolver candidates.
    if (!name.startsWith("./runtime-browser/")) continue
    if (target.default !== `${name}.ts` || name.includes("..", 2)) {
      throw new Error(`invalid browser provider export source: ${name}`)
    }
    entries.push({
      specifier: providers.name + name.slice(1),
      // The native package stager projects browser/ to runtime-browser/.
      // No per-provider filename mapping is owned by Playground.
      source: `runtime/providers/browser/${name.slice(18)}.ts`,
    })
  }
  return entries.sort((left, right) =>
    left.specifier.localeCompare(right.specifier, "en")
  )
}

export function renderRuntimeRegistry(entries: readonly BrowserRuntimeEntry[]) {
  const sources = [...new Set(entries.map(({ source }) => source))].sort(
    (left, right) =>
      left
        .replace(/\.[^.]+$/u, "")
        .localeCompare(right.replace(/\.[^.]+$/u, ""), "en")
  )
  const imports = sources.map((path, index) => {
    const source = relative(
      resolve(root, "apps/playground/src/runtime"),
      resolve(root, path)
    ).replaceAll("\\", "/")
    return `import * as module${index} from ${JSON.stringify(source)}`
  })
  const members = entries.map(
    (entry) =>
      `  ${JSON.stringify(entry.specifier)}: module${sources.indexOf(entry.source)},`
  )
  return [
    "// Generated by scripts/generate-playground-runtime.ts; do not edit.",
    "// Sources: runtime/ts/package.json and runtime/providers/package.json.",
    "",
    ...imports,
    "",
    "export const runtimeModules: Readonly<Record<string, unknown>> = {",
    ...members,
    "}",
    "",
  ].join("\n")
}

export async function loadBrowserRuntimeEntries() {
  const load = async (path: string): Promise<RuntimePackage> =>
    JSON.parse(await readFile(resolve(root, path), "utf8"))
  return browserRuntimeEntries(
    await load("runtime/ts/package.json"),
    await load("runtime/providers/package.json")
  )
}

export function assertBrowserRuntimeCoverage(
  entries: readonly BrowserRuntimeEntry[],
  modules: Readonly<Record<string, unknown>>
) {
  const expected = entries.map(({ specifier }) => specifier).sort()
  const actual = Object.keys(modules).sort()
  if (JSON.stringify(expected) !== JSON.stringify(actual)) {
    throw new Error(
      "Playground runtime registry drift; run bun run --cwd apps/playground runtime:generate"
    )
  }
}

if (import.meta.main) {
  const entries = await loadBrowserRuntimeEntries()
  // Fail at generation time rather than emitting imports to missing files.
  await Promise.all(
    entries.map(({ source }) => readFile(resolve(root, source)))
  )
  const output = renderRuntimeRegistry(entries)
  if (process.argv.includes("--check")) {
    if ((await readFile(runtimeRegistryPath, "utf8")) !== output) {
      throw new Error(
        "Playground runtime registry is stale; run bun run --cwd apps/playground runtime:generate"
      )
    }
    console.log(
      `Playground runtime registry is current (${entries.length} modules).`
    )
  } else {
    await writeFile(runtimeRegistryPath, output)
    console.log(
      `Generated Playground runtime registry (${entries.length} modules).`
    )
  }
}
