import { Left as _ssrg_either_Left, Right as _ssrg_either_Right } from "@seseragi/runtime/sum"
import { add as _ssrg_int64_add } from "@seseragi/runtime/int64"
import { flatMap as _ssrg_effect_flatMap } from "@seseragi/runtime/effect"
import { println as _ssrg_console_println } from "@seseragi/runtime/console"

export const __ssrg$instance$Functor$0 = <E,>() => ({ "map": <A, B,>(f: (argument: A) => B) => (value: { readonly tag: "Left"; readonly value: E } | { readonly tag: "Right"; readonly value: A }) => (($ssrg_match: { readonly tag: "Left"; readonly value: E } | { readonly tag: "Right"; readonly value: A }): { readonly tag: "Left"; readonly value: E } | { readonly tag: "Right"; readonly value: B } => $ssrg_match.tag === "Left" ? ((error: E): { readonly tag: "Left"; readonly value: E } | { readonly tag: "Right"; readonly value: B } => _ssrg_either_Left(error))($ssrg_match.value) : $ssrg_match.tag === "Right" ? ((item: A): { readonly tag: "Left"; readonly value: E } | { readonly tag: "Right"; readonly value: B } => _ssrg_either_Right(f(item)))($ssrg_match.value) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(value) }) as const;
export const __ssrg$instance$Applicative$1 = <E,>(__ssrg$evidence$0: Readonly<Record<string, (...args: any[]) => any>>) => ({ ...__ssrg$evidence$0, "pure": <A,>(value: A) => _ssrg_either_Right(value), "apply": <A, B,>(wrapped: { readonly tag: "Left"; readonly value: E } | { readonly tag: "Right"; readonly value: (argument: A) => B }) => (value: { readonly tag: "Left"; readonly value: E } | { readonly tag: "Right"; readonly value: A }) => (($ssrg_match: readonly [{ readonly tag: "Left"; readonly value: E } | { readonly tag: "Right"; readonly value: (argument: A) => B }, { readonly tag: "Left"; readonly value: E } | { readonly tag: "Right"; readonly value: A }]): { readonly tag: "Left"; readonly value: E } | { readonly tag: "Right"; readonly value: B } => $ssrg_match[0].tag === "Right" && $ssrg_match[1].tag === "Right" ? ((_function: (argument: A) => B, item: A): { readonly tag: "Left"; readonly value: E } | { readonly tag: "Right"; readonly value: B } => _ssrg_either_Right(_function(item)))($ssrg_match[0].value, $ssrg_match[1].value) : $ssrg_match[0].tag === "Left" ? ((error: E): { readonly tag: "Left"; readonly value: E } | { readonly tag: "Right"; readonly value: B } => _ssrg_either_Left(error))($ssrg_match[0].value) : $ssrg_match[1].tag === "Left" ? ((error: E): { readonly tag: "Left"; readonly value: E } | { readonly tag: "Right"; readonly value: B } => _ssrg_either_Left(error))($ssrg_match[1].value) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())([wrapped, value] as const) }) as const;
export const __ssrg$instance$Monad$2 = <E,>(__ssrg$evidence$0: Readonly<Record<string, (...args: any[]) => any>>) => ({ ...__ssrg$evidence$0, "flatMap": <A, B,>(f: (argument: A) => { readonly tag: "Left"; readonly value: E } | { readonly tag: "Right"; readonly value: B }) => (value: { readonly tag: "Left"; readonly value: E } | { readonly tag: "Right"; readonly value: A }) => (($ssrg_match: { readonly tag: "Left"; readonly value: E } | { readonly tag: "Right"; readonly value: A }): { readonly tag: "Left"; readonly value: E } | { readonly tag: "Right"; readonly value: B } => $ssrg_match.tag === "Left" ? ((error: E): { readonly tag: "Left"; readonly value: E } | { readonly tag: "Right"; readonly value: B } => _ssrg_either_Left(error))($ssrg_match.value) : $ssrg_match.tag === "Right" ? ((item: A): { readonly tag: "Left"; readonly value: E } | { readonly tag: "Right"; readonly value: B } => f(item))($ssrg_match.value) : ((): never => { throw new Error("non-exhaustive Seseragi match"); })())(value) }) as const;
const addEither = (left: { readonly tag: "Left"; readonly value: string } | { readonly tag: "Right"; readonly value: bigint }) => (right: { readonly tag: "Left"; readonly value: string } | { readonly tag: "Right"; readonly value: bigint }) => __ssrg$instance$Monad$2<string>(__ssrg$instance$Applicative$1<string>(__ssrg$instance$Functor$0<string>()))["flatMap"]((first: bigint) => __ssrg$instance$Monad$2<string>(__ssrg$instance$Applicative$1<string>(__ssrg$instance$Functor$0<string>()))["flatMap"]((second: bigint) => __ssrg$instance$Applicative$1<string>(__ssrg$instance$Functor$0<string>())["pure"](_ssrg_int64_add(first, second)))(right))(left)
const addEitherExplicit = (left: { readonly tag: "Left"; readonly value: string } | { readonly tag: "Right"; readonly value: bigint }) => (right: { readonly tag: "Left"; readonly value: string } | { readonly tag: "Right"; readonly value: bigint }) => __ssrg$instance$Monad$2<string>(__ssrg$instance$Applicative$1<string>(__ssrg$instance$Functor$0<string>()))["flatMap"]((first: bigint) => __ssrg$instance$Monad$2<string>(__ssrg$instance$Applicative$1<string>(__ssrg$instance$Functor$0<string>()))["flatMap"]((second: bigint) => __ssrg$instance$Applicative$1<string>(__ssrg$instance$Functor$0<string>())["pure"](_ssrg_int64_add(first, second)))(right))(left)
const render = (value: { readonly tag: "Left"; readonly value: string } | { readonly tag: "Right"; readonly value: bigint }) => (($ssrg_match: { readonly tag: "Left"; readonly value: string } | { readonly tag: "Right"; readonly value: bigint }): string => $ssrg_match.tag === "Left" ? ((error: string): string => "Left " + error)($ssrg_match.value) : $ssrg_match.tag === "Right" && $ssrg_match.value === 42n ? "Right 42" : "Right another value")(value)
export const main = (_unit: undefined) => _ssrg_effect_flatMap(_ssrg_console_println(render(addEither(_ssrg_either_Right(20n))(_ssrg_either_Right(22n)))), () => _ssrg_effect_flatMap(_ssrg_console_println(render(addEitherExplicit(_ssrg_either_Right(20n))(_ssrg_either_Right(22n)))), () => _ssrg_effect_flatMap(_ssrg_console_println(render(addEither(_ssrg_either_Left("stopped"))(_ssrg_either_Right(22n)))), () => _ssrg_console_println(render(addEitherExplicit(_ssrg_either_Left("stopped"))(_ssrg_either_Right(22n)))))))
