import { eitherMonad as _ssrg_either_monad, eitherApplicative as _ssrg_either_applicative, Right as _ssrg_either_Right, Left as _ssrg_either_Left } from "@seseragi/runtime/sum"
import { add as _ssrg_int64_add } from "@seseragi/runtime/int64"
import { flatMap as _ssrg_effect_flatMap } from "@seseragi/runtime/effect"
import { println as _ssrg_console_println } from "@seseragi/runtime/console"

const addEither = (left: { readonly tag: "Left"; readonly value: string } | { readonly tag: "Right"; readonly value: bigint }) => (right: { readonly tag: "Left"; readonly value: string } | { readonly tag: "Right"; readonly value: bigint }) => _ssrg_either_monad["flatMap"]((first: bigint) => _ssrg_either_monad["flatMap"]((second: bigint) => _ssrg_either_applicative["pure"](_ssrg_int64_add(first, second)))(right))(left)
const addEitherExplicit = (left: { readonly tag: "Left"; readonly value: string } | { readonly tag: "Right"; readonly value: bigint }) => (right: { readonly tag: "Left"; readonly value: string } | { readonly tag: "Right"; readonly value: bigint }) => _ssrg_either_monad["flatMap"]((first: bigint) => _ssrg_either_monad["flatMap"]((second: bigint) => _ssrg_either_applicative["pure"](_ssrg_int64_add(first, second)))(right))(left)
const render = (value: { readonly tag: "Left"; readonly value: string } | { readonly tag: "Right"; readonly value: bigint }) => (($ssrg_match: { readonly tag: "Left"; readonly value: string } | { readonly tag: "Right"; readonly value: bigint }): string => $ssrg_match.tag === "Left" ? ((error: string): string => "Left " + error)($ssrg_match.value) : $ssrg_match.tag === "Right" && $ssrg_match.value === 42n ? "Right 42" : "Right another value")(value)
export const main = (_unit: undefined) => _ssrg_effect_flatMap(_ssrg_console_println(render(addEither(_ssrg_either_Right(20n))(_ssrg_either_Right(22n)))), () => _ssrg_effect_flatMap(_ssrg_console_println(render(addEitherExplicit(_ssrg_either_Right(20n))(_ssrg_either_Right(22n)))), () => _ssrg_effect_flatMap(_ssrg_console_println(render(addEither(_ssrg_either_Left("stopped"))(_ssrg_either_Right(22n)))), () => _ssrg_console_println(render(addEitherExplicit(_ssrg_either_Left("stopped"))(_ssrg_either_Right(22n)))))))
