import { assertUnicodeVersion as $ssrg$assertUnicodeVersion } from "@seseragi/runtime/unicode-version"
import { intEq as _ssrg_int_eq_dictionary, intOrd as _ssrg_int_ord_dictionary, boolOrd as _ssrg_bool_ord_dictionary, unitOrd as _ssrg_unit_ord_dictionary, stringOrd as _ssrg_string_ord_dictionary } from "@seseragi/runtime/equality"
import { add as _ssrg_int_add } from "@seseragi/runtime/int"
import { flatMap as _ssrg_effect_flatMap } from "@seseragi/runtime/effect"
import { println as _ssrg_console_println } from "@seseragi/runtime/console"
import { boolShow as _ssrg_show_boolShow, tupleShow as _ssrg_show_tupleShow } from "@seseragi/runtime/show"
$ssrg$assertUnicodeVersion("17.0.0")

declare const __ssrg$brand$Score: unique symbol;
type Score = {
  readonly "value": number;
  readonly [__ssrg$brand$Score]: true;
};
export const __ssrg$instance$Eq$0 = { "eq": (left: Score) => (right: Score) => _ssrg_int_eq_dictionary["eq"]((left)["value"])((right)["value"]) } as const;
export const __ssrg$instance$Ord$1 = (__ssrg$evidence$0: Readonly<Record<string, (...args: any[]) => any>>) => ({ ...__ssrg$evidence$0, "compare": (left: Score) => (right: Score) => _ssrg_int_ord_dictionary["compare"]((right)["value"])((left)["value"]) }) as const;
const ordered = <A,>(left: A) => (right: A) => (__ssrg$evidence$0: Readonly<Record<string, (...args: any[]) => any>>) => (__ssrg$evidence$0["compare"](left)(right))["tag"] !== "Greater"
const referenced = <A,>(left: A) => (right: A) => (__ssrg$evidence$0: Readonly<Record<string, (...args: any[]) => any>>) => (__ssrg$evidence$0["compare"](left)(right))["tag"] !== "Less"
const apply = <A,>(f: (argument: A) => (argument: A) => boolean) => (left: A) => (right: A) => f(left)(right)
const arithmeticApply = <A,>(f: (argument: A) => (argument: A) => A) => (left: A) => (right: A) => f(left)(right)
const arithmeticReference = (unit: undefined) => (((_argument0) => (_argument1) => _ssrg_int_add(_argument0, _argument1)) as (argument: number) => (argument: number) => number)
const equalityReference = (unit: undefined) => (((_argument0) => (_argument1) => __ssrg$instance$Eq$0["eq"](_argument0)(_argument1)) as (argument: Score) => (argument: Score) => boolean)
const partial = (left: Score) => (((__ssrg$comparison$argument$1) => (__ssrg$instance$Ord$1(__ssrg$instance$Eq$0)["compare"](left)(__ssrg$comparison$argument$1))["tag"] !== "Greater") as (argument: Score) => boolean)
const reference = (unit: undefined) => (((__ssrg$comparison$left) => (__ssrg$comparison$right) => (__ssrg$instance$Ord$1(__ssrg$instance$Eq$0)["compare"](__ssrg$comparison$left)(__ssrg$comparison$right))["tag"] === "Less") as (argument: Score) => (argument: Score) => boolean)
const section = (unit: undefined) => (() => { const returnedPartial: (argument: Score) => boolean = partial((({ "value": 2 } as const) as unknown as Score)); return (() => { const returnedComparison: (argument: Score) => (argument: Score) => boolean = reference(undefined); return (() => { const returnedEquality: (argument: Score) => (argument: Score) => boolean = equalityReference(undefined); return (() => { const returnedArithmetic: (argument: number) => (argument: number) => number = arithmeticReference(undefined); return (() => { const less: (argument: Score) => (argument: Score) => boolean = (((__ssrg$comparison$left) => (__ssrg$comparison$right) => (__ssrg$instance$Ord$1(__ssrg$instance$Eq$0)["compare"](__ssrg$comparison$left)(__ssrg$comparison$right))["tag"] === "Less") as (argument: Score) => (argument: Score) => boolean); return (() => { const greater: (argument: Score) => boolean = (((__ssrg$comparison$argument$1) => (__ssrg$instance$Ord$1(__ssrg$instance$Eq$0)["compare"]((({ "value": 1 } as const) as unknown as Score))(__ssrg$comparison$argument$1))["tag"] === "Greater") as (argument: Score) => boolean); return (((((((less((({ "value": 2 } as const) as unknown as Score))((({ "value": 1 } as const) as unknown as Score)) ? greater((({ "value": 2 } as const) as unknown as Score)) : false) ? apply((((__ssrg$comparison$left) => (__ssrg$comparison$right) => (__ssrg$instance$Ord$1(__ssrg$instance$Eq$0)["compare"](__ssrg$comparison$left)(__ssrg$comparison$right))["tag"] === "Less") as (argument: Score) => (argument: Score) => boolean))((({ "value": 2 } as const) as unknown as Score))((({ "value": 1 } as const) as unknown as Score)) : false) ? returnedPartial((({ "value": 1 } as const) as unknown as Score)) : false) ? returnedComparison((({ "value": 2 } as const) as unknown as Score))((({ "value": 1 } as const) as unknown as Score)) : false) ? apply((((_argument0) => (_argument1) => __ssrg$instance$Eq$0["eq"](_argument0)(_argument1)) as (argument: Score) => (argument: Score) => boolean))((({ "value": 2 } as const) as unknown as Score))((({ "value": 2 } as const) as unknown as Score)) : false) ? returnedEquality((({ "value": 2 } as const) as unknown as Score))((({ "value": 2 } as const) as unknown as Score)) : false) ? _ssrg_int_eq_dictionary["eq"](arithmeticApply((((_argument0) => (_argument1) => _ssrg_int_add(_argument0, _argument1)) as (argument: number) => (argument: number) => number))(1)(2))(3) : false) ? _ssrg_int_eq_dictionary["eq"](returnedArithmetic(1)(2))(3) : false; })(); })(); })(); })(); })(); })()
export const main = (_unit: undefined) => (() => { const low: Score = (({ "value": 2 } as const) as unknown as Score); return (() => { const high: Score = (({ "value": 1 } as const) as unknown as Score); return _ssrg_effect_flatMap(_ssrg_console_println(_ssrg_show_tupleShow<readonly [boolean, boolean, boolean, boolean]>(_ssrg_show_boolShow, _ssrg_show_boolShow, _ssrg_show_boolShow, _ssrg_show_boolShow)["show"]([(__ssrg$instance$Ord$1(__ssrg$instance$Eq$0)["compare"](low)(high))["tag"] === "Less", (__ssrg$instance$Ord$1(__ssrg$instance$Eq$0)["compare"](low)(high))["tag"] !== "Greater", (__ssrg$instance$Ord$1(__ssrg$instance$Eq$0)["compare"](high)(low))["tag"] === "Greater", (__ssrg$instance$Ord$1(__ssrg$instance$Eq$0)["compare"](high)(low))["tag"] !== "Less"] as const)), () => _ssrg_effect_flatMap(_ssrg_console_println(_ssrg_show_tupleShow<readonly [boolean, boolean, boolean, boolean]>(_ssrg_show_boolShow, _ssrg_show_boolShow, _ssrg_show_boolShow, _ssrg_show_boolShow)["show"]([(__ssrg$instance$Ord$1(__ssrg$instance$Eq$0)["compare"](low)(low))["tag"] === "Less", (__ssrg$instance$Ord$1(__ssrg$instance$Eq$0)["compare"](low)(low))["tag"] !== "Greater", (__ssrg$instance$Ord$1(__ssrg$instance$Eq$0)["compare"](low)(low))["tag"] === "Greater", (__ssrg$instance$Ord$1(__ssrg$instance$Eq$0)["compare"](low)(low))["tag"] !== "Less"] as const)), () => _ssrg_effect_flatMap(_ssrg_console_println(_ssrg_show_tupleShow<readonly [boolean, boolean, boolean, boolean]>(_ssrg_show_boolShow, _ssrg_show_boolShow, _ssrg_show_boolShow, _ssrg_show_boolShow)["show"]([(__ssrg$instance$Ord$1(__ssrg$instance$Eq$0)["compare"](low)(high))["tag"] === "Greater", (__ssrg$instance$Ord$1(__ssrg$instance$Eq$0)["compare"](low)(high))["tag"] !== "Less", (__ssrg$instance$Ord$1(__ssrg$instance$Eq$0)["compare"](high)(low))["tag"] === "Less", (__ssrg$instance$Ord$1(__ssrg$instance$Eq$0)["compare"](high)(low))["tag"] !== "Greater"] as const)), () => _ssrg_effect_flatMap(_ssrg_console_println(_ssrg_show_tupleShow<readonly [boolean, boolean, boolean]>(_ssrg_show_boolShow, _ssrg_show_boolShow, _ssrg_show_boolShow)["show"]([((ordered(low)(high)(__ssrg$instance$Ord$1(__ssrg$instance$Eq$0))) as boolean), ((referenced(high)(low)(__ssrg$instance$Ord$1(__ssrg$instance$Eq$0))) as boolean), section(undefined)] as const)), () => _ssrg_effect_flatMap(_ssrg_console_println(_ssrg_show_tupleShow<readonly [boolean, boolean, boolean, boolean]>(_ssrg_show_boolShow, _ssrg_show_boolShow, _ssrg_show_boolShow, _ssrg_show_boolShow)["show"]([(_ssrg_int_ord_dictionary["compare"](1)(2))["tag"] === "Less", (_ssrg_bool_ord_dictionary["compare"](false)(true))["tag"] === "Less", (_ssrg_unit_ord_dictionary["compare"](undefined)(undefined))["tag"] !== "Greater", (_ssrg_string_ord_dictionary["compare"]("a")("b"))["tag"] === "Less"] as const)), () => _ssrg_console_println(_ssrg_show_boolShow["show"]((_ssrg_string_ord_dictionary["compare"]("𐀀")("\u{e000}"))["tag"] === "Greater"))))))); })(); })()
